import { Drone, Part, Pilot, Projectile,TacticCard } from "./types";

export const rdlTorso: Part[] = [
  {
    "id": "012",
    "name": "RT-06「マイア」戦闘コア",
    "score": 15,
    "structure": 2,
    "armor": 6,
    "parray": 0,
    "dodge": 0,
    "electronic": 2,
    "type": "torso",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "014",
    "name": "RT-07T「デューン」 戦術コア",
    "score": 62,
    "structure": 4,
    "armor": 5,
    "parray": 0,
    "dodge": 0,
    "electronic": 3,
    "type": "torso",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "015",
    "name": "RT-08「テンペスト」 砲戦コア",
    "score": 62,
    "structure": 2,
    "armor": 7,
    "parray": 0,
    "dodge": 0,
    "electronic": 3,
    "type": "torso",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "016",
    "name": "RT-09A「ボルカノ」 装甲コア",
    "score": 66,
    "structure": 4,
    "armor": 6,
    "parray": 0,
    "dodge": 0,
    "electronic": 3,
    "type": "torso",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "projectile": ["268"]
  },
  {
    "id": "017",
    "name": "RT-15B「ラバー」強襲コア",
    "score": 59,
    "structure": 4,
    "armor": 5,
    "parray": 0,
    "dodge": 1,
    "electronic": 3,
    "type": "torso",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "projectile": ["268"]
  },
  {
    "id": "019",
    "name": "RT-15C「グレイシャ」強襲コア",
    "score": 56,
    "structure": 4,
    "armor": 5,
    "parray": 0,
    "dodge": 1,
    "electronic": 2,
    "type": "torso",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "projectile": ["268"]
  },
  {
    "id": "018",
    "name": "RT-15/EC「オーロラ」ECMコア",
    "score": 60,
    "structure": 4,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 3,
    "type": "torso",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "246",
    "name": "RT-09M「ボルカノM」装甲コア",
    "score": 66,
    "structure": 4,
    "armor": 6,
    "parray": 0,
    "dodge": 0,
    "electronic": 3,
    "type": "torso",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "projectile": ["268"]
  },
  {
    "id": "280",
    "name": "RT-09M II「ボルカノM II」装甲コア",
    "score": 66,
    "structure": 4,
    "armor": 6,
    "parray": 0,
    "dodge": 0,
    "electronic": 3,
    "type": "torso",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "projectile": ["268"]
  },
  {
    "id": "503",
    "name": "RT-16B 「アバランシェ」 強襲コア",
    "score": 60,
    "structure": 4,
    "armor": 5,
    "parray": 0,
    "dodge": 1,
    "electronic": 3,
    "type": "torso",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "projectile": ["268"]
  },
  {
    "id": "504",
    "name": "RT-15/S 「ニンバス」支援コア",
    "score": 60,
    "structure": 4,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 3,
    "type": "torso",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "505",
    "name": "RT-06E 「マイア」E 戦闘コア",
    "score": 21,
    "structure": 2,
    "armor": 6,
    "parray": 0,
    "dodge": 0,
    "electronic": 3,
    "type": "torso",
    "description": "",
    "imgSrc": "",
    "tags": []
  }
];

export const rdlChasis: Part[] = [
  {
    "id": "020",
    "name": "RL-06  標準下肢",
    "score": 18,
    "structure": 0,
    "armor": 5,
    "parray": 0,
    "dodge": 3,
    "electronic": 0,
    "type": "chasis",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "021",
    "name": "RL-08  装甲下肢",
    "score": 30,
    "structure": 1,
    "armor": 6,
    "parray": 0,
    "dodge": 3,
    "electronic": 0,
    "type": "chasis",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "022",
    "name": "RL-03D  「スウィフトステッド」高機動下肢",
    "score": 42,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 4,
    "electronic": 0,
    "type": "chasis",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "249",
    "name": "RL-08M  装甲下肢",
    "score": 30,
    "structure": 1,
    "armor": 6,
    "parray": 0,
    "dodge": 3,
    "electronic": 0,
    "type": "chasis",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "281",
    "name": "RL-08M II  装甲下肢",
    "score": 45,
    "structure": 1,
    "armor": 6,
    "parray": 0,
    "dodge": 3,
    "electronic": 0,
    "type": "chasis",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "506",
    "name": "RL-06M   標準下肢",
    "score": 18,
    "structure": 0,
    "armor": 5,
    "parray": 0,
    "dodge": 3,
    "electronic": 0,
    "type": "chasis",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "507",
    "name": "RL-06MS アシスト下肢",
    "score": 24,
    "structure": 0,
    "armor": 5,
    "parray": 0,
    "dodge": 3,
    "electronic": 0,
    "type": "chasis",
    "description": "",
    "imgSrc": "",
    "tags": []
  }
];

export const rdlLeftHand: Part[] = [
  {
    "id": "023",
    "name": "55型シールド+CC-6クリーバー",
    "score": 54,
    "structure": 0,
    "armor": 5,
    "parray": 2,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "024",
    "name": "55型シールド+CC-6クリーバー(D)",
    "score": 0,
    "structure": 0,
    "armor": 5,
    "parray": 2,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "029",
    "name": "ML-32 デュアルランチャー+ CC-3 ダガー",
    "score": 33,
    "structure": 0,
    "armor": 4,
    "parray": 1,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "032",
    "name": "R-20 肩掛けレールガン(L)",
    "score": 51,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "034",
    "name": "77型ブルウォーク",
    "score": 50,
    "structure": 0,
    "armor": 8,
    "parray": 1,
    "dodge": -2,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "035",
    "name": "77型ブルウォーク (D)",
    "score": 0,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "040",
    "name": "SPHX-3 支持アーム",
    "score": 42,
    "structure": 0,
    "armor": 4,
    "parray": 1,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "041",
    "name": "L-320 SMMG + 55 型シールド + CC-6 クリーバー",
    "score": 51,
    "structure": 0,
    "armor": 5,
    "parray": 2,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "042",
    "name": "L-320 SMMG + 55 型シールド + CC-6 クリーバー (D)",
    "score": 0,
    "structure": 0,
    "armor": 5,
    "parray": 2,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "045",
    "name": "79型コンバットシールド",
    "score": 56,
    "structure": 0,
    "armor": 6,
    "parray": 2,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "050",
    "name": "FCC-12 「ビッグハンド」 グラッパー",
    "score": 69,
    "structure": 0,
    "armor": 4,
    "parray": 3,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "053",
    "name": "55型シールド+PC-9ショットガン(L)",
    "score": 48,
    "structure": 0,
    "armor": 5,
    "parray": 2,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "054",
    "name": "55型シールド+PC-9ショットガン(L) (D)",
    "score": 0,
    "structure": 0,
    "armor": 5,
    "parray": 2,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "056",
    "name": "G/AC-6ロケットランチャー",
    "score": 36,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "057",
    "name": "G/AC-6ロケットランチャー (D)",
    "score": 0,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "062",
    "name": "62型 バックラー+CC-20 サーベル(L)",
    "score": 63,
    "structure": 0,
    "armor": 5,
    "parray": 3,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "064",
    "name": "55型シールド+MESビーコンランチャ",
    "score": 45,
    "structure": 0,
    "armor": 5,
    "parray": 2,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "065",
    "name": "55型シールド+MESビーコンランチャ (D)",
    "score": 0,
    "structure": 0,
    "armor": 5,
    "parray": 2,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "252",
    "name": "77型ブルウォーク(初期モデル)",
    "score": 50,
    "structure": 0,
    "armor": 8,
    "parray": 1,
    "dodge": -2,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "253",
    "name": "77型ブルウォーク(初期モデル) (D)",
    "score": 0,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "282",
    "name": "L-330 SMMG + 77B型ブルウォーク",
    "score": 56,
    "structure": 0,
    "armor": 9,
    "parray": 1,
    "dodge": -3,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "283",
    "name": "L-330 SMMG + 77B型ブルウォーク（D）",
    "score": 0,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "510",
    "name": "55型シールド + PC-9Kショットガン(L)",
    "score": 63,
    "structure": 0,
    "armor": 5,
    "parray": 2,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "511",
    "name": "55型シールド + PC-9Kショットガン(L) (D)",
    "score": 0,
    "structure": 0,
    "armor": 5,
    "parray": 2,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "514",
    "name": "AH-21ピストル+ CC-50 パイルバンカー (L)",
    "score": 63,
    "structure": 0,
    "armor": 4,
    "parray": 1,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "515",
    "name": "AH-21ピストル+ CC-50 パイルバンカー(L) (D)",
    "score": 0,
    "structure": 0,
    "armor": 4,
    "parray": 1,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "520",
    "name": "55型シールド",
    "score": 30,
    "structure": 0,
    "armor": 5,
    "parray": 2,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  }
];

export const rdlRightHand: Part[] = [
  {
    "id": "025",
    "name": "AC-32 自動ライフル",
    "score": 24,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "026",
    "name": "AC-32 自動ライフル(D)",
    "score": 0,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "027",
    "name": "AC-32M マークスマン・ライフル",
    "score": 33,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "028",
    "name": "AC-32M マークスマン・ライフル (D)",
    "score": 0,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "030",
    "name": "AC-150 HMG",
    "score": 42,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": -2,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "031",
    "name": "AC-150 HMG(D)",
    "score": 0,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "033",
    "name": "R-20 肩掛けレールガン(R)",
    "score": 51,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "036",
    "name": "CC-4 クリーバー(R)",
    "score": 39,
    "structure": 0,
    "armor": 4,
    "parray": 1,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "038",
    "name": "ACX-350 「ストゥレイタス」プロトタイプ HMG",
    "score": 48,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": -2,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "039",
    "name": "ACX-350 「ストゥレイタス」プロトタイプ HMG (D)",
    "score": 0,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "043",
    "name": "R-35 大型レールガン",
    "score": 54,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": -2,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "044",
    "name": "R-35 大型レールガン(D)",
    "score": 0,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "046",
    "name": "55型シールド+PC-9ショットガン(R)",
    "score": 48,
    "structure": 0,
    "armor": 5,
    "parray": 2,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "047",
    "name": "55型シールド+PC-9ショットガン(R) (D)",
    "score": 0,
    "structure": 0,
    "armor": 5,
    "parray": 2,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "048",
    "name": "55型シールド+PC-9ショットガン(R) + スモークグレネード (R)",
    "score": 57,
    "structure": 0,
    "armor": 5,
    "parray": 2,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "049",
    "name": "55型シールド+PC-9ショットガン(R) + スモークグレネード (R) (D)",
    "score": 0,
    "structure": 0,
    "armor": 5,
    "parray": 2,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "051",
    "name": "L-320 SMMG + CC-90グリーブ",
    "score": 63,
    "structure": 0,
    "armor": 4,
    "parray": 1,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "052",
    "name": "L-320 SMMG + CC-90グリーブ (D)",
    "score": 0,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "055",
    "name": "CC-100 「ヘラクレス」 流星錘",
    "score": 48,
    "structure": 0,
    "armor": 4,
    "parray": 1,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "058",
    "name": "AC-39 戦術ライフル",
    "score": 45,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "059",
    "name": "AC-39 戦術ライフル (D)",
    "score": 0,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "063",
    "name": "63型 アームキャノン+CC-20 サーベル(R)",
    "score": 66,
    "structure": 0,
    "armor": 4,
    "parray": 2,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "068",
    "name": "AC-161 SMG",
    "score": 45,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "069",
    "name": "AC-161 SMG(D)",
    "score": 0,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "254",
    "name": "L-320 SMMG + CC-90グリーブ(初期モデル)",
    "score": 63,
    "structure": 0,
    "armor": 4,
    "parray": 1,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "255",
    "name": "L-320 SMMG + CC-90グリーブ(初期モデル)(D)",
    "score": 0,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "284",
    "name": "L-330 SMMG + CC-85ロックソー",
    "score": 57,
    "structure": 0,
    "armor": 4,
    "parray": 1,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "285",
    "name": "L-330 SMMG + CC-85ロックソー（D）",
    "score": 0,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "508",
    "name": "55型シールド + PC-9Kショットガン(R)",
    "score": 63,
    "structure": 0,
    "armor": 5,
    "parray": 2,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "509",
    "name": "55型シールド + PC-9Kショットガン(R) (D)",
    "score": 0,
    "structure": 0,
    "armor": 5,
    "parray": 2,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "512",
    "name": "AH-21ピストル+ CC-50 パイルバンカー(R)",
    "score": 63,
    "structure": 0,
    "armor": 4,
    "parray": 1,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "513",
    "name": "AH-21ピストル+ CC-50 パイルバンカー (R)(D)",
    "score": 0,
    "structure": 0,
    "armor": 4,
    "parray": 1,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "516",
    "name": "AC-35スナイパーライフル",
    "score": 51,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "517",
    "name": "AC-35スナイパーライフル (D)",
    "score": 0,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "518",
    "name": "AC-32C自動ライフル",
    "score": 36,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "519",
    "name": "AC-32C自動ライフル (D)",
    "score": 0,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  }
];

export const rdlBackpack: Part[] = [
  {
    "id": "001",
    "name": "SH-15 野外修復システム",
    "score": 30,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 2,
    "electronic": 0,
    "type": "backpack",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "002",
    "name": "ECS-2 外部クーラー",
    "score": 33,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 1,
    "electronic": 0,
    "type": "backpack",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "003",
    "name": "AMS-190 アクティブ防護システム",
    "score": 27,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 0,
    "electronic": 1,
    "type": "backpack",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "004",
    "name": "ML-34 四連装ミサイルラック",
    "score": 39,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 1,
    "electronic": 0,
    "type": "backpack",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "005",
    "name": "LGP-80 長距離キャノン",
    "score": 33,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": -2,
    "electronic": 0,
    "type": "backpack",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "006",
    "name": "GLP-15 地雷敷設機",
    "score": 30,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "backpack",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "007",
    "name": "MUD-1 「ムック」 ECM バックパック",
    "score": 33,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 1,
    "electronic": 1,
    "type": "backpack",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "008",
    "name": "CP-3 ビーコンバックパック",
    "score": 36,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "backpack",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "009",
    "name": "MUE/N-20 「エコース」支援型バックパック",
    "score": 30,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "backpack",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "010",
    "name": "TB-600 ジェットパック",
    "score": 48,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 2,
    "electronic": 0,
    "type": "backpack",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "011",
    "name": "ML-92 二連装ミサイルラック",
    "score": 20,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "backpack",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "264",
    "name": "AMS-192 アクティブ防護システム",
    "score": 27,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 0,
    "electronic": 1,
    "type": "backpack",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "286",
    "name": "AMS-193 アクティブ防護システム",
    "score": 27,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 0,
    "electronic": 1,
    "type": "backpack",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "500",
    "name": "HD-2データパック",
    "score": 24,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 0,
    "electronic": 1,
    "type": "backpack",
    "description": "任务",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "501",
    "name": "ML-94四連装ミサイルラック",
    "score": 48,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "backpack",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "projectile": [
      "521"
    ]
  },
  {
    "id": "502",
    "name": "CP-4ドローンパック",
    "score": 36,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "backpack",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "projectile": [
      "522"
    ]
  }
];

export const rdlProjectiles: Projectile[] = [
  {
    "id": "070",
    "name": "GA-3 HEグレネード",
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 4,
    "electronic": 0,
    "stance": "offensive",
    "imgSrc": ""
  },
  {
    "id": "071",
    "name": "MC-3 「レイザ」ミサイル",
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 6,
    "electronic": 1,
    "stance": "offensive",
    "imgSrc": ""
  },
  {
    "id": "072",
    "name": "MESビーコン",
    "structure": 0,
    "armor": 1,
    "parray": 0,
    "dodge": 0,
    "electronic": 1,
    "stance": "offensive",
    "imgSrc": ""
  },
  {
    "id": "073",
    "name": "MR-9 「ファルコン」 ミサイル",
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 4,
    "electronic": 1,
    "stance": "offensive",
    "imgSrc": ""
  },
  {
    "id": "074",
    "name": "GM-35 対装甲地雷",
    "structure": 0,
    "armor": 2,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "stance": "offensive",
    "imgSrc": ""
  },
  {
    "id": "075",
    "name": "B3/1リンクビーコン",
    "structure": 0,
    "armor": 2,
    "parray": 0,
    "dodge": 0,
    "electronic": 3,
    "stance": "offensive",
    "imgSrc": ""
  },
  {
    "id": "076",
    "name": "B3/2デコイビーコン",
    "structure": 2,
    "armor": 2,
    "parray": 0,
    "dodge": 0,
    "electronic": 3,
    "stance": "offensive",
    "imgSrc": ""
  },
  {
    "id": "077",
    "name": "B3/3戦術ビーコン",
    "structure": 0,
    "armor": 2,
    "parray": 0,
    "dodge": 0,
    "electronic": 3,
    "stance": "offensive",
    "imgSrc": ""
  },
  {
    "id": "521",
    "name": "MR-10 「ケストレル」ミサイル",
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 4,
    "electronic": 1,
    "stance": "offensive",
    "imgSrc": ""
  }
];

export const rdlDrones: Drone[] = [
  {
    "id": "078",
    "name": "DTG-30M「ハイエナ」MG型",
    "score": 42,
    "structure": 2,
    "armor": 5,
    "parray": 0,
    "dodge": 0,
    "electronic": 2,
    "type": "medium",
    "move": 0,
    "stance": "offensive",
    "description": ""
  },
  {
    "id": "079",
    "name": "DTG-30S 「ハイエナ」ミサイル型",
    "score": 33,
    "structure": 2,
    "armor": 5,
    "parray": 0,
    "dodge": 0,
    "electronic": 2,
    "type": "medium",
    "move": 0,
    "stance": "offensive",
    "description": "",
    "projectile": [
      "071"
    ]
  },
  {
    "id": "080",
    "name": "DTG-30R 「ハイエナ」レーダー型",
    "score": 27,
    "structure": 2,
    "armor": 5,
    "parray": 0,
    "dodge": 0,
    "electronic": 2,
    "type": "medium",
    "move": 0,
    "stance": "offensive",
    "description": ""
  },
  {
    "id": "522",
    "name": "MD-1「ドラゴンフライ」小型偵察機",
    "score": 0,
    "structure": 0,
    "armor": 2,
    "parray": 0,
    "dodge": 2,
    "electronic": 3,
    "type": "small",
    "move": 0,
    "stance": "offensive",
    "description": ""
  }
];

export const unTorso: Part[] = [
  {
    "id": "091",
    "name": "TM31C 「グレーウルフ」戦闘コア",
    "score": 45,
    "structure": 4,
    "armor": 4,
    "parray": 0,
    "dodge": 1,
    "electronic": 3,
    "type": "torso",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "projectile": ["155"]
  },
  {
    "id": "092",
    "name": "TM31R 「カラカル」戦闘コア",
    "score": 54,
    "structure": 4,
    "armor": 4,
    "parray": 0,
    "dodge": 1,
    "electronic": 4,
    "type": "torso",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "094",
    "name": "TM39 「ヴァイパー」低姿勢コア",
    "score": 63,
    "structure": 3,
    "armor": 3,
    "parray": 0,
    "dodge": 1,
    "electronic": 5,
    "type": "torso",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "096",
    "name": "TM641 「オクトパス」ステルスコア",
    "score": 81,
    "structure": 3,
    "armor": 3,
    "parray": 0,
    "dodge": 1,
    "electronic": 5,
    "type": "torso",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "097",
    "name": "TM35N 「アリゲーター」電子戦コア",
    "score": 72,
    "structure": 4,
    "armor": 5,
    "parray": 0,
    "dodge": 1,
    "electronic": 4,
    "type": "torso",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "098",
    "name": "TM35B 「バイソン」突撃コア",
    "score": 72,
    "structure": 4,
    "armor": 5,
    "parray": 0,
    "dodge": 1,
    "electronic": 4,
    "type": "torso",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "247",
    "name": "TM641O 「オクトパス」ステルスコア試作型",
    "score": 81,
    "structure": 3,
    "armor": 3,
    "parray": 0,
    "dodge": 1,
    "electronic": 5,
    "type": "torso",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  // {
  //   "id": "555",
  //   "name": "TM35BT「タウルス」実験型コア",
  //   "score": 84,
  //   "armor": 5,
  //   "structure": 4,
  //   "parray": 0,
  //   "dodge": 1,
  //   "electronic": 4,
  //   "type": "torso",
  //    "description": "",
  //   "imgSrc": "",
  //   "tags": []
  // }
];

export const unChasis: Part[] = [
  {
    "id": "099",
    "name": "LM231   標準下肢",
    "score": 27,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 4,
    "electronic": 0,
    "type": "chasis",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "100",
    "name": "LM210S  隠密下肢",
    "score": 39,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 4,
    "electronic": 0,
    "type": "chasis",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "101",
    "name": "LM213B 格闘下肢",
    "score": 57,
    "structure": 1,
    "armor": 4,
    "parray": 0,
    "dodge": 4,
    "electronic": 0,
    "type": "chasis",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "250",
    "name": "LM210SO 隠密下肢試作型",
    "score": 39,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 4,
    "electronic": 0,
    "type": "chasis",
    "description": "",
    "imgSrc": "",
    "tags": []
  }
];

export const unLeftHand: Part[] = [
  {
    "id": "103",
    "name": "S9 「メテオ」シールド + M5 パイルバンカー",
    "score": 57,
    "structure": 0,
    "armor": 4,
    "parray": 2,
    "dodge": 1,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "107",
    "name": "S100 シールド  + グレネードポッド",
    "score": 66,
    "structure": 0,
    "armor": 5,
    "parray": 2,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "108",
    "name": "S100 シールド  + グレネードポッド (D)",
    "score": 0,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "111",
    "name": "RH21 ピストル + M3 振動剑 (L)",
    "score": 45,
    "structure": 0,
    "armor": 3,
    "parray": 1,
    "dodge": 1,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "112",
    "name": "RH21 ピストル + M3 振動剑 (L) (D)",
    "score": 0,
    "structure": 0,
    "armor": 3,
    "parray": 1,
    "dodge": 1,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "117",
    "name": "MDXS 「フェアリー」システム + R6 SMG (L)",
    "score": 45,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 2,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "118",
    "name": "MDXS 「フェアリー」システム + R6 SMG (L) (D)",
    "score": 0,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 2,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "121",
    "name": "MSH1 アシストアーム(L)",
    "score": 24,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "126",
    "name": "K9 ネイルガン + M14BO 「脇差」",
    "score": 42,
    "structure": 0,
    "armor": 3,
    "parray": 1,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "129",
    "name": "RKG70  ミサイルポッド",
    "score": 42,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "130",
    "name": "RKG70  ミサイルポッド (D)",
    "score": 0,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "131",
    "name": "M3S 振動剑(L)",
    "score": 42,
    "structure": 0,
    "armor": 3,
    "parray": 1,
    "dodge": 1,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "135",
    "name": "M4 振動剑 + グレネードポッド(L)",
    "score": 54,
    "structure": 0,
    "armor": 3,
    "parray": 1,
    "dodge": 1,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "139",
    "name": "MX82 多用途ウィップ",
    "score": 48,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 1,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "142",
    "name": "S100 シールド",
    "score": 48,
    "structure": 0,
    "armor": 5,
    "parray": 2,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "143",
    "name": "S100 シールド(D)",
    "score": 0,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "144",
    "name": "K7 ネイルガン + S10 シールド",
    "score": 54,
    "structure": 0,
    "armor": 5,
    "parray": 2,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "146",
    "name": "G6 ショットガン + グレネードポッド",
    "score": 75,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 1,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "147",
    "name": "G6ショットガン+グレネードポッド (D)",
    "score": 0,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 1,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "150",
    "name": "RHX23 「 レインストーム」アサルトピストル (L)",
    "score": 57,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 2,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "151",
    "name": "RHX23 「 レインストーム」アサルトピストル (L) (D)",
    "score": 0,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 2,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "256",
    "name": "K9 ネイルガン + M14BO 「脇差」試作型 (L)",
    "score": 42,
    "structure": 0,
    "armor": 3,
    "parray": 1,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  }
];

export const unRightHand: Part[] = [
  {
    "id": "104",
    "name": "R7 オートライフル",
    "score": 42,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "105",
    "name": "R7 オートライフル (D)",
    "score": 0,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "106",
    "name": "R33 スナイパーライフル",
    "score": 39,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "109",
    "name": "R6 SMG",
    "score": 54,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 1,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "110",
    "name": "R6 SMG (D)",
    "score": 0,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 1,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "113",
    "name": "RH21 ピストル + M3 振動剑 (R)",
    "score": 45,
    "structure": 0,
    "armor": 3,
    "parray": 1,
    "dodge": 1,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "114",
    "name": "RH21 ピストル + M3 振動剑 (R) (D)",
    "score": 0,
    "structure": 0,
    "armor": 3,
    "parray": 1,
    "dodge": 1,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "115",
    "name": "S100 シールド + R6SS SMG",
    "score": 63,
    "structure": 0,
    "armor": 5,
    "parray": 2,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "116",
    "name": "S100 シールド + R6SS SMG(D)",
    "score": 0,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "119",
    "name": "MDXS 「フェアリー」システム + R6 SMG (R)",
    "score": 45,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 2,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "120",
    "name": "MDXS 「フェアリー」システム + R6 SMG (R) (D)",
    "score": 0,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 2,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "122",
    "name": "IGX920 ヘビーイオンガン",
    "score": 60,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": -2,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "throwIndex": "123"
  },
  {
    "id": "123",
    "name": "IGX920 ヘビーイオンガン (D)",
    "score": 0,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "124",
    "name": "R6SD SMG",
    "score": 60,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 1,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "125",
    "name": "R6SD SMG (D)",
    "score": 0,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 1,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "127",
    "name": "R9B タクティカルライフル",
    "score": 48,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "128",
    "name": "R9B タクティカルライフル (D)",
    "score": 0,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "133",
    "name": "M3S 振動剑 (R)",
    "score": 42,
    "structure": 0,
    "armor": 3,
    "parray": 1,
    "dodge": 1,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "137",
    "name": "M4 振動剑 + グレネードポッド(R)",
    "score": 54,
    "structure": 0,
    "armor": 3,
    "parray": 1,
    "dodge": 1,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "140",
    "name": "IGX350 イオンショットガン",
    "score": 45,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "141",
    "name": "IGX350 イオンショットガン (D)",
    "score": 0,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "145",
    "name": "M15BO 「打刀」",
    "score": 81,
    "structure": 0,
    "armor": 4,
    "parray": 2,
    "dodge": 2,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "148",
    "name": "G6ショットガン+ M5 パイルバンカー",
    "score": 69,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 1,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "149",
    "name": "G6ショットガン+ M5 パイルバンカー (D)",
    "score": 0,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 1,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "152",
    "name": "RHX23「 レインストーム」アサルトピストル(R)",
    "score": 57,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 2,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "153",
    "name": "RHX23「 レインストーム」アサルトピストル(R) (D)",
    "score": 0,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 2,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "257",
    "name": "K9 ネイルガン + M14BO 「脇差」試作型(R)",
    "score": 42,
    "structure": 0,
    "armor": 3,
    "parray": 1,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "556",
    "name": "R7MG LMG",
    "score": 50,
    "armor": 3,
    "structure": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "imgSrc": "",
    "description": "",
    "tags": []
  },
  {
    "id": "557",
    "name": "R7MG LMG (D)",
    "score": 0,
    "armor": 3,
    "structure": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": "",
    "type": "rightHand",
    "imgSrc": "",
    "tags": []
  }
];

export const unProjectiles: Projectile[] = [
  {
    "id": "154",
    "name": "M7 グレネード",
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 2,
    "electronic": 0,
    "stance": "offensive",
    "imgSrc": ""
  },
  {
    "id": "155",
    "name": "M9 スタングレネード",
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 2,
    "electronic": 0,
    "stance": "offensive",
    "imgSrc": ""
  },
  {
    "id": "156",
    "name": "SGM2 「ユウレイグモ」自律型地雷",
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 2,
    "electronic": 2,
    "stance": "offensive",
    "imgSrc": ""
  },
  {
    "id": "157",
    "name": "RKG70 連装ミサイル",
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 3,
    "electronic": 1,
    "stance": "offensive",
    "imgSrc": ""
  },
  {
    "id": "158",
    "name": "DBP 「亀甲」機動バリケード",
    "structure": 0,
    "armor": 5,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "stance": "offensive",
    "imgSrc": ""
  }
];

export const unBackpack: Part[] = [
  {
    "id": "081",
    "name": "EBS/X40 アーマーチャージャー",
    "score": 39,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 2,
    "electronic": 0,
    "type": "backpack",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "082",
    "name": "GSD2A 「ユウレイグモ」自律型地雷ラック",
    "score": 21,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "backpack",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "083",
    "name": "CSC60 冷却剤タンク",
    "score": 27,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 1,
    "electronic": 0,
    "type": "backpack",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "084",
    "name": "DBP 「亀甲」バリケードラック",
    "score": 39,
    "structure": 0,
    "armor": 5,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "backpack",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "085",
    "name": "AMDS210 「デルフィニウム」ラック",
    "score": 30,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "backpack",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "086",
    "name": "RKG70 アーモーパック",
    "score": 21,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "backpack",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "087",
    "name": "MSH2 スタビライザーアーム",
    "score": 24,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "backpack",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "088",
    "name": "JP1 ジェットパック",
    "score": 57,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 2,
    "electronic": 0,
    "type": "backpack",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "089",
    "name": "EC50 電子戦ポッド",
    "score": 42,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 1,
    "electronic": 1,
    "type": "backpack",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "090",
    "name": "OCSP オーバーロードパック",
    "score": 49,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 2,
    "electronic": 0,
    "type": "backpack",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "265",
    "name": "EBS/X40 アーマーチャージャー試作型",
    "score": 39,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 2,
    "electronic": 0,
    "type": "backpack",
    "description": "",
    "imgSrc": "",
    "tags": []
  }
];

export const unDrones: Drone[] = [
  {
    "id": "159",
    "name": "AMDS210 「デルフィニウム」自動防衛システム",
    "score": 0,
    "structure": 0,
    "armor": 2,
    "parray": 0,
    "dodge": 0,
    "electronic": 2,
    "type": "small",
    "move": 0,
    "stance": "offensive",
    "description": ""
  },
  {
    "id": "160",
    "name": "ADK15D 「ヤマアラシ」CIWS型",
    "score": 48,
    "structure": 2,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 2,
    "type": "medium",
    "move": 0,
    "stance": "offensive",
    "description": ""
  },
  {
    "id": "161",
    "name": "ADK15/MAS 「ヤマアラシ」マイクロウェーブ型",
    "score": 30,
    "structure": 2,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 2,
    "type": "medium",
    "move": 0,
    "stance": "offensive",
    "description": ""
  },
  {
    "id": "162",
    "name": "ADK30C 「タランチュラ」 輸送型",
    "score": 12,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 5,
    "electronic": 2,
    "type": "medium",
    "move": 0,
    "stance": "offensive",
    "description": ""
  },
  {
    "id": "163",
    "name": "ADK30F 「タランチュラ」火力型",
    "score": 33,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 5,
    "electronic": 2,
    "type": "medium",
    "move": 0,
    "stance": "offensive",
    "description": ""
  },
  {
    "id": "164",
    "name": "ADK60R「レイヴン」偵察型",
    "score": 33,
    "structure": 0,
    "armor": 1,
    "parray": 0,
    "dodge": 7,
    "electronic": 3,
    "type": "medium",
    "move": 0,
    "stance": "offensive",
    "description": ""
  },
  {
    "id": "165",
    "name": "ADK60EC「レイヴン」電子戦型",
    "score": 33,
    "structure": 0,
    "armor": 1,
    "parray": 0,
    "dodge": 7,
    "electronic": 3,
    "type": "medium",
    "move": 0,
    "stance": "offensive",
    "description": ""
  },
  {
    "id": "166",
    "name": "ADK60S「レイヴン」妨害型",
    "score": 51,
    "structure": 0,
    "armor": 1,
    "parray": 0,
    "dodge": 7,
    "electronic": 3,
    "type": "medium",
    "move": 0,
    "stance": "offensive",
    "description": ""
  },
  {
    "id": "167",
    "name": "SGM-2  「ユウレイグモ」自律型地雷（展开）",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 2,
    "electronic": 2,
    "type": "small",
    "move": 0,
    "stance": "offensive",
    "description": ""
  }
];

export const unPilots: Pilot[] = [
  {
    "id": "LPA-19",
    "name": "クォーツ",
    "score": 24,
    "LV": 4,
    "faction": "UN",
    "swift": 2,
    "melee": 5,
    "projectile": 4,
    "firing": 4,
    "moving": 6,
    "tactic": 6,
    "trait": "冷静",
    "traitDescription": "· ターン終了したとき、リンク値１回復する。"
  },
  {
    "id": "LPA-20",
    "name": "パンツァー",
    "score": 15,
    "LV": 4,
    "faction": "UN",
    "swift": 3,
    "melee": 3,
    "projectile": 2,
    "firing": 5,
    "moving": 2,
    "tactic": 6,
    "trait": "ブロック",
    "traitDescription": "敵ユニットが本機の近接ロックから離脱する場合、追加で移動力1またはリンク値1を支払わなければない。"
  },
  {
    "id": "LPA-21",
    "name": "オニビ",
    "score": 18,
    "LV": 4,
    "faction": "UN",
    "swift": 3,
    "melee": 7,
    "projectile": 6,
    "firing": 1,
    "moving": 5,
    "tactic": 5,
    "trait": "ステルス",
    "traitDescription": "本機が光学迷彩を発動している場合、または低姿勢である場合、本機はほかのユニットをすり抜けて移動できる。"
  },
  {
    "id": "LPA-22",
    "name": "ヨユウ",
    "score": 21,
    "LV": 4,
    "faction": "UN",
    "swift": 7,
    "melee": 4,
    "projectile": 5,
    "firing": 3,
    "moving": 4,
    "tactic": 1,
    "trait": "挑発",
    "traitDescription": "本機が電子戦対抗ロールに成功した場合、対抗ロールを行った敵機甲を攻撃態勢へ変更させられる。"
  },
  {
    "id": "LPA-23",
    "name": "オニキス",
    "score": 21,
    "LV": 4,
    "faction": "UN",
    "swift": 6,
    "melee": 2,
    "projectile": 3,
    "firing": 5,
    "moving": 4,
    "tactic": 4,
    "trait": "不屈",
    "traitDescription": "本機は大型ユニットをクラッシュできる。"
  },
  {
    "id": "LPA-24",
    "name": "シーロック",
    "score": 21,
    "LV": 4,
    "faction": "UN",
    "swift": 5,
    "melee": 4,
    "projectile": 8,
    "firing": 4,
    "moving": 7,
    "tactic": 3,
    "trait": "チェース",
    "traitDescription": "脆弱トークン付いてるユニットを攻撃する場合、攻撃ロール出目{目}は{重撃}になる。"
  },
  {
    "id": "LPA-27",
    "name": "チャージャー1",
    "score": 9,
    "LV": 4,
    "faction": "UN",
    "swift": 3,
    "melee": 7,
    "projectile": 6,
    "firing": 2,
    "moving": 5,
    "tactic": 5,
    "trait": "",
    "traitDescription": "303中隊のトレーナーチャージャー。"
  },
  {
    "id": "LPA-28",
    "name": "チャージャー2",
    "score": 9,
    "LV": 4,
    "faction": "UN",
    "swift": 3,
    "melee": 7,
    "projectile": 6,
    "firing": 2,
    "moving": 5,
    "tactic": 5,
    "trait": "",
    "traitDescription": "303中隊のトレーナーチャージャー。"
  },
  {
    "id": "LPA-29",
    "name": "チャージャー3",
    "score": 9,
    "LV": 4,
    "faction": "UN",
    "swift": 3,
    "melee": 7,
    "projectile": 6,
    "firing": 2,
    "moving": 5,
    "tactic": 5,
    "trait": "",
    "traitDescription": "303中隊のトレーナーチャージャー。"
  },
  {
    "id": "LPA-30",
    "name": "チャージャー4",
    "score": 9,
    "LV": 4,
    "faction": "UN",
    "swift": 3,
    "melee": 7,
    "projectile": 6,
    "firing": 2,
    "moving": 5,
    "tactic": 5,
    "trait": "",
    "traitDescription": "303中隊のトレーナーチャージャー。"
  },
  {
    "id": "LPA-31",
    "name": "ライフルマン1",
    "score": 6,
    "LV": 4,
    "faction": "UN",
    "swift": 4,
    "melee": 3,
    "projectile": 2,
    "firing": 5,
    "moving": 2,
    "tactic": 6,
    "trait": "",
    "traitDescription": "303中隊のトレーナーライフルマン。"
  },
  {
    "id": "LPA-32",
    "name": "ライフルマン2",
    "score": 6,
    "LV": 4,
    "faction": "UN",
    "swift": 4,
    "melee": 3,
    "projectile": 2,
    "firing": 5,
    "moving": 2,
    "tactic": 6,
    "trait": "",
    "traitDescription": "303中隊のトレーナーライフルマン。"
  },
  {
    "id": "LPA-33",
    "name": "ライフルマン3",
    "score": 6,
    "LV": 4,
    "faction": "UN",
    "swift": 4,
    "melee": 3,
    "projectile": 2,
    "firing": 5,
    "moving": 2,
    "tactic": 6,
    "trait": "",
    "traitDescription": "303中隊のトレーナーライフルマン。"
  },
  {
    "id": "LPA-34",
    "name": "ライフルマン4",
    "score": 6,
    "LV": 4,
    "faction": "UN",
    "swift": 4,
    "melee": 3,
    "projectile": 2,
    "firing": 5,
    "moving": 2,
    "tactic": 6,
    "trait": "",
    "traitDescription": "303中隊のトレーナーライフルマン。"
  },
  // {
  //   "id": "LPA-66",
  //   "name": "ライフルマン66",
  //   "score": 9,
  //   "LV": 4,
  //   "faction": "UN",
  //   "swift": 3,
  //   "melee": 7,
  //   "projectile": 6,
  //   "firing": 2,
  //   "moving": 5,
  //   "tactic": 5,
  //   "trait": "",
  //   "traitDescription": "303中隊のトレーナーライフルマン。"
  // }
];

export const rdlPilots: Pilot[] = [
  {
    "id": "FPA-01",
    "name": "ミスティ",
    "score": 15,
    "LV": 4,
    "faction": "RDL",
    "swift": 7,
    "melee": 4,
    "projectile": 5,
    "firing": 3,
    "moving": 3,
    "tactic": 2,
    "trait": "変化",
    "traitDescription": "· 戦術タイミングでは、任意タイミングのアクションでリードアクションを実行してもよい。"
  },
  {
    "id": "FPA-02",
    "name": "スパイク",
    "score": 15,
    "LV": 4,
    "faction": "RDL",
    "swift": 3,
    "melee": 7,
    "projectile": 6,
    "firing": 2,
    "moving": 5,
    "tactic": 5,
    "trait": "鷹の目",
    "traitDescription": "· 射撃アクション、常に装甲貫通1を得る。"
  },
  {
    "id": "FPA-03",
    "name": "ウー",
    "score": 12,
    "LV": 4,
    "faction": "RDL",
    "swift": 6,
    "melee": 2,
    "projectile": 3,
    "firing": 7,
    "moving": 4,
    "tactic": 4,
    "trait": "頑健",
    "traitDescription": "·搭乗している機甲がパーツを失うことに、リンク値が減らない。"
  },
  {
    "id": "FPA-04",
    "name": "ハンマーヘッド",
    "score": 10,
    "LV": 4,
    "faction": "RDL",
    "swift": 4,
    "melee": 3,
    "projectile": 2,
    "firing": 5,
    "moving": 2,
    "tactic": 6,
    "trait": "猛攻",
    "traitDescription": "·[攻撃態勢] 近接アクション は{Eye}を{Light Hit}.と見なしてもよい。"
  },
  {
    "id": "FPA-05",
    "name": "アンサー",
    "score": 15,
    "LV": 4,
    "faction": "RDL",
    "swift": 5,
    "melee": 6,
    "projectile": 9,
    "firing": 3,
    "moving": 8,
    "tactic": 4,
    "trait": "スタミナ",
    "traitDescription": "·搭乗した機甲の下肢に構造値がなければ、構造値2を持っているように扱う。"
  },
  {
    "id": "FPA-06",
    "name": "キーホール",
    "score": 12,
    "LV": 4,
    "faction": "RDL",
    "swift": 2,
    "melee": 5,
    "projectile": 4,
    "firing": 6,
    "moving": 6,
    "tactic": 7,
    "trait": "増幅",
    "traitDescription": "・搭乗した機甲のオーラ、電子攻撃と電子サポートの射程が+1グリッド。"
  },
  {
    "id": "FPA-09",
    "name": "突撃兵-09",
    "score": 6,
    "LV": 4,
    "faction": "RDL",
    "swift": 6,
    "melee": 2,
    "projectile": 3,
    "firing": 7,
    "moving": 4,
    "tactic": 4,
    "trait": "",
    "traitDescription": "試験評価中隊066の新米隊員"
  },
  {
    "id": "FPA-10",
    "name": "突撃兵-10",
    "score": 6,
    "LV": 4,
    "faction": "RDL",
    "swift": 6,
    "melee": 2,
    "projectile": 3,
    "firing": 7,
    "moving": 4,
    "tactic": 4,
    "trait": "",
    "traitDescription": "試験評価中隊066の新米隊員"
  },
  {
    "id": "FPA-11",
    "name": "突撃兵-11",
    "score": 6,
    "LV": 4,
    "faction": "RDL",
    "swift": 6,
    "melee": 2,
    "projectile": 3,
    "firing": 7,
    "moving": 4,
    "tactic": 4,
    "trait": "",
    "traitDescription": "試験評価中隊066の新米隊員"
  },
  {
    "id": "FPA-12",
    "name": "突撃兵-12",
    "score": 6,
    "LV": 4,
    "faction": "RDL",
    "swift": 6,
    "melee": 2,
    "projectile": 3,
    "firing": 7,
    "moving": 4,
    "tactic": 4,
    "trait": "",
    "traitDescription": "試験評価中隊066の新米隊員"
  },
  {
    "id": "FPA-13",
    "name": "突撃兵-13",
    "score": 6,
    "LV": 4,
    "faction": "RDL",
    "swift": 6,
    "melee": 2,
    "projectile": 3,
    "firing": 7,
    "moving": 4,
    "tactic": 4,
    "trait": "",
    "traitDescription": "試験評価中隊066の新米隊員"
  },
  {
    "id": "FPA-14",
    "name": "斥候-14",
    "score": 9,
    "LV": 4,
    "faction": "RDL",
    "swift": 5,
    "melee": 6,
    "projectile": 7,
    "firing": 4,
    "moving": 7,
    "tactic": 3,
    "trait": "",
    "traitDescription": "試験評価隊066の新米スカウト"
  },
  {
    "id": "FPA-15",
    "name": "斥候-15",
    "score": 9,
    "LV": 4,
    "faction": "RDL",
    "swift": 5,
    "melee": 6,
    "projectile": 7,
    "firing": 4,
    "moving": 7,
    "tactic": 3,
    "trait": "",
    "traitDescription": "試験評価隊066の新米スカウト"
  },
  {
    "id": "FPA-16",
    "name": "斥候-16",
    "score": 9,
    "LV": 4,
    "faction": "RDL",
    "swift": 5,
    "melee": 6,
    "projectile": 7,
    "firing": 4,
    "moving": 7,
    "tactic": 3,
    "trait": "",
    "traitDescription": "試験評価隊066の新米スカウト"
  },
  {
    "id": "FPA-17",
    "name": "斥候-17",
    "score": 9,
    "LV": 4,
    "faction": "RDL",
    "swift": 5,
    "melee": 6,
    "projectile": 7,
    "firing": 4,
    "moving": 7,
    "tactic": 3,
    "trait": "",
    "traitDescription": "試験評価隊066の新米スカウト"
  },
  {
    "id": "FPA-18",
    "name": "斥候-18",
    "score": 9,
    "LV": 4,
    "faction": "RDL",
    "swift": 5,
    "melee": 6,
    "projectile": 7,
    "firing": 4,
    "moving": 7,
    "tactic": 3,
    "trait": "",
    "traitDescription": "試験評価隊066の新米スカウト"
  },
  {
    "id": "FPA-06-2",
    "name": "キーホール-06",
    "score": 12,
    "LV": 4,
    "faction": "RDL",
    "swift": 2,
    "melee": 5,
    "projectile": 4,
    "firing": 6,
    "moving": 6,
    "tactic": 7,
    "trait": "隠れた",
    "traitDescription": "·搭乗しているメックが味方のオーラ範囲内にいる場合、低姿勢を獲得します。"
  },
  {
    "id": "FPA-63",
    "name": "斥候-63",
    "score": 9,
    "LV": 4,
    "faction": "RDL",
    "swift": 5,
    "melee": 6,
    "projectile": 7,
    "firing": 4,
    "moving": 7,
    "tactic": 3,
    "trait": "",
    "traitDescription": "試験評価隊066の新米スカウト"
  }
];

export const pdDrones: Drone[] = [
  {
    "id": "PRDR-101",
    "name": "MD-4A「リーパー」I型",
    "type": "large",
    "score": 90,
    "structure": 4,
    "armor": 5,
    "parray": 0,
    "dodge": 0,
    "electronic": 3,
    "move": 6,
    "stance": "defensive",
    "description": "",
    "isPD":true,"projectile": [
      "PDAM-001"
    ]
  },
  {
    "id": "PRDR-102",
    "name": "MD-4C「リーパー」III型",
    "type": "large",
    "score": 99,
    "structure": 4,
    "armor": 5,
    "parray": 0,
    "dodge": 0,
    "electronic": 3,
    "move": 6,
    "stance": "defensive",
    "description": "",
    "isPD":true,"projectile": [
      "PDAM-001"
    ]
  },
  {
    "id": "PRDR-103",
    "name": "MD-4D「リーパー」IV型",
    "type": "large",
    "score": 105,
    "structure": 5,
    "armor": 6,
    "parray": 0,
    "dodge": 0,
    "electronic": 3,
    "move": 6,
    "stance": "defensive",
    "description": "",
    "isPD":true
  },
  {
    "id": "PRDR-104",
    "name": "MD-4B「リーパー」II型",
    "type": "large",
    "score": 114,
    "structure": 5,
    "armor": 6,
    "parray": 0,
    "dodge": 0,
    "electronic": 3,
    "move": 6,
    "stance": "defensive",
    "description": "",
    "isPD":true
  },
  {
    "id": "PRDR-105",
    "name": "MD-4E「リーパー」工兵型",
    "type": "large",
    "score": 90,
    "structure": 4,
    "armor": 5,
    "parray": 0,
    "dodge": 0,
    "electronic": 3,
    "move": 6,
    "stance": "defensive",
    "description": "",
    "isPD":true,"projectile": [
      "PDAM-003","PDAM-004"
    ]
  },
  {
    "id": "PRDR-201",
    "name": "LD-5A 「ヴィジラント」オートキャノン型",
    "type": "medium",
    "score": 48,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 4,
    "electronic": 2,
    "move": 6,
    "stance": "mobility",
    "description": "",
    "isPD":true
  },
  {
    "id": "PRDR-202",
    "name": "LD-5M「ヴィジラント」機関銃型",
    "type": "medium",
    "score": 42,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 4,
    "electronic": 2,
    "move": 6,
    "stance": "mobility",
    "description": "",
    "isPD":true
  },
  {
    "id": "PRDR-203",
    "name": "LD-5B「ヴィジラント」爆撃型",
    "type": "medium",
    "score": 45,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 4,
    "electronic": 2,
    "move": 6,
    "stance": "mobility",
    "description": "",
    "isPD":true, "projectile": [
      "PDAM-005"
    ]
  },
  {
    "id": "PRDR-204",
    "name": "LD-5S「ヴィジラント」支援型",
    "type": "medium",
    "score": 48,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 4,
    "electronic": 2,
    "move": 6,
    "stance": "mobility",
    "description": "",
    "isPD":true,"projectile": [
      "PDAM-005","PDAM-006"
    ]
  }
];

export const pdLeftHand: Part[] = [
];

export const pdRightHand: Part[] = [
];
export const pdTorso: Part[] = [
];
export const pdChasis: Part[] = [
];
export const pdBackpack: Part[] = [
];

export const pdPilots: Pilot[] = [
];

export const allTacticCards: TacticCard[] = [
  {
    "id": "274",
    "name": "追加指令",
    "description": "",
    "score": 30
  },{
    "id": "275",
    "name": "戰場復㷌",
    "description": "",
    "score": 30
  },{
    "id": "276",
    "name": "一擊離脱",
    "description": "",
    "score": 30
  },{
    "id": "277",
    "name": "緊急修理",
    "description": "",
    "score": 30
  },{
    "id": "278",
    "name": "協調指揮",
    "description": "",
    "score": 30
  },{
    "id": "279",
    "name": "遠隔再起動",
    "description": "",
    "score": 30
  },
]