import { Part, Drone, Pilot, Projectile } from '../../src/types';

export const gofPilots: Pilot[] = [
  {
    "id": "ZPA-35",
    "name": "大厨",
    "score": 15,
    "LV": 4,
    "faction": "GOF",
    "swift": 3,
    "melee": 4,
    "projectile": 4,
    "firing": 6,
    "moving": 6,
    "tactic": 7,
    "trait": "CQC",
    "traitDescription": "· 执行近战动作时，可以消耗1枚指令标记，将{眼睛}视为{重击}"
  },
  {
    "id": "ZPA-36",
    "name": "紫苑",
    "score": 12,
    "LV": 4,
    "faction": "GOF",
    "swift": 6,
    "melee": 4,
    "projectile": 5,
    "firing": 3,
    "moving": 3,
    "tactic": 4,
    "trait": "调整",
    "traitDescription": "· 每回合1次，指令阶段可以消耗1枚指令标记，为1台友军机甲恢复1点链接值。"
  },
  {
    "id": "ZPA-37",
    "name": "猎狐犬",
    "score": 15,
    "LV": 4,
    "faction": "GOF",
    "swift": 3,
    "melee": 7,
    "projectile": 6,
    "firing": 2,
    "moving": 5,
    "tactic": 5,
    "trait": "寻踪",
    "traitDescription": "· 如果有2台以上的己方无人机对目标有视线，本机在射击时无视低特征。"
  },
  {
    "id": "ZPA-38",
    "name": "护林员",
    "score": 15,
    "LV": 4,
    "faction": "GOF",
    "swift": 5,
    "melee": 6,
    "projectile": 7,
    "firing": 4,
    "moving": 7,
    "tactic": 3,
    "trait": "湿件优势",
    "traitDescription": "· 执行电子对抗投骰时，可消耗1点链接值，将{眼睛}视为{闪电}。"
  },
  {
    "id": "ZPA-39",
    "name": "丧尸",
    "score": 18,
    "LV": 4,
    "faction": "GOF",
    "swift": 4,
    "melee": 3,
    "projectile": 2,
    "firing": 5,
    "moving": 4,
    "tactic": 7,
    "trait": "求生意志",
    "traitDescription": "· 本机部件少于4时，本机的专注重投不消耗链接值。"
  },
  {
    "id": "ZPA-40",
    "name": "伯劳",
    "score": 12,
    "LV": 4,
    "faction": "GOF",
    "swift": 5,
    "melee": 2,
    "projectile": 3,
    "firing": 8,
    "moving": 4,
    "tactic": 4,
    "trait": "欢愉",
    "traitDescription": "· [攻击姿态]以近战动作摧毁敌军部件时，恢复1点链接值。"
  },
  {
    "id": "ZPA-43",
    "name": "游骑兵1",
    "score": 4,
    "LV": 4,
    "faction": "GOF",
    "swift": 2,
    "melee": 5,
    "projectile": 4,
    "firing": 6,
    "moving": 6,
    "tactic": 8,
    "trait": "",
    "traitDescription": "525中队的实习游骑兵。"
  },
  {
    "id": "ZPA-44",
    "name": "游骑兵2",
    "score": 4,
    "LV": 4,
    "faction": "GOF",
    "swift": 2,
    "melee": 5,
    "projectile": 4,
    "firing": 6,
    "moving": 6,
    "tactic": 8,
    "trait": "",
    "traitDescription": "525中队的实习游骑兵。"
  },
  {
    "id": "ZPA-45",
    "name": "游骑兵3",
    "score": 4,
    "LV": 4,
    "faction": "GOF",
    "swift": 2,
    "melee": 5,
    "projectile": 4,
    "firing": 6,
    "moving": 6,
    "tactic": 8,
    "trait": "",
    "traitDescription": "525中队的实习游骑兵。"
  },
  {
    "id": "ZPA-46",
    "name": "掷弹兵1",
    "score": 4,
    "LV": 4,
    "faction": "GOF",
    "swift": 8,
    "melee": 4,
    "projectile": 5,
    "firing": 3,
    "moving": 3,
    "tactic": 2,
    "trait": "",
    "traitDescription": "525中队的实习掷弹兵。"
  },
  {
    "id": "ZPA-47",
    "name": "掷弹兵2",
    "score": 4,
    "LV": 4,
    "faction": "GOF",
    "swift": 8,
    "melee": 4,
    "projectile": 5,
    "firing": 3,
    "moving": 3,
    "tactic": 2,
    "trait": "",
    "traitDescription": "525中队的实习掷弹兵。"
  },
  {
    "id": "ZPA-48",
    "name": "掷弹兵3",
    "score": 4,
    "LV": 4,
    "faction": "GOF",
    "swift": 8,
    "melee": 4,
    "projectile": 5,
    "firing": 3,
    "moving": 3,
    "tactic": 2,
    "trait": "",
    "traitDescription": "525中队的实习掷弹兵。"
  },
  {
    "id": "ZPA-49",
    "name": "掷弹兵4",
    "score": 4,
    "LV": 4,
    "faction": "GOF",
    "swift": 8,
    "melee": 4,
    "projectile": 5,
    "firing": 3,
    "moving": 3,
    "tactic": 2,
    "trait": "",
    "traitDescription": "525中队的实习掷弹兵。"
  }
];

export const pdPilots: Pilot[] = [
  {
    "id": "战斗员A-101",
    "name": "战斗员A-101",
    "score": 10,
    "LV": 5,
    "faction": "PD",
    "swift": 8,
    "melee": 4,
    "projectile": 5,
    "firing": 3,
    "moving": 3,
    "tactic": 2,
    "trait": "",
    "traitDescription": "为了使用LUKAS系统进行远程接入，战斗员的作战义体均装备了LK系列植入体。"
  },
  {
    "id": "战斗员A-102",
    "name": "战斗员A-102",
    "score": 10,
    "LV": 5,
    "faction": "PD",
    "swift": 8,
    "melee": 4,
    "projectile": 5,
    "firing": 3,
    "moving": 3,
    "tactic": 2,
    "trait": "",
    "traitDescription": "搭载作战员和LUKAS的运输机通常作为空中支援，在战场上空盘旋，以获得最低的延迟。"
  },
  {
    "id": "战斗员A-103",
    "name": "战斗员A-103",
    "score": 10,
    "LV": 5,
    "faction": "PD",
    "swift": 8,
    "melee": 4,
    "projectile": 5,
    "firing": 3,
    "moving": 3,
    "tactic": 2,
    "trait": "",
    "traitDescription": "虽然“工作就是工作”，但执行中队通常不会在短时间内切换合作方。"
  }
];

export const rdlPilots: Pilot[] = [
  {
    "id": "FPA-01",
    "name": "薄雾-01",
    "score": 15,
    "LV": 4,
    "faction": "RDL",
    "swift": 7,
    "melee": 4,
    "projectile": 5,
    "firing": 3,
    "moving": 3,
    "tactic": 2,
    "trait": "变招",
    "traitDescription": "· 在战术时机，起手动作不限制时机类型。"
  },
  {
    "id": "FPA-02",
    "name": "长钉-02",
    "score": 15,
    "LV": 4,
    "faction": "RDL",
    "swift": 3,
    "melee": 7,
    "projectile": 6,
    "firing": 2,
    "moving": 5,
    "tactic": 5,
    "trait": "鹰眼",
    "traitDescription": "· 执行射击动作时获得穿甲1。"
  },
  {
    "id": "FPA-03",
    "name": "无霜-03",
    "score": 12,
    "LV": 4,
    "faction": "RDL",
    "swift": 6,
    "melee": 2,
    "projectile": 3,
    "firing": 7,
    "moving": 4,
    "tactic": 4,
    "trait": "坚毅",
    "traitDescription": "· 本机部件被摧毁时，不扣除链接值。"
  },
  {
    "id": "FPA-04",
    "name": "锤头鲨-04",
    "score": 10,
    "LV": 4,
    "faction": "RDL",
    "swift": 4,
    "melee": 3,
    "projectile": 2,
    "firing": 5,
    "moving": 2,
    "tactic": 6,
    "trait": "猛攻",
    "traitDescription": "· 【攻击姿态】近战动作{眼睛}视为{轻击}。"
  },
  {
    "id": "FPA-05",
    "name": "灰雁-05",
    "score": 15,
    "LV": 4,
    "faction": "RDL",
    "swift": 5,
    "melee": 6,
    "projectile": 9,
    "firing": 3,
    "moving": 8,
    "tactic": 4,
    "trait": "不竭",
    "traitDescription": "· 本机的下肢如果没有结构值，则视为拥有2点结构值。"
  },
  {
    "id": "FPA-06",
    "name": "锁眼-06",
    "score": 12,
    "LV": 4,
    "faction": "RDL",
    "swift": 2,
    "melee": 5,
    "projectile": 4,
    "firing": 6,
    "moving": 6,
    "tactic": 7,
    "trait": "功率加大",
    "traitDescription": "· 本机的光环、电子攻击与电子支援，+1范围。"
  },
  {
    "id": "FPA-09",
    "name": "突击兵-09",
    "score": 6,
    "LV": 4,
    "faction": "RDL",
    "swift": 6,
    "melee": 2,
    "projectile": 3,
    "firing": 7,
    "moving": 4,
    "tactic": 4,
    "trait": "",
    "traitDescription": "066测试中队的新晋突击兵。"
  },
  {
    "id": "FPA-10",
    "name": "突击兵-10",
    "score": 6,
    "LV": 4,
    "faction": "RDL",
    "swift": 6,
    "melee": 2,
    "projectile": 3,
    "firing": 7,
    "moving": 4,
    "tactic": 4,
    "trait": "",
    "traitDescription": "066测试中队的新晋突击兵。"
  },
  {
    "id": "FPA-11",
    "name": "突击兵-11",
    "score": 6,
    "LV": 4,
    "faction": "RDL",
    "swift": 6,
    "melee": 2,
    "projectile": 3,
    "firing": 7,
    "moving": 4,
    "tactic": 4,
    "trait": "",
    "traitDescription": "066测试中队的新晋突击兵。"
  },
  {
    "id": "FPA-12",
    "name": "突击兵-12",
    "score": 6,
    "LV": 4,
    "faction": "RDL",
    "swift": 6,
    "melee": 2,
    "projectile": 3,
    "firing": 7,
    "moving": 4,
    "tactic": 4,
    "trait": "",
    "traitDescription": "066测试中队的新晋突击兵。"
  },
  {
    "id": "FPA-13",
    "name": "突击兵-13",
    "score": 6,
    "LV": 4,
    "faction": "RDL",
    "swift": 6,
    "melee": 2,
    "projectile": 3,
    "firing": 7,
    "moving": 4,
    "tactic": 4,
    "trait": "",
    "traitDescription": "066测试中队的新晋突击兵。"
  },
  {
    "id": "FPA-14",
    "name": "侦察兵-14",
    "score": 9,
    "LV": 4,
    "faction": "RDL",
    "swift": 5,
    "melee": 6,
    "projectile": 7,
    "firing": 4,
    "moving": 7,
    "tactic": 3,
    "trait": "",
    "traitDescription": "066测试中队的新晋侦察兵。"
  },
  {
    "id": "FPA-15",
    "name": "侦察兵-15",
    "score": 9,
    "LV": 4,
    "faction": "RDL",
    "swift": 5,
    "melee": 6,
    "projectile": 7,
    "firing": 4,
    "moving": 7,
    "tactic": 3,
    "trait": "",
    "traitDescription": "066测试中队的新晋侦察兵。"
  },
  {
    "id": "FPA-16",
    "name": "侦察兵-16",
    "score": 9,
    "LV": 4,
    "faction": "RDL",
    "swift": 5,
    "melee": 6,
    "projectile": 7,
    "firing": 4,
    "moving": 7,
    "tactic": 3,
    "trait": "",
    "traitDescription": "066测试中队的新晋侦察兵。"
  },
  {
    "id": "FPA-17",
    "name": "侦察兵-17",
    "score": 9,
    "LV": 4,
    "faction": "RDL",
    "swift": 5,
    "melee": 6,
    "projectile": 7,
    "firing": 4,
    "moving": 7,
    "tactic": 3,
    "trait": "",
    "traitDescription": "066测试中队的新晋侦察兵。"
  },
  {
    "id": "FPA-18",
    "name": "侦察兵-18",
    "score": 9,
    "LV": 4,
    "faction": "RDL",
    "swift": 5,
    "melee": 6,
    "projectile": 7,
    "firing": 4,
    "moving": 7,
    "tactic": 3,
    "trait": "",
    "traitDescription": "066测试中队的新晋侦察兵。"
  },
  {
    "id": "FPA-06-2",
    "name": "锁眼-06\n藏木于林",
    "score": 12,
    "LV": 4,
    "faction": "RDL",
    "swift": 2,
    "melee": 5,
    "projectile": 4,
    "firing": 6,
    "moving": 6,
    "tactic": 7,
    "trait": "功率隐匿",
    "traitDescription": "· 本机处于友军光环范围内时获得低特征。"
  },
  {
    "id": "FPA-63",
    "name": "侦察兵-63",
    "score": 9,
    "LV": 4,
    "faction": "RDL",
    "swift": 5,
    "melee": 6,
    "projectile": 7,
    "firing": 4,
    "moving": 7,
    "tactic": 3,
    "trait": "",
    "traitDescription": "066测试中队的新晋侦察兵。"
  }
];

export const unPilots: Pilot[] = [
  {
    "id": "LPA-19",
    "name": "石英",
    "score": 24,
    "LV": 4,
    "faction": "UN",
    "swift": 2,
    "melee": 5,
    "projectile": 4,
    "firing": 4,
    "moving": 6,
    "tactic": 6,
    "trait": "沉著",
    "traitDescription": "· 每回合结束时恢复1点链接值。"
  },
  {
    "id": "LPA-20",
    "name": "铠甲",
    "score": 15,
    "LV": 4,
    "faction": "UN",
    "swift": 3,
    "melee": 3,
    "projectile": 2,
    "firing": 5,
    "moving": 2,
    "tactic": 6,
    "trait": "阻拦",
    "traitDescription": "· 敌方单位脱离与本机的近战锁定时，需要额外消耗1格移动力，或者支付1点链接值。"
  },
  {
    "id": "LPA-21",
    "name": "鬼火",
    "score": 18,
    "LV": 4,
    "faction": "UN",
    "swift": 3,
    "melee": 7,
    "projectile": 6,
    "firing": 1,
    "moving": 5,
    "tactic": 5,
    "trait": "匿踪",
    "traitDescription": "· 当本机开启光学迷彩或处于低特征中时，本机的移动路径可穿越其他单位。"
  },
  {
    "id": "LPA-22",
    "name": "余裕",
    "score": 21,
    "LV": 4,
    "faction": "UN",
    "swift": 7,
    "melee": 4,
    "projectile": 5,
    "firing": 3,
    "moving": 4,
    "tactic": 1,
    "trait": "挑衅",
    "traitDescription": "· 当本机电子对抗投骰成功时，可使对方机甲切换为攻击姿态。"
  },
  {
    "id": "LPA-23",
    "name": "玉髓",
    "score": 21,
    "LV": 4,
    "faction": "UN",
    "swift": 6,
    "melee": 2,
    "projectile": 3,
    "firing": 5,
    "moving": 4,
    "tactic": 4,
    "trait": "不屈",
    "traitDescription": "· 本机可以碾压大体型单位。"
  },
  {
    "id": "LPA-24",
    "name": "峡湾",
    "score": 21,
    "LV": 4,
    "faction": "UN",
    "swift": 5,
    "melee": 4,
    "projectile": 8,
    "firing": 4,
    "moving": 7,
    "tactic": 3,
    "trait": "追击",
    "traitDescription": "· 攻击有脆弱标记的目标时，{眼睛}视为{重击}。"
  },
  {
    "id": "LPA-27",
    "name": "步枪手1",
    "score": 9,
    "LV": 4,
    "faction": "UN",
    "swift": 3,
    "melee": 7,
    "projectile": 6,
    "firing": 2,
    "moving": 5,
    "tactic": 5,
    "trait": "",
    "traitDescription": "303中队的实习步枪手。"
  },
  {
    "id": "LPA-28",
    "name": "步枪手2",
    "score": 9,
    "LV": 4,
    "faction": "UN",
    "swift": 3,
    "melee": 7,
    "projectile": 6,
    "firing": 2,
    "moving": 5,
    "tactic": 5,
    "trait": "",
    "traitDescription": "303中队的实习步枪手。"
  },
  {
    "id": "LPA-29",
    "name": "步枪手3",
    "score": 9,
    "LV": 4,
    "faction": "UN",
    "swift": 3,
    "melee": 7,
    "projectile": 6,
    "firing": 2,
    "moving": 5,
    "tactic": 5,
    "trait": "",
    "traitDescription": "303中队的实习步枪手。"
  },
  {
    "id": "LPA-30",
    "name": "步枪手4",
    "score": 9,
    "LV": 4,
    "faction": "UN",
    "swift": 3,
    "melee": 7,
    "projectile": 6,
    "firing": 2,
    "moving": 5,
    "tactic": 5,
    "trait": "",
    "traitDescription": "303中队的实习步枪手。"
  },
  {
    "id": "LPA-31",
    "name": "冲锋手1",
    "score": 6,
    "LV": 4,
    "faction": "UN",
    "swift": 4,
    "melee": 3,
    "projectile": 2,
    "firing": 5,
    "moving": 2,
    "tactic": 6,
    "trait": "",
    "traitDescription": "303中队的实习冲锋手。"
  },
  {
    "id": "LPA-32",
    "name": "冲锋手2",
    "score": 6,
    "LV": 4,
    "faction": "UN",
    "swift": 4,
    "melee": 3,
    "projectile": 2,
    "firing": 5,
    "moving": 2,
    "tactic": 6,
    "trait": "",
    "traitDescription": "303中队的实习冲锋手。"
  },
  {
    "id": "LPA-33",
    "name": "冲锋手3",
    "score": 6,
    "LV": 4,
    "faction": "UN",
    "swift": 4,
    "melee": 3,
    "projectile": 2,
    "firing": 5,
    "moving": 2,
    "tactic": 6,
    "trait": "",
    "traitDescription": "303中队的实习冲锋手。"
  },
  {
    "id": "LPA-34",
    "name": "冲锋手4",
    "score": 6,
    "LV": 4,
    "faction": "UN",
    "swift": 4,
    "melee": 3,
    "projectile": 2,
    "firing": 5,
    "moving": 2,
    "tactic": 6,
    "trait": "",
    "traitDescription": "303中队的实习冲锋手。"
  }
];

export const gofDrones: Drone[] = [
  {
    "id": "ZHDR-201",
    "name": "N31 猎犬I “猎兔犬”",
    "type": "medium",
    "score": 40,
    "structure": 0,
    "armor": 6,
    "parray": 2,
    "dodge": 0,
    "electronic": 2,
    "move": 5,
    "stance": "offensive",
    "description": "·曲射：本动作不需要对落点或目标有视线。\r\n·齐射X：发射或布撒最多X枚抛射物，并消耗同等数量的弹药标记。"
  },
  {
    "id": "ZHDR-202",
    "name": "N31 猎犬II “看门狗”",
    "type": "medium",
    "score": 36,
    "structure": 0,
    "armor": 6,
    "parray": 2,
    "dodge": 0,
    "electronic": 2,
    "move": 5,
    "stance": "offensive",
    "description": ""
  },
  {
    "id": "ZHDR-203",
    "name": "N31 猎犬III “斗牛犬”",
    "type": "medium",
    "score": 36,
    "structure": 0,
    "armor": 6,
    "parray": 2,
    "dodge": 0,
    "electronic": 2,
    "move": 5,
    "stance": "offensive",
    "description": ""
  },
  {
    "id": "ZHDR-303",
    "name": "N503 “女武神”",
    "type": "medium",
    "score": 72,
    "structure": 4,
    "armor": 2,
    "parray": 0,
    "dodge": 0,
    "electronic": 3,
    "move": 5,
    "stance": "offensive",
    "description": "·全向射击：本动作没有射界限制。\r\n·近战射击：在近战锁定中仍可执行本动作。"
  },
  {
    "id": "ZHDR-304",
    "name": "N504 “鹰身女妖”",
    "type": "medium",
    "score": 72,
    "structure": 4,
    "armor": 2,
    "parray": 0,
    "dodge": 0,
    "electronic": 3,
    "move": 5,
    "stance": "offensive",
    "description": "·全向射击：本动作没有射界限制。\r\n·近战射击：在近战锁定中仍可执行本动作。"
  },
  {
    "id": "ZHDR-101",
    "name": "N11 先锋I “塔盾”",
    "type": "medium",
    "score": 36,
    "structure": 3,
    "armor": 5,
    "parray": 0,
    "dodge": 0,
    "electronic": 2,
    "move": 5,
    "stance": "defensive",
    "description": "·自动盾牌：相邻的己方单位在遭受射击时，如果攻击者与目标的连线穿过本单位，则攻击变为以本机为目标。"
  },
  {
    "id": "ZHDR-102",
    "name": "N12 先锋II “十字弓”",
    "type": "medium",
    "score": 24,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 2,
    "move": 5,
    "stance": "defensive",
    "description": "·全向射击：本动作没有射界限制。\r\n·近战射击：在近战锁定中仍可执行本动作。"
  },
  {
    "id": "ZHDR-103",
    "name": "N13 先锋III “阔剑”",
    "type": "medium",
    "score": 24,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 2,
    "move": 5,
    "stance": "defensive",
    "description": "·全向射击：本动作没有射界限制。\r\n·近战射击：在近战锁定中仍可执行本动作。"
  },
  {
    "id": "ZHDR-104",
    "name": "N14 先锋IV “标枪”",
    "type": "medium",
    "score": 24,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 2,
    "move": 5,
    "stance": "defensive",
    "description": "·曲射：本动作不需要对落点或目标有视线。"
  },
  {
    "id": "ZHDR-106",
    "name": "N113 神盾II “弩炮”",
    "type": "medium",
    "score": 72,
    "structure": 6,
    "armor": 3,
    "parray": 0,
    "dodge": 0,
    "electronic": 2,
    "move": 4,
    "stance": "offensive",
    "description": "·穿甲X：遭受本攻击时受击方减少X枚白骰。\r\n·近战射击：在近战锁定中仍可执行本动作。"
  },
  {
    "id": "ZHDR-107",
    "name": "N113 神盾III “冲角”",
    "type": "medium",
    "score": 60,
    "structure": 6,
    "armor": 3,
    "parray": 0,
    "dodge": 0,
    "electronic": 2,
    "move": 4,
    "stance": "offensive",
    "description": "·压制：被本动作宣布为目标的机甲会立刻切换为防御姿态（重启中单位不受此影响）。"
  },
  {
    "id": "ZHDR-301",
    "name": "N51 “护教者”",
    "type": "medium",
    "score": 60,
    "structure": 5,
    "armor": 2,
    "parray": 0,
    "dodge": 0,
    "electronic": 2,
    "move": 5,
    "stance": "defensive",
    "description": "·霰射：如果目标为机甲，溢出伤害结算至目标另1个随机部件。\r\n·击退X：本动作结束后，将目标沿攻击方向，强制移动X格。"
  },
  {
    "id": "ZHDR-302",
    "name": "N52 “狂热者”",
    "type": "medium",
    "score": 60,
    "structure": 5,
    "armor": 2,
    "parray": 1,
    "dodge": 0,
    "electronic": 2,
    "move": 5,
    "stance": "defensive",
    "description": ""
  },
  {
    "id": "ZHDR-204",
    "name": "N305 猎鹰I “迷雾鹰”",
    "type": "medium",
    "score": 36,
    "structure": 0,
    "armor": 2,
    "parray": 0,
    "dodge": 7,
    "electronic": 3,
    "move": 6,
    "stance": "mobility",
    "description": ""
  },
  {
    "id": "ZHDR-205",
    "name": "N306 猎鹰II “咆哮鹰”",
    "type": "medium",
    "score": 36,
    "structure": 0,
    "armor": 2,
    "parray": 0,
    "dodge": 7,
    "electronic": 3,
    "move": 6,
    "stance": "mobility",
    "description": ""
  },
  {
    "id": "ZHDR-206",
    "name": "N307 猎鹰III “巡逻鹰”",
    "type": "medium",
    "score": 36,
    "structure": 0,
    "armor": 2,
    "parray": 0,
    "dodge": 7,
    "electronic": 3,
    "move": 6,
    "stance": "mobility",
    "description": "· 静默：执行本动作时不会解除光学迷彩。"
  },
  {
    "id": "ZYDR-108",
    "name": "SU1 “护巢蜂”",
    "type": "medium",
    "score": 0,
    "structure": 0,
    "armor": 1,
    "parray": 0,
    "dodge": 2,
    "electronic": 1,
    "move": 5,
    "stance": "mobility",
    "description": ""
  }
];

export const pdDrones: Drone[] = [
  {
    "id": "PRDR-101",
    "name": "MD-4A \"收割者\"I型",
    "type": "medium",
    "score": 90,
    "structure": 4,
    "armor": 5,
    "parray": 0,
    "dodge": 0,
    "electronic": 3,
    "move": 6,
    "stance": "defensive",
    "description": "·曲射：本动作不需要对落点或目标有视线。\n·齐射X：发射或布撒最多X枚抛射物，并消耗同等数量的弹药标记。",
    "isPD":true
  },
  {
    "id": "PRDR-102",
    "name": "MD-4C \"收割者\"III型",
    "type": "medium",
    "score": 99,
    "structure": 4,
    "armor": 5,
    "parray": 0,
    "dodge": 0,
    "electronic": 3,
    "move": 6,
    "stance": "defensive",
    "description": "·曲射：本动作不需要对落点或目标有视线。\n·齐射X：发射或布撒最多X枚抛射物，并消耗同等数量的弹药标记。",
    "isPD":true
  },
  {
    "id": "PRDR-103",
    "name": "MD-4D \"收割者\"IV型",
    "type": "medium",
    "score": 105,
    "structure": 5,
    "armor": 6,
    "parray": 0,
    "dodge": 0,
    "electronic": 3,
    "move": 6,
    "stance": "defensive",
    "description": "",
    "isPD":true
  },
  {
    "id": "PRDR-104",
    "name": "MD-4B \"收割者\"II型",
    "type": "medium",
    "score": 114,
    "structure": 5,
    "armor": 6,
    "parray": 0,
    "dodge": 0,
    "electronic": 3,
    "move": 6,
    "stance": "defensive",
    "description": "",
    "isPD":true
  },
  {
    "id": "PRDR-105",
    "name": "MD-4E \"收割者\"工兵型",
    "type": "medium",
    "score": 90,
    "structure": 4,
    "armor": 5,
    "parray": 0,
    "dodge": 0,
    "electronic": 3,
    "move": 6,
    "stance": "defensive",
    "description": "·直射：本动作需要对落点或目标有视线。",
    "isPD":true
  },
  {
    "id": "PRDR-201",
    "name": "LD-5A \"警惕\"机炮型",
    "type": "medium",
    "score": 48,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 4,
    "electronic": 2,
    "move": 6,
    "stance": "mobility",
    "description": "·全向射击：本动作没有射界限制。\n·近战射击：在近战锁定中仍可执行本动作。\n·空中移动：本动作视为飞行。",
    "isPD":true
  },
  {
    "id": "PRDR-202",
    "name": "LD-5M \"警惕\"机枪型",
    "type": "medium",
    "score": 42,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 4,
    "electronic": 2,
    "move": 6,
    "stance": "mobility",
    "description": "·全向射击：本动作没有射界限制。\n·近战射击：在近战锁定中仍可执行本动作。\n·空中移动：本动作视为飞行。",
    "isPD":true
  },
  {
    "id": "PRDR-203",
    "name": "LD-5B \"警惕\"轰炸型",
    "type": "medium",
    "score": 45,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 4,
    "electronic": 2,
    "move": 6,
    "stance": "mobility",
    "description": "·曲射：本动作不需要对落点或目标有视线。\n·齐射X：发射或布撒最多X枚抛射物，并消耗同等数量的弹药标记。\n·空中移动：本动作视为飞行。",
    "isPD":true
  },
  {
    "id": "PRDR-204",
    "name": "LD-5S \"警惕\"支援型",
    "type": "medium",
    "score": 48,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 4,
    "electronic": 2,
    "move": 6,
    "stance": "mobility",
    "description": "·曲射：本动作不需要对落点或目标有视线。\n·齐射X：发射或布撒最多X枚抛射物，并消耗同等数量的弹药标记。\n·空中移动：本动作视为飞行。\n·直射：本动作需要对落点或目标有视线。",
    "isPD":true
  }
];

export const gofTorso: Part[] = [
  {
    "id": "ZYTR-101",
    "name": "P7\r\n“勇士”\r\n主战核心",
    "type": "torso",
    "score": 76,
    "structure": 3,
    "armor": 5,
    "parray": 0,
    "dodge": 0,
    "electronic": 3,
    "description": "·指令生成X：指令阶段开始时，本机自动生成X枚指令标记。\r\n· 指令协调X：本动作执行结束后，可以立即向X台己方无人机发送1枚指令标记。 "
  },
  {
    "id": "ZYTR-102",
    "name": "P7-A3\r\n“百夫长”\r\n节点核心",
    "type": "torso",
    "score": 79,
    "structure": 3,
    "armor": 5,
    "parray": 0,
    "dodge": 0,
    "electronic": 3,
    "description": "·指令生成X：指令阶段开始时，本机自动生成X枚指令标记。"
  },
  {
    "id": "ZYTR-201",
    "name": "P22\r\n“猎人”\r\n电战核心",
    "type": "torso",
    "score": 91,
    "structure": 4,
    "armor": 5,
    "parray": 0,
    "dodge": 0,
    "electronic": 4,
    "description": "·指令生成X：指令阶段开始时，本机自动生成X枚指令标记。"
  },
  {
    "id": "ZYTR-301",
    "name": "P28\r\n“龙骑兵”\r\n重甲核心",
    "type": "torso",
    "score": 97,
    "structure": 4,
    "armor": 5,
    "parray": 0,
    "dodge": 0,
    "electronic": 2,
    "description": "·指令生成X：指令阶段开始时，本机自动生成X枚指令标记。"
  },
  {
    "id": "ZYTR-302",
    "name": "P24\r\n“战车”\r\n重甲核心",
    "type": "torso",
    "score": 94,
    "structure": 4,
    "armor": 5,
    "parray": 0,
    "dodge": 0,
    "electronic": 2,
    "description": "·指令生成X：指令阶段开始时，本机自动生成X枚指令标记。"
  }
];

export const gofChasis: Part[] = [
  {
    "id": "ZHLT-101",
    "name": "PL1\r\n标准下肢",
    "type": "chasis",
    "score": 37,
    "structure": 5,
    "armor": 1,
    "parray": 0,
    "dodge": 3,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "ZHLT-201",
    "name": "PL29\r\n隐秘下肢",
    "type": "chasis",
    "score": 61,
    "structure": 5,
    "armor": 1,
    "parray": 0,
    "dodge": 4,
    "electronic": 0,
    "description": "·静默：不会解除光学迷彩。"
  },
  {
    "id": "ZHLT-301",
    "name": "PLK400\r\n“半人马”\r\n高速下肢",
    "type": "chasis",
    "score": 90,
    "structure": 3,
    "armor": 5,
    "parray": 0,
    "dodge": 3,
    "electronic": 0,
    "description": "`不可阻挡：本动作在禁足状态下也可以移动\r\n·异形X：执行本动作时，需要消耗X点链接值。\r\n·推动X：将目标沿本单位面朝方向，强制直线移动X格，然后本单位执行同样的移动。"
  },
  {
    "id": "281",
    "name": "PL35\r\n重甲下肢",
    "type": "chasis",
    "score": 64,
    "structure": 2,
    "armor": 6,
    "parray": 0,
    "dodge": 3,
    "electronic": 0,
    "description": "·推动X：将目标沿本单位面朝方向，强制直线移动X格，然后本单位执行同样的移动。"
  }
];

export const gofLeftHand: Part[] = [
  {
    "id": "ZHLA-101",
    "name": "SS12圆盾",
    "type": "leftHand",
    "score": 53,
    "structure": 5,
    "armor": 4,
    "parray": 2,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "ZHLA-102",
    "name": "双联“雨燕”发射器",
    "type": "leftHand",
    "score": 35,
    "structure": 4,
    "armor": 1,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "ZHLA-201",
    "name": "GSD7迫击炮",
    "type": "leftHand",
    "score": 29,
    "structure": 4,
    "armor": 1,
    "parray": 0,
    "dodge": 0,
    "electronic": 1,
    "description": ""
  },
  {
    "id": "ZHLA-202",
    "name": "M4格斗爪",
    "type": "leftHand",
    "score": 65,
    "structure": 5,
    "armor": 1,
    "parray": 3,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "ZHLA-301",
    "name": "SS30重盾",
    "type": "leftHand",
    "score": 75,
    "structure": 5,
    "armor": 6,
    "parray": 2,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },

  {
    "id": "ZHLA-302",
    "name": "MR870霰弹枪",
    "type": "leftHand",
    "score": 56,
    "structure": 5,
    "armor": 1,
    "parray": 1,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "ZHLA-303",
    "name": "辅助左臂",
    "type": "leftHand",
    "score": 29,
    "structure": 5,
    "armor": 1,
    "parray": 1,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "ZHLA-304",
    "name": "MH-K1热能重剑（左）",
    "type": "leftHand",
    "score": 47,
    "structure": 5,
    "armor": 1,
    "parray": 2,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  }
];

export const gofRightHand: Part[] = [
  {
    "id": "ZHRA-101",
    "name": "MR14磁轨步枪",
    "type": "rightHand",
    "score": 29,
    "structure": 4,
    "armor": 1,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "ZHRA-102",
    "name": "MR16磁轨步枪",
    "type": "rightHand",
    "score": 32,
    "structure": 4,
    "armor": 1,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "ZHRA-103",
    "name": "M115长矛",
    "type": "rightHand",
    "score": 29,
    "structure": 4,
    "armor": 1,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "ZHRA-201",
    "name": "MR21磁轨步枪",
    "type": "rightHand",
    "score": 68,
    "structure": 4,
    "armor": 1,
    "parray": 0,
    "dodge": 0,
    "electronic": 1,
    "description": ""
  },
  {
    "id": "ZHRA-202",
    "name": "MR24磁轨步枪",
    "type": "rightHand",
    "score": 68,
    "structure": 4,
    "armor": 1,
    "parray": 0,
    "dodge": 0,
    "electronic": 1,
    "description": ""
  },
  {
    "id": "ZHRA-301",
    "name": "M100长枪",
    "type": "rightHand",
    "score": 56,
    "structure": 5,
    "armor": 1,
    "parray": 1,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "ZHRA-303",
    "name": "M105长戟",
    "type": "rightHand",
    "score": 38,
    "structure": 4,
    "armor": 1,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "ZHRA-304",
    "name": "MH-K1热能重剑（右）",
    "type": "rightHand",
    "score": 47,
    "structure": 5,
    "armor": 1,
    "parray": 2,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  }
];

export const gofBackpack: Part[] = [
  {
    "id": "ZYBP-101",
    "name": "DLSP蜂群控制包",
    "type": "backpack",
    "score": 0,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 1,
    "electronic": 1,
    "description": ""
  },
  {
    "id": "ZYBP-102",
    "name": "集成数据链吊舱",
    "type": "backpack",
    "score": 0,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 1,
    "electronic": 1,
    "description": "· 指令协调X：在本机此次行动结束后，可以立即为X台己方无人机各提供1枚指令标记。"
  },
  {
    "id": "ZYBP-201",
    "name": "CSS20“披风”光学迷彩系统",
    "type": "backpack",
    "score": 0,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 1,
    "electronic": 0,
    "description": "·光学迷彩：将本机替换为光学迷彩模型，并移除所有高亮目标/低特征标记。\r\n· 隐秘X：光学迷彩解除时，本机在X格范围内现身。"
  },
  {
    "id": "ZYBP-202",
    "name": "ECP9“鹰哨”无人机指挥系统",
    "type": "backpack",
    "score": 0,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 1,
    "electronic": 1,
    "description": ""
  },
  {
    "id": "ZYBP-301",
    "name": "MCP7“回旋镖”携带包",
    "type": "backpack",
    "score": 0,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 1,
    "electronic": 0,
    "description": "·曲射：本动作不需要对落点或目标有视线。"
  },
  {
    "id": "ZYBP-302",
    "name": "“光环”近战协作系统",
    "type": "backpack",
    "score": 0,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 1,
    "electronic": 0,
    "description": ""
  }
];

export const pdTorso: Part[] = [
  {
    "id": "PDTR-101",
    "name": "H2-A“危机”I型",
    "type": "torso",
    "score": 69,
    "structure": 3,
    "armor": 5,
    "parray": 0,
    "dodge": 0,
    "electronic": 2,
    "description": ""
  },
  {
    "id": "PDTR-102",
    "name": "H2-B“危机”II型",
    "type": "torso",
    "score": 72,
    "structure": 3,
    "armor": 5,
    "parray": 0,
    "dodge": 0,
    "electronic": 2,
    "description": ""
  }
];

export const pdChasis: Part[] = [
  {
    "id": "PDLT-101",
    "name": "HL2\n“危机”下肢",
    "type": "chasis",
    "score": 24,
    "structure": 0,
    "armor": 5,
    "parray": 0,
    "dodge": 3,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "PDLT-102",
    "name": "HL2-M\n“危机”下肢M",
    "type": "chasis",
    "score": 32,
    "structure": 2,
    "armor": 5,
    "parray": 0,
    "dodge": 3,
    "electronic": 0,
    "description": ""
  }
];

export const pdLeftHand: Part[] = [
  {
    "id": "PDLA-101",
    "name": "Ls197R机炮（左）",
    "type": "leftHand",
    "score": 48,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "PDLA-102",
    "name": "Ot41激光压制系统+Sd3盾牌",
    "type": "leftHand",
    "score": 66,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  }
];

export const pdRightHand: Part[] = [
  {
    "id": "PDRA-101",
    "name": "Ls197R机炮（右）",
    "type": "rightHand",
    "score": 48,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "PDRA-102",
    "name": "Ot50-ADS+Sd3盾牌",
    "type": "rightHand",
    "score": 66,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  }
];

export const pdBackpack: Part[] = [
  {
    "id": "PDBP-101",
    "name": "四联装“飞鱼”发射器",
    "type": "backpack",
    "score": 56,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": "·曲射：本动作不需要对落点或目标有视线。\n·齐射X：发射或布撒最多X枚抛射物，并消耗同等数量的弹药标记。"
  },
  {
    "id": "PDBP-102",
    "name": "Ls297双联机炮",
    "type": "backpack",
    "score": 48,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": "·压制：被本动作宣布为目标的机甲会立刻切换为防御姿态（处于宕机姿态的单位不受此影响）。"
  }
];




export const rdlTorso: Part[] = [
  {
    "id": "012",
    "name": "RT-06  泥沼  主战核心",
    "score": 15,
    "structure": 2,
    "armor": 6,
    "parray": 0,
    "dodge": 0,
    "electronic": 2,
    "type": "torso",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "014",
    "name": "RT-07T  沙丘  战术核心",
    "score": 62,
    "structure": 4,
    "armor": 5,
    "parray": 0,
    "dodge": 0,
    "electronic": 3,
    "type": "torso",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "015",
    "name": "RT-08  雷暴  炮战核心",
    "score": 62,
    "structure": 2,
    "armor": 7,
    "parray": 0,
    "dodge": 0,
    "electronic": 3,
    "type": "torso",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "016",
    "name": "RT-09A  火山  重甲核心",
    "score": 66,
    "structure": 4,
    "armor": 6,
    "parray": 0,
    "dodge": 0,
    "electronic": 3,
    "type": "torso",
    "description": "",
    "imgSrc": "",
    "tags": [],    
    "projectile":["268"]
  },
  {
    "id": "017",
    "name": "RT-15B  熔岩  突击核心",
    "score": 59,
    "structure": 4,
    "armor": 5,
    "parray": 0,
    "dodge": 1,
    "electronic": 3,
    "type": "torso",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "projectile":["268"]
  },
  {
    "id": "019",
    "name": "RT-15C  冰川  突击核心",
    "score": 56,
    "structure": 4,
    "armor": 5,
    "parray": 0,
    "dodge": 1,
    "electronic": 2,
    "type": "torso",
    "description": "",
    "imgSrc": "",
    "tags": [],
        "projectile":["268"]
  },
  {
    "id": "018",
    "name": "RT-15/EC  极光  电战核心",
    "score": 60,
    "structure": 4,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 3,
    "type": "torso",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "246",
    "name": "RT-09M  火山M  重甲核心",
    "score": 66,
    "structure": 4,
    "armor": 6,
    "parray": 0,
    "dodge": 0,
    "electronic": 3,
    "type": "torso",
    "description": "",
    "imgSrc": "",
    "tags": [],
        "projectile":["268"]
  },
  {
    "id": "280",
    "name": "RT-09M II  火山M II  重甲核心",
    "score": 66,
    "structure": 4,
    "armor": 6,
    "parray": 0,
    "dodge": 0,
    "electronic": 3,
    "type": "torso",
    "description": "",
    "imgSrc": "",
    "tags": [],
        "projectile":["268"]
  },
  {
    "id": "503",
    "name": "RT-16B  雪崩  突击核心",
    "score": 60,
    "structure": 4,
    "armor": 5,
    "parray": 0,
    "dodge": 1,
    "electronic": 3,
    "type": "torso",
    "description": "",
    "imgSrc": "",
    "tags": [],
        "projectile":["268"]
  },
  {
    "id": "504",
    "name": "RT-15/S  光轮  支援核心",
    "score": 60,
    "structure": 4,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 3,
    "type": "torso",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "505",
    "name": "RT-06E  泥沼E  主战核心",
    "score": 21,
    "structure": 2,
    "armor": 6,
    "parray": 0,
    "dodge": 0,
    "electronic": 3,
    "type": "torso",
    "description": "",
    "imgSrc": "",
    "tags": []
  }
];

export const rdlChasis: Part[] = [
  {
    "id": "020",
    "name": "RL-06  标准下肢",
    "score": 18,
    "structure": 0,
    "armor": 5,
    "parray": 0,
    "dodge": 3,
    "electronic": 0,
    "type": "chasis",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "021",
    "name": "RL-08  重甲下肢",
    "score": 30,
    "structure": 1,
    "armor": 6,
    "parray": 0,
    "dodge": 3,
    "electronic": 0,
    "type": "chasis",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "022",
    "name": "RL-03D  快马高速下肢",
    "score": 42,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 4,
    "electronic": 0,
    "type": "chasis",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "249",
    "name": "RL-08M  重甲下肢",
    "score": 30,
    "structure": 1,
    "armor": 6,
    "parray": 0,
    "dodge": 3,
    "electronic": 0,
    "type": "chasis",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "281",
    "name": "RL-08M II 重甲下肢",
    "score": 45,
    "structure": 2,
    "armor": 6,
    "parray": 0,
    "dodge": 2,
    "electronic": 0,
    "type": "chasis",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "506",
    "name": "RL-06M  标准下肢",
    "score": 18,
    "structure": 0,
    "armor": 5,
    "parray": 0,
    "dodge": 3,
    "electronic": 0,
    "type": "chasis",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "507",
    "name": "RL-06MS  辅助下肢",
    "score": 24,
    "structure": 0,
    "armor": 5,
    "parray": 0,
    "dodge": 3,
    "electronic": 0,
    "type": "chasis",
    "description": "空手",
    "imgSrc": "",
    "tags": []
  }
];

export const rdlLeftHand: Part[] = [
  {
    "id": "023",
    "name": "55型轻盾 + CC-6格斗刀",
    "score": 54,
    "structure": 0,
    "armor": 5,
    "parray": 2,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "throwIndex":"024",
  },
  {
    "id": "024",
    "name": "55型轻盾 + CC-6格斗刀（弃置）",
    "score": 0,
    "structure": 0,
    "armor": 5,
    "parray": 2,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "029",
    "name": "ML-32双联发射器 + CC-3格斗刀",
    "score": 33,
    "structure": 0,
    "armor": 4,
    "parray": 1,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "projectile":["071"]
  },
  {
    "id": "032",
    "name": "R-20肩置磁轨炮（左）",
    "score": 51,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "034",
    "name": "77型重型盾牌",
    "score": 50,
    "structure": 0,
    "armor": 8,
    "parray": 1,
    "dodge": -2,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "throwIndex":"035",
  },
  {
    "id": "035",
    "name": "77型重型盾牌（弃置）",
    "score": 0,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "040",
    "name": "SPHX-3重武器支持手",
    "score": 42,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "041",
    "name": "L-320肩部机枪 + CC-6格斗刀",
    "score": 51,
    "structure": 0,
    "armor": 5,
    "parray": 2,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "throwIndex":"042",
  },
  {
    "id": "042",
    "name": "L-320肩部机枪 + CC-6格斗刀（弃置）",
    "score": 0,
    "structure": 0,
    "armor": 5,
    "parray": 2,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "045",
    "name": "79型战斗盾牌",
    "score": 56,
    "structure": 0,
    "armor": 6,
    "parray": 2,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "050",
    "name": "FCC-12 大手 格斗系统",
    "score": 69,
    "structure": 0,
    "armor": 4,
    "parray": 3,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "053",
    "name": "55型轻盾 + PC-9霰弹枪（左）",
    "score": 48,
    "structure": 0,
    "armor": 5,
    "parray": 2,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "throwIndex":"054",
  },
  {
    "id": "054",
    "name": "55型轻盾 + PC-9霰弹枪（左）（弃置）",
    "score": 0,
    "structure": 0,
    "armor": 5,
    "parray": 2,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "056",
    "name": "G/AC-6火箭筒",
    "score": 36,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "throwIndex":"057",
    "projectile":["267"]
  },
  {
    "id": "057",
    "name": "G/AC-6火箭筒（弃置）",
    "score": 0,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "062",
    "name": "62型臂盾 + CC-20单手剑（左）",
    "score": 63,
    "structure": 0,
    "armor": 5,
    "parray": 3,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "064",
    "name": "55型轻盾 + MES信标发射器",
    "score": 45,
    "structure": 0,
    "armor": 5,
    "parray": 2,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "throwIndex":"065",
    "projectile":["072"]
  },
  {
    "id": "065",
    "name": "55型轻盾+  MES信标发射器  （弃置）",
    "score": 0,
    "structure": 0,
    "armor": 5,
    "parray": 2,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "252",
    "name": "77型重盾（早期型）",
    "score": 50,
    "structure": 0,
    "armor": 8,
    "parray": 1,
    "dodge": -2,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "throwIndex":"253",
  },
  {
    "id": "253",
    "name": "77型重盾早期型（弃置）",
    "score": 0,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "282",
    "name": "L-330肩部机枪 + 77B型重盾",
    "score": 56,
    "structure": 0,
    "armor": 9,
    "parray": 1,
    "dodge": -3,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "throwIndex":"283",
  },
  {
    "id": "283",
    "name": "L-330肩部机枪 + 77B型重盾（弃置）",
    "score": 0,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "510",
    "name": "55型轻盾 + PC-9K霰弹枪（左）",
    "score": 63,
    "structure": 0,
    "armor": 5,
    "parray": 2,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "throwIndex":"511",
  },
  {
    "id": "511",
    "name": "55型轻盾 + PC-9K霰弹枪（左）（弃置）",
    "score": 0,
    "structure": 0,
    "armor": 5,
    "parray": 2,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "514",
    "name": "AH-21手枪 + CC-50打桩机 （左）",
    "score": 63,
    "structure": 0,
    "armor": 4,
    "parray": 1,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "throwIndex":"515",
  },
  {
    "id": "515",
    "name": "AH-21手枪 + CC-50打桩机 （左）（弃置）",
    "score": 0,
    "structure": 0,
    "armor": 4,
    "parray": 1,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "520",
    "name": "55型轻盾",
    "score": 30,
    "structure": 0,
    "armor": 5,
    "parray": 2,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  }
];

export const rdlRightHand: Part[] = [
  {
    "id": "025",
    "name": "AC-32自动步枪",
    "score": 24,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "throwIndex":"026",
  },
  {
    "id": "026",
    "name": "AC-32自动步枪（弃置）",
    "score": 0,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "030",
    "name": "AC-150重型机枪",
    "score": 42,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": -2,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "throwIndex":"031",
  },
  {
    "id": "031",
    "name": "AC-150重型机枪（弃置）",
    "score": 0,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "033",
    "name": "R-20肩置磁轨炮（右）",
    "score": 51,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "036",
    "name": "CC-4战斗刀（右）",
    "score": 39,
    "structure": 0,
    "armor": 4,
    "parray": 1,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "038",
    "name": "ACX-350积雨云原型重机枪",
    "score": 48,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": -2,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "throwIndex":"039",
  },
  {
    "id": "039",
    "name": "ACX-350积雨云原型重机枪（弃置）",
    "score": 0,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "043",
    "name": "R-35重型磁轨炮",
    "score": 54,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": -2,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "throwIndex":"044",
  },
  {
    "id": "044",
    "name": "R-35重型磁轨炮（弃置）",
    "score": 0,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "046",
    "name": "55型轻盾 + PC-9霰弹枪（右）",
    "score": 48,
    "structure": 0,
    "armor": 5,
    "parray": 2,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "throwIndex":"047",
  },
  {
    "id": "047",
    "name": "55型轻盾 + PC-9霰弹枪（右）（弃置）",
    "score": 0,
    "structure": 0,
    "armor": 5,
    "parray": 2,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "048",
    "name": "55型轻盾 + PC-9霰弹枪 + 烟幕弹（右）",
    "score": 57,
    "structure": 0,
    "armor": 5,
    "parray": 2,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "throwIndex":"049",
        "projectile":["268"]
  },
  {
    "id": "049",
    "name": "55型轻盾 + PC-9霰弹枪 + 烟幕弹（右）（弃置）",
    "score": 0,
    "structure": 0,
    "armor": 5,
    "parray": 2,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": [],
        "projectile":["268"]
  },
  {
    "id": "051",
    "name": "L-320肩部机枪 + CC-90重格斗刀",
    "score": 63,
    "structure": 0,
    "armor": 4,
    "parray": 1,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "throwIndex":"052",
  },
  {
    "id": "052",
    "name": "L-320肩部机枪 + CC-90重格斗刀 （弃置）",
    "score": 0,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "055",
    "name": "CC-100力士链锤",
    "score": 48,
    "structure": 0,
    "armor": 4,
    "parray": 1,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "058",
    "name": "AC-39战术步枪",
    "score": 45,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "throwIndex":"059",
  },
  {
    "id": "059",
    "name": "AC-39战术步枪（弃置）",
    "score": 0,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "063",
    "name": "63型臂炮 + CC-20单手剑（右）",
    "score": 66,
    "structure": 0,
    "armor": 4,
    "parray": 2,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "068",
    "name": "AC-161冲锋枪",
    "score": 45,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "throwIndex":"069",
  },
  {
    "id": "069",
    "name": "AC-161冲锋枪（弃置）",
    "score": 0,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "254",
    "name": "L-320肩部机枪 + CC-90重型格斗刀早期型",
    "score": 63,
    "structure": 0,
    "armor": 4,
    "parray": 1,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "throwIndex":"255",
  },
  {
    "id": "255",
    "name": "L-320肩部机枪 + CC-90重型格斗刀早期型（弃置）",
    "score": 0,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "284",
    "name": "L-330肩部机枪 + CC-85岩锯",
    "score": 57,
    "structure": 0,
    "armor": 4,
    "parray": 1,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "throwIndex":"285",
  },
  {
    "id": "285",
    "name": "L-330肩部机枪 + CC-85岩锯（弃置）",
    "score": 0,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "508",
    "name": "55型轻盾 + PC-9K霰弹枪（右）",
    "score": 63,
    "structure": 0,
    "armor": 5,
    "parray": 2,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "throwIndex":"509",
  },
  {
    "id": "509",
    "name": "55型轻盾 + PC-9K霰弹枪（右）（弃置）",
    "score": 0,
    "structure": 0,
    "armor": 5,
    "parray": 2,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "512",
    "name": "AH-21手枪 + CC-50打桩机 （右）",
    "score": 63,
    "structure": 0,
    "armor": 4,
    "parray": 1,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "throwIndex":"513",
  },
  {
    "id": "513",
    "name": "AH-21手枪 + CC-50打桩机 （右）（弃置）",
    "score": 0,
    "structure": 0,
    "armor": 4,
    "parray": 1,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "516",
    "name": "AC-35狙击步枪",
    "score": 51,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "throwIndex":"517",
  },
  {
    "id": "517",
    "name": "AC-35狙击步枪（弃置）",
    "score": 0,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "518",
    "name": "AC-32C自动步枪",
    "score": 36,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "throwIndex":"519",
  },
  {
    "id": "519",
    "name": "AC-32C自动步枪（弃置）",
    "score": 0,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  }
];

export const rdlBackpack: Part[] = [
  {
    "id": "001",
    "name": "SH-15战场修复系统",
    "score": 30,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 2,
    "electronic": 0,
    "type": "backpack",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "002",
    "name": "ECS-2外置冷却器",
    "score": 33,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 1,
    "electronic": 0,
    "type": "backpack",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "003",
    "name": "AMS-190主动防御系统",
    "score": 27,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 0,
    "electronic": 1,
    "type": "backpack",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "004",
    "name": "ML-34四联导弹包",
    "score": 39,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 1,
    "electronic": 0,
    "type": "backpack",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "projectile":["071"]
  },
  {
    "id": "005",
    "name": "LGP-80长程火炮",
    "score": 33,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": -2,
    "electronic": 0,
    "type": "backpack",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "006",
    "name": "GLP-15布雷包",
    "score": 30,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "backpack",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "projectile":["074"]
  },
  {
    "id": "007",
    "name": "MUD-1泥浆电子战背包",
    "score": 33,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 1,
    "electronic": 1,
    "type": "backpack",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "008",
    "name": "CP-3信标携带包",
    "score": 36,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "backpack",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "projectile":["075","076","077"]
  },
  {
    "id": "009",
    "name": "MUE/N-20回响支援背包",
    "score": 30,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "backpack",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "010",
    "name": "TB-600跳跃背包",
    "score": 48,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 2,
    "electronic": 0,
    "type": "backpack",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "011",
    "name": "ML-92双联导弹包",
    "score": 20,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "backpack",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "projectile":["073"]
  },
  {
    "id": "264",
    "name": "AMS-192主动防御系统",
    "score": 27,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 0,
    "electronic": 1,
    "type": "backpack",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "286",
    "name": "AMS-193主动防御系统",
    "score": 27,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 0,
    "electronic": 1,
    "type": "backpack",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "500",
    "name": "HD-2数据携带包",
    "score": 24,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 0,
    "electronic": 1,
    "type": "backpack",
    "description": "任务",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "501",
    "name": "ML-94四联导弹包",
    "score": 48,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "backpack",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "502",
    "name": "CP-4无人机携带包",
    "score": 36,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "backpack",
    "description": "",
    "imgSrc": "",
    "tags": []
  }
];

export const rdlDrones: Drone[] = [
  {
    "id": "078",
    "name": "DTG-30M 鬣狗机枪型",
    "score": 42,
    "structure": 2,
    "armor": 5,
    "parray": 0,
    "dodge": 0,
    "electronic": 2,
    "type": "small",
    "move": 0,
    "stance": "offensive",
    "description": ""
  },
  {
    "id": "079",
    "name": "DTG-30S 鬣狗导弹型",
    "score": 33,
    "structure": 2,
    "armor": 5,
    "parray": 0,
    "dodge": 0,
    "electronic": 2,
    "type": "small",
    "move": 0,
    "stance": "offensive",
    "description": "",
    "projectile":["071"]
  },
  {
    "id": "080",
    "name": "DTG-30R 鬣狗雷达型",
    "score": 27,
    "structure": 2,
    "armor": 5,
    "parray": 0,
    "dodge": 0,
    "electronic": 2,
    "type": "small",
    "move": 0,
    "stance": "offensive",
    "description": ""
  },
  {
    "id": "522",
    "name": "MD-1 蜻蜓微型侦察机",
    "score": 0,
    "structure": 0,
    "armor": 2,
    "parray": 0,
    "dodge": 2,
    "electronic": 3,
    "type": "small",
    "move": 0,
    "stance": "offensive",
    "description": ""
  }
];

export const unTorso: Part[] = [
  {
    "id": "091",
    "name": "TM31C 灰狼 主战核心",
    "score": 45,
    "structure": 4,
    "armor": 4,
    "parray": 0,
    "dodge": 1,
    "electronic": 3,
    "type": "torso",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "projectile":["155"]
  },
  {
    "id": "092",
    "name": "TM31R 薮猫 主战核心",
    "score": 54,
    "structure": 4,
    "armor": 4,
    "parray": 0,
    "dodge": 1,
    "electronic": 4,
    "type": "torso",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "094",
    "name": "TM39 蝮蛇 低征核心",
    "score": 63,
    "structure": 3,
    "armor": 3,
    "parray": 0,
    "dodge": 1,
    "electronic": 5,
    "type": "torso",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "096",
    "name": "TM641 章鱼 隐秘核心",
    "score": 81,
    "structure": 3,
    "armor": 3,
    "parray": 0,
    "dodge": 1,
    "electronic": 5,
    "type": "torso",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "097",
    "name": "TM35N 短吻鳄 电战核心",
    "score": 72,
    "structure": 4,
    "armor": 5,
    "parray": 0,
    "dodge": 1,
    "electronic": 4,
    "type": "torso",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "098",
    "name": "TM35B 野牛 突击核心",
    "score": 72,
    "structure": 4,
    "armor": 5,
    "parray": 0,
    "dodge": 1,
    "electronic": 4,
    "type": "torso",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "247",
    "name": "TM641O 章鱼 隐秘核心试作型",
    "score": 81,
    "structure": 3,
    "armor": 3,
    "parray": 0,
    "dodge": 1,
    "electronic": 5,
    "type": "torso",
    "description": "",
    "imgSrc": "",
    "tags": []
  }
];

export const unChasis: Part[] = [
  {
    "id": "099",
    "name": "LM231 标准下肢",
    "score": 27,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 4,
    "electronic": 0,
    "type": "chasis",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "100",
    "name": "LM210S 隐秘下肢",
    "score": 39,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 4,
    "electronic": 0,
    "type": "chasis",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "101",
    "name": "LM213B 格斗下肢",
    "score": 57,
    "structure": 1,
    "armor": 4,
    "parray": 0,
    "dodge": 4,
    "electronic": 0,
    "type": "chasis",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "250",
    "name": "LM210SO 隐秘下肢试作型",
    "score": 39,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 4,
    "electronic": 0,
    "type": "chasis",
    "description": "",
    "imgSrc": "",
    "tags": []
  }
];

export const unLeftHand: Part[] = [
  {
    "id": "103",
    "name": "S9流星盾 + M5刺桩",
    "score": 57,
    "structure": 0,
    "armor": 4,
    "parray": 2,
    "dodge": 1,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "107",
    "name": "S100大盾 + 手雷荚舱",
    "score": 66,
    "structure": 0,
    "armor": 5,
    "parray": 2,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "throwIndex":"108",
    "projectile":["154"]
  },
  {
    "id": "108",
    "name": "S100大盾 + 手雷荚舱（抛弃卡）",
    "score": 0,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "projectile":["154"]
  },
  {
    "id": "111",
    "name": "RH21手枪 + M3振剑（左）",
    "score": 45,
    "structure": 0,
    "armor": 3,
    "parray": 1,
    "dodge": 1,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "throwIndex":"112",
  },
  {
    "id": "112",
    "name": "RH21手枪·M3振剑（左）（抛弃卡）",
    "score": 0,
    "structure": 0,
    "armor": 3,
    "parray": 1,
    "dodge": 1,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "117",
    "name": "MDXS精灵系统 + R6冲锋枪（左）",
    "score": 45,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 2,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "throwIndex":"118",
  },
  {
    "id": "118",
    "name": "MDXS精灵系统 + R6冲锋枪（左）（抛弃卡）",
    "score": 0,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 2,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "121",
    "name": "MSH1稳定辅助臂（左）",
    "score": 24,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "126",
    "name": "K9钉刺枪 + M14BO胁差",
    "score": 42,
    "structure": 0,
    "armor": 3,
    "parray": 1,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "129",
    "name": "RKG70导弹巢",
    "score": 42,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "throwIndex":"130",
    "projectile":["157"]
  },
  {
    "id": "130",
    "name": "RKG70导弹巢（抛弃卡）",
    "score": 0,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "131",
    "name": "M3S振剑（左）",
    "score": 42,
    "structure": 0,
    "armor": 3,
    "parray": 1,
    "dodge": 1,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "135",
    "name": "M4振剑 + 手雷荚舱（左）",
    "score": 54,
    "structure": 0,
    "armor": 3,
    "parray": 1,
    "dodge": 1,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "projectile":["154"]
  },
  {
    "id": "139",
    "name": "MX82多功能鞭索",
    "score": 48,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 1,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "142",
    "name": "S100大盾",
    "score": 48,
    "structure": 0,
    "armor": 5,
    "parray": 2,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "throwIndex":"143",
  },
  {
    "id": "143",
    "name": "S100大盾（抛弃卡）",
    "score": 0,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "144",
    "name": "K7钉刺枪 + S10中盾",
    "score": 54,
    "structure": 0,
    "armor": 5,
    "parray": 2,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "146",
    "name": "G6霰射炮 + 手雷荚舱",
    "score": 75,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 1,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "throwIndex":"147",
    "projectile":["154"]
  },
  {
    "id": "147",
    "name": "G6霰射炮 + 手雷荚舱（抛弃卡）",
    "score": 0,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 1,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "projectile":["154"]
  },
  {
    "id": "150",
    "name": "RHX23暴雨突击手枪（左）",
    "score": 57,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 2,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "throwIndex":"151",
  },
  {
    "id": "151",
    "name": "RHX23暴雨突击手枪（左）（抛弃卡）",
    "score": 0,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 2,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "256",
    "name": "K9钉刺枪 + M14BO胁差试作型（左）",
    "score": 42,
    "structure": 0,
    "armor": 3,
    "parray": 1,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  }
];

export const unRightHand: Part[] = [
  ,
  {
    "id": "152",
    "name": "RHX23暴雨突击手枪（右）",
    "score": 57,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 2,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "throwIndex":"153",
  },
  {
    "id": "153",
    "name": "RHX23暴雨突击手枪（右）（抛弃卡）",
    "score": 0,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 2,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "104",
    "name": "R7自动步枪",
    "score": 42,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "throwIndex":"105",
  },
  {
    "id": "105",
    "name": "R7自动步枪（抛弃卡）",
    "score": 0,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "106",
    "name": "R33狙击步枪",
    "score": 39,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "109",
    "name": "R6冲锋枪",
    "score": 54,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 1,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "throwIndex":"110",
  },
  {
    "id": "110",
    "name": "R6冲锋枪（抛弃卡）",
    "score": 0,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 1,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "113",
    "name": "RH21手枪 + M3振剑（右）",
    "score": 45,
    "structure": 0,
    "armor": 3,
    "parray": 1,
    "dodge": 1,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "throwIndex":"114",
  },
  {
    "id": "114",
    "name": "RH21手枪·M3振剑（右）（抛弃卡）",
    "score": 0,
    "structure": 0,
    "armor": 3,
    "parray": 1,
    "dodge": 1,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "115",
    "name": "S100大盾 + R6SS肩炮",
    "score": 63,
    "structure": 0,
    "armor": 5,
    "parray": 2,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "throwIndex":"116",
  },
  {
    "id": "116",
    "name": "S100大盾 + R6SS肩炮（抛弃卡）",
    "score": 0,
    "structure": 0,
    "armor": 4,
    "parray": 2,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "119",
    "name": "MDXS精灵系统 + R6冲锋枪（右）",
    "score": 45,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 2,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "throwIndex":"120",
  },
  {
    "id": "120",
    "name": "MDXS精灵系统 + R6冲锋枪（右）（抛弃卡）",
    "score": 0,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 2,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "122",
    "name": "IGX920重型离子炮",
    "score": 60,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": -2,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "124",
    "name": "R6SD冲锋枪",
    "score": 60,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 1,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "throwIndex":"125",
  },
  {
    "id": "125",
    "name": "R6SD冲锋枪（抛弃卡）",
    "score": 0,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 1,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "127",
    "name": "R9B战术步枪",
    "score": 48,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "throwIndex":"128",
  },
  {
    "id": "128",
    "name": "R9B战术步枪（抛弃卡）",
    "score": 0,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "133",
    "name": "M3S振剑（右）",
    "score": 42,
    "structure": 0,
    "armor": 3,
    "parray": 1,
    "dodge": 1,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "137",
    "name": "M4振剑 + 手雷荚舱（右）",
    "score": 54,
    "structure": 0,
    "armor": 3,
    "parray": 1,
    "dodge": 1,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "projectile":["154"]
  },
  {
    "id": "140",
    "name": "IGX350离子霰弹枪",
    "score": 45,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "throwIndex":"141",
  },
  {
    "id": "141",
    "name": "IGX350离子霰弹枪（抛弃卡）",
    "score": 0,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "145",
    "name": "M15BO打刀",
    "score": 81,
    "structure": 0,
    "armor": 4,
    "parray": 2,
    "dodge": 2,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "148",
    "name": "G6霰射炮 + M5刺桩",
    "score": 69,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 1,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "throwIndex":"149",
  },
  {
    "id": "149",
    "name": "G6霰射炮 + M5刺桩（抛弃卡）",
    "score": 0,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 1,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "257",
    "name": "K9钉刺枪 + M14BO胁差试作型（右）",
    "score": 42,
    "structure": 0,
    "armor": 3,
    "parray": 1,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  }
];

export const unBackpack: Part[] = [
  {
    "id": "081",
    "name": "EBS/X40护甲充能器",
    "score": 39,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 2,
    "electronic": 0,
    "type": "backpack",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "082",
    "name": "GSD2A幽灵蛛挂架",
    "score": 21,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "backpack",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "projectile":["156"]
  },
  {
    "id": "083",
    "name": "CSC60冷却剂背包",
    "score": 27,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 1,
    "electronic": 0,
    "type": "backpack",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "084",
    "name": "DBP龟壳掩体挂架",
    "score": 39,
    "structure": 0,
    "armor": 5,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "backpack",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "projectile":["158"]
  },
  {
    "id": "085",
    "name": "AMDS210翠雀携带包",
    "score": 30,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "backpack",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "086",
    "name": "RKG70弹药补充包",
    "score": 21,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "backpack",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "projectile":["157"]
  },
  {
    "id": "087",
    "name": "MSH2稳定臂",
    "score": 24,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "backpack",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "088",
    "name": "JP1喷射包",
    "score": 57,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 2,
    "electronic": 0,
    "type": "backpack",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "089",
    "name": "EC50电战荚舱",
    "score": 42,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 1,
    "electronic": 1,
    "type": "backpack",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "090",
    "name": "OCSP超载包",
    "score": 49,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 2,
    "electronic": 0,
    "type": "backpack",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "265",
    "name": "EBS/X40护甲充能器试作型",
    "score": 39,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 2,
    "electronic": 0,
    "type": "backpack",
    "description": "",
    "imgSrc": "",
    "tags": []
  }
];

export const unProjectiles: Projectile[] = [
  {
    "id": "154",
    "name": "M7手雷",
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 2,
    "electronic": 0,
    "stance": "offensive",
    "imgSrc": ""
  },
  {
    "id": "155",
    "name": "M9闪光弹",
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 2,
    "electronic": 0,
    "stance": "offensive",
    "imgSrc": ""
  },
  {
    "id": "156",
    "name": "SGM2幽灵蛛自行地雷",
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 2,
    "electronic": 2,
    "stance": "offensive",
    "imgSrc": ""
  },
  {
    "id": "157",
    "name": "RKG70导弹组",
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 3,
    "electronic": 1,
    "stance": "offensive",
    "imgSrc": ""
  },
  {
    "id": "158",
    "name": "DBP龟壳机动掩体",
    "structure": 0,
    "armor": 5,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "stance": "offensive",
    "imgSrc": ""
  }
];

export const unDrones: Drone[] = [
  {
    "id": "159",
    "name": "AMDS210翠雀自动防御系统",
    "score": 0,
    "structure": 0,
    "armor": 2,
    "parray": 0,
    "dodge": 0,
    "electronic": 2,
    "type": "small",
    "move": 0,
    "stance": "offensive",
    "description": ""
  },
  {
    "id": "160",
    "name": "ADK15D近防型豪猪",
    "score": 48,
    "structure": 2,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 2,
    "type": "small",
    "move": 0,
    "stance": "offensive",
    "description": ""
  },
  {
    "id": "161",
    "name": "ADK15/MAS 微波型豪猪",
    "score": 30,
    "structure": 2,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 2,
    "type": "small",
    "move": 0,
    "stance": "offensive",
    "description": ""
  },
  {
    "id": "162",
    "name": "ADK30C 运载型狼蛛",
    "score": 12,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 5,
    "electronic": 2,
    "type": "small",
    "move": 0,
    "stance": "offensive",
    "description": ""
  },
  {
    "id": "163",
    "name": "ADK30F 火力型狼蛛",
    "score": 33,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 5,
    "electronic": 2,
    "type": "small",
    "move": 0,
    "stance": "offensive",
    "description": ""
  },
  {
    "id": "164",
    "name": "ADK60R 侦查型渡鸦",
    "score": 33,
    "structure": 0,
    "armor": 1,
    "parray": 0,
    "dodge": 7,
    "electronic": 3,
    "type": "small",
    "move": 0,
    "stance": "offensive",
    "description": ""
  },
  {
    "id": "165",
    "name": "ADK60EC 电战型渡鸦",
    "score": 33,
    "structure": 0,
    "armor": 1,
    "parray": 0,
    "dodge": 7,
    "electronic": 3,
    "type": "small",
    "move": 0,
    "stance": "offensive",
    "description": ""
  },
  {
    "id": "166",
    "name": "ADK60S 干扰型渡鸦",
    "score": 51,
    "structure": 0,
    "armor": 1,
    "parray": 0,
    "dodge": 7,
    "electronic": 3,
    "type": "small",
    "move": 0,
    "stance": "offensive",
    "description": ""
  },
  {
    "id": "167",
    "name": "SGM2幽灵蛛自行地雷(展开）",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 2,
    "electronic": 2,
    "type": "small",
    "move": 0,
    "stance": "offensive",
    "description": ""
  }
];


