import { Part, Drone, Pilot, Projectile,TacticCard } from '../../src/types';

export const rdlTorso: Part[] = [
  {
    "id": "012",
    "name": "RT-06  Mire  Battle Core",
    "score": 15,
    "structure": 2,
    "armor": 6,
    "parray": 0,
    "dodge": 0,
    "electronic": 2,
    "type": "torso",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "014",
    "name": "RT-07T  Dune  Tactical Core",
    "score": 62,
    "structure": 4,
    "armor": 5,
    "parray": 0,
    "dodge": 0,
    "electronic": 3,
    "type": "torso",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "015",
    "name": "RT-08  Tempest  Artillery Core",
    "score": 62,
    "structure": 2,
    "armor": 7,
    "parray": 0,
    "dodge": 0,
    "electronic": 3,
    "type": "torso",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "016",
    "name": "RT-09A  Volcano  Armored Core",
    "score": 66,
    "structure": 4,
    "armor": 6,
    "parray": 0,
    "dodge": 0,
    "electronic": 3,
    "type": "torso",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "projectile": [
      "268"
    ]
  },
  {
    "id": "017",
    "name": "RT-15B  Lava  Assault Core",
    "score": 59,
    "structure": 4,
    "armor": 5,
    "parray": 0,
    "dodge": 1,
    "electronic": 3,
    "type": "torso",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "projectile": [
      "268"
    ]
  },
  {
    "id": "019",
    "name": "RT-15C  Glacier  Assault Core",
    "score": 56,
    "structure": 4,
    "armor": 5,
    "parray": 0,
    "dodge": 1,
    "electronic": 2,
    "type": "torso",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "projectile": [
      "268"
    ]
  },
  {
    "id": "018",
    "name": "RT-15/EC  Aurora  ECM Core",
    "score": 60,
    "structure": 4,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 3,
    "type": "torso",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "246",
    "name": "RT-09M  Volcano-M  Armored Core",
    "score": 66,
    "structure": 4,
    "armor": 6,
    "parray": 0,
    "dodge": 0,
    "electronic": 3,
    "type": "torso",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "projectile": [
      "268"
    ]
  },
  {
    "id": "280",
    "name": "RT-09M II  Volcano M II  Armored Core",
    "score": 66,
    "structure": 4,
    "armor": 6,
    "parray": 0,
    "dodge": 0,
    "electronic": 3,
    "type": "torso",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "projectile": [
      "268"
    ]
  },
  {
    "id": "503",
    "name": "RT-16B Avalanche Assault Core",
    "score": 60,
    "structure": 4,
    "armor": 5,
    "parray": 0,
    "dodge": 1,
    "electronic": 3,
    "type": "torso",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "projectile": [
      "268"
    ]
  },
  {
    "id": "504",
    "name": "RT-15/S Nimbus Support Core",
    "score": 60,
    "structure": 4,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 3,
    "type": "torso",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "505",
    "name": "RT-06E  Mire E  Battle Core",
    "score": 21,
    "structure": 2,
    "armor": 6,
    "parray": 0,
    "dodge": 0,
    "electronic": 3,
    "type": "torso",
    "description": "",
    "imgSrc": "",
    "tags": []
  }
];

export const rdlChasis: Part[] = [
  {
    "id": "020",
    "name": "RL-06  Standard Chassis",
    "score": 18,
    "structure": 0,
    "armor": 5,
    "parray": 0,
    "dodge": 3,
    "electronic": 0,
    "type": "chasis",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "021",
    "name": "RL-08  Armored Chassis",
    "score": 30,
    "structure": 1,
    "armor": 6,
    "parray": 0,
    "dodge": 3,
    "electronic": 0,
    "type": "chasis",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "022",
    "name": "RL-03D  Swift Steed High-mobility Chassis",
    "score": 42,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 4,
    "electronic": 0,
    "type": "chasis",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "249",
    "name": "RL-08M  Armored Chassis",
    "score": 30,
    "structure": 1,
    "armor": 6,
    "parray": 0,
    "dodge": 3,
    "electronic": 0,
    "type": "chasis",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "281",
    "name": "RL-08M II Armored Chassis",
    "score": 45,
    "structure": 2,
    "armor": 6,
    "parray": 0,
    "dodge": 2,
    "electronic": 0,
    "type": "chasis",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "506",
    "name": "RL-06M  Standard Chassis",
    "score": 18,
    "structure": 0,
    "armor": 5,
    "parray": 0,
    "dodge": 3,
    "electronic": 0,
    "type": "chasis",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "507",
    "name": "RL-06MS Support Chassis",
    "score": 24,
    "structure": 0,
    "armor": 5,
    "parray": 0,
    "dodge": 3,
    "electronic": 0,
    "type": "chasis",
    "description": "",
    "imgSrc": "",
    "tags": []
  }
];

export const rdlLeftHand: Part[] = [
  {
    "id": "023",
    "name": "Type 55 Shield + CC-6 Cleaver",
    "score": 54,
    "structure": 0,
    "armor": 5,
    "parray": 2,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "throwIndex": "024"
  },
  {
    "id": "024",
    "name": "Type 55 Shield + CC-6 Cleaver (D)",
    "score": 0,
    "structure": 0,
    "armor": 5,
    "parray": 2,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "029",
    "name": "ML-32 Dual Launcher + CC-3 Dagger",
    "score": 33,
    "structure": 0,
    "armor": 4,
    "parray": 1,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "projectile": [
      "071"
    ]
  },
  {
    "id": "032",
    "name": "R-20 Shoulder-Mounted Railgun (L)",
    "score": 51,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "034",
    "name": "Type 77 Bulwark",
    "score": 50,
    "structure": 0,
    "armor": 8,
    "parray": 1,
    "dodge": -2,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "throwIndex": "035"
  },
  {
    "id": "035",
    "name": "Type 77 Bulwark (D)",
    "score": 0,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "040",
    "name": "SPHX-3 Supporting Arm",
    "score": 42,
    "structure": 0,
    "armor": 4,
    "parray": 1,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "041",
    "name": "L-320 SMMG + Type 55 Shield + CC-6 Cleaver",
    "score": 51,
    "structure": 0,
    "armor": 5,
    "parray": 2,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "throwIndex": "042"
  },
  {
    "id": "042",
    "name": "L-320 SMMG + Type 55 Shield + CC-6 Cleaver (D)",
    "score": 0,
    "structure": 0,
    "armor": 5,
    "parray": 2,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "045",
    "name": "Type 79 Combat Shield",
    "score": 56,
    "structure": 0,
    "armor": 6,
    "parray": 2,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "050",
    "name": "FCC-12 Big Hand Grappler",
    "score": 69,
    "structure": 0,
    "armor": 4,
    "parray": 3,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "053",
    "name": "Type 55 Shield + PC-9 Shotgun (L)",
    "score": 48,
    "structure": 0,
    "armor": 5,
    "parray": 2,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "throwIndex": "054"
  },
  {
    "id": "054",
    "name": "Type 55 Shield + PC-9 Shotgun (L) (D)",
    "score": 0,
    "structure": 0,
    "armor": 5,
    "parray": 2,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "056",
    "name": "G/AC-6 Rocket Launcher",
    "score": 36,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "projectile": [
      "267"
    ],
    "throwIndex": "057"
  },
  {
    "id": "057",
    "name": "G/AC-6 Rocket Launcher (D)",
    "score": 0,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "062",
    "name": "Type 62 Buckler + CC-20 Sabre (L)",
    "score": 63,
    "structure": 0,
    "armor": 5,
    "parray": 3,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "064",
    "name": "Type 55 Shield + MES Beacon Launcher",
    "score": 45,
    "structure": 0,
    "armor": 5,
    "parray": 2,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "projectile": [
      "072"
    ],
    "throwIndex": "065"
  },
  {
    "id": "065",
    "name": "Type 55 Shield + MES Beacon Launcher (D)",
    "score": 0,
    "structure": 0,
    "armor": 5,
    "parray": 2,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "252",
    "name": "Type 77 Bulwark (Early Model)",
    "score": 50,
    "structure": 0,
    "armor": 8,
    "parray": 1,
    "dodge": -2,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "throwIndex": "253"
  },
  {
    "id": "253",
    "name": "Type 77 Bulwark (Early Model) (D)",
    "score": 0,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "282",
    "name": "L-330 SMMG + Type 77B Bulwark",
    "score": 56,
    "structure": 0,
    "armor": 9,
    "parray": 1,
    "dodge": -3,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "throwIndex": "283"
  },
  {
    "id": "283",
    "name": "L-330 SMMG + Type 77B Bulwark(D)",
    "score": 0,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "510",
    "name": "Type 55 Shield + PC-9K Shotgun (L)",
    "score": 63,
    "structure": 0,
    "armor": 5,
    "parray": 2,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "throwIndex": "511"
  },
  {
    "id": "511",
    "name": "Type 55 Shield + PC-9K Shotgun (L) (D)",
    "score": 0,
    "structure": 0,
    "armor": 5,
    "parray": 2,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "514",
    "name": "AH-21 Pistol + CC-50 Pile Bunker (L)",
    "score": 63,
    "structure": 0,
    "armor": 4,
    "parray": 1,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "throwIndex": "515"
  },
  {
    "id": "515",
    "name": "AH-21 Pistol + CC-50 Pile Bunker (L) (D)",
    "score": 0,
    "structure": 0,
    "armor": 4,
    "parray": 1,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "520",
    "name": "Type 55 Shield",
    "score": 30,
    "structure": 0,
    "armor": 5,
    "parray": 2,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  }
];

export const rdlRightHand: Part[] = [
  {
    "id": "025",
    "name": "AC-32 Automatic Rifle",
    "score": 24,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "throwIndex": "026"
  },
  {
    "id": "026",
    "name": "AC-32 Automatic Rifle (D)",
    "score": 0,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "030",
    "name": "AC-150 HMG",
    "score": 42,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": -2,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "throwIndex": "031"
  },
  {
    "id": "031",
    "name": "AC-150 HMG (D)",
    "score": 0,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "033",
    "name": "R-20 Shoulder-Mounted Railgun (R)",
    "score": 51,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "036",
    "name": "CC-4 Cleaver (R)",
    "score": 39,
    "structure": 0,
    "armor": 4,
    "parray": 1,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "038",
    "name": "ACX-350 Stratus Prototype HMG",
    "score": 48,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": -2,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "throwIndex": "039"
  },
  {
    "id": "039",
    "name": "ACX-350 Stratus Prototype HMG (D)",
    "score": 0,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "043",
    "name": "R-35 Heavy Railgun",
    "score": 54,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": -2,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "throwIndex": "044"
  },
  {
    "id": "044",
    "name": "R-35 Heavy Railgun (D)",
    "score": 0,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "046",
    "name": "Type 55 Shield + PC-9 Shotgun (R)",
    "score": 48,
    "structure": 0,
    "armor": 5,
    "parray": 2,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "throwIndex": "047"
  },
  {
    "id": "047",
    "name": "Type 55 Shield + PC-9 Shotgun (R) (D)",
    "score": 0,
    "structure": 0,
    "armor": 5,
    "parray": 2,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "048",
    "name": "Type 55 Shield + PC-9 Shotgun + Smoke Grenade (R)",
    "score": 57,
    "structure": 0,
    "armor": 5,
    "parray": 2,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "projectile": [
      "268"
    ],
    "throwIndex": "049"
  },
  {
    "id": "049",
    "name": "Type 55 Shield + PC-9 Shotgun + Smoke Grenade (R) (D)",
    "score": 0,
    "structure": 0,
    "armor": 5,
    "parray": 2,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "projectile": [
      "268"
    ]
  },
  {
    "id": "051",
    "name": "L-320 SMMG + CC-90 Glaive",
    "score": 63,
    "structure": 0,
    "armor": 4,
    "parray": 1,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "throwIndex": "052"
  },
  {
    "id": "052",
    "name": "L-320 SMMG + CC-90 Glaive (D)",
    "score": 0,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "055",
    "name": "CC-100 Hercules Meteor Hammer",
    "score": 48,
    "structure": 0,
    "armor": 4,
    "parray": 1,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "058",
    "name": "AC-39 Tactical Rifle",
    "score": 45,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "throwIndex": "059"
  },
  {
    "id": "059",
    "name": "AC-39 Tactical Rifle (D)",
    "score": 0,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "063",
    "name": "Type 63 Arm Cannon + CC-20 Sabre (R)",
    "score": 66,
    "structure": 0,
    "armor": 4,
    "parray": 2,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "068",
    "name": "AC-161 SMG",
    "score": 45,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "throwIndex": "069"
  },
  {
    "id": "069",
    "name": "AC-161 SMG (D)",
    "score": 0,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "254",
    "name": "L-320 SMMG + CC-90 Glaive (Early Model)",
    "score": 63,
    "structure": 0,
    "armor": 4,
    "parray": 1,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "throwIndex": "255"
  },
  {
    "id": "255",
    "name": "L-320 SMMG + CC-90 Glaive (Early Model) (D)",
    "score": 0,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "284",
    "name": "L-330 SMMG + CC-85 Rock Saw",
    "score": 57,
    "structure": 0,
    "armor": 4,
    "parray": 1,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "throwIndex": "285"
  },
  {
    "id": "285",
    "name": "L-330 SMMG + CC-85 Rock Saw(D)",
    "score": 0,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "508",
    "name": "Type 55 Shield + PC-9K Shotgun (R)",
    "score": 63,
    "structure": 0,
    "armor": 5,
    "parray": 2,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "throwIndex": "509"
  },
  {
    "id": "509",
    "name": "Type 55 Shield + PC-9K Shotgun (R) (D)",
    "score": 0,
    "structure": 0,
    "armor": 5,
    "parray": 2,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "512",
    "name": "AH-21 Pistol + CC-50 Pile Bunker (R) (D)",
    "score": 63,
    "structure": 0,
    "armor": 4,
    "parray": 1,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "throwIndex": "513"
  },
  {
    "id": "513",
    "name": "AH-21 Pistol + CC-50 Pile Bunker (R) (D)",
    "score": 0,
    "structure": 0,
    "armor": 4,
    "parray": 1,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "516",
    "name": "AC-35 Sniper Rifle",
    "score": 51,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "throwIndex": "517"
  },
  {
    "id": "517",
    "name": "AC-35 Sniper Rifle (D)",
    "score": 0,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "518",
    "name": "AC-32C Auto Rifle",
    "score": 36,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "throwIndex": "519"
  },
  {
    "id": "519",
    "name": "AC-32C Auto Rifle (D)",
    "score": 0,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "rightHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  }
];

export const rdlBackpack: Part[] = [
  {
    "id": "001",
    "name": "SH-15 Field Repair System",
    "score": 30,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 2,
    "electronic": 0,
    "type": "backpack",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "002",
    "name": "ECS-2 External Cooler",
    "score": 33,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 1,
    "electronic": 0,
    "type": "backpack",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "003",
    "name": "AMS-190 Active Defense System",
    "score": 27,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 0,
    "electronic": 1,
    "type": "backpack",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "004",
    "name": "ML-34 Quad Missile Rack",
    "score": 39,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 1,
    "electronic": 0,
    "type": "backpack",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "projectile": [
      "071"
    ]
  },
  {
    "id": "005",
    "name": "LGP-80 Artillery",
    "score": 33,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": -2,
    "electronic": 0,
    "type": "backpack",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "006",
    "name": "GLP-15 Mine Layer",
    "score": 30,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "backpack",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "projectile": [
      "074"
    ]
  },
  {
    "id": "007",
    "name": "MUD-1 Muck ECM Backpack",
    "score": 33,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 1,
    "electronic": 1,
    "type": "backpack",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "008",
    "name": "CP-3 Beacon Backpack",
    "score": 36,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "backpack",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "projectile": [
      "075",
      "076",
      "077"
    ]
  },
  {
    "id": "009",
    "name": "MUE/N-20 Echoes Support Backpack",
    "score": 30,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "backpack",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "010",
    "name": "TB-600 Jetpack",
    "score": 48,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 2,
    "electronic": 0,
    "type": "backpack",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "011",
    "name": "ML-92 Dual Missile Rack",
    "score": 20,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "backpack",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "projectile": [
      "073"
    ]
  },
  {
    "id": "264",
    "name": "AMS-192 Active Defense System",
    "score": 27,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 0,
    "electronic": 1,
    "type": "backpack",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "286",
    "name": "AMS-193 Active Defense System",
    "score": 27,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 0,
    "electronic": 1,
    "type": "backpack",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "501",
    "name": "ML-94 Quad Missile Rack",
    "score": 48,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "backpack",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "projectile": [
      "521"
    ]
  },
  {
    "id": "502",
    "name": "CP-4 Drone Backpack",
    "score": 36,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "backpack",
    "description": "",
    "imgSrc": "",
    "tags": [], "projectile": [
      "522"
    ]
  }
];

export const rdlDrones: Drone[] = [
  {
    "id": "078",
    "name": "DTG-30M Hyena MG Type",
    "score": 42,
    "structure": 2,
    "armor": 5,
    "parray": 0,
    "dodge": 0,
    "electronic": 2,
    "type": "medium",
    "move": null,
    "stance": "offensive",
    "description": ""
  },
  {
    "id": "079",
    "name": "DTG-30S Hyena Missile Type",
    "score": 33,
    "structure": 2,
    "armor": 5,
    "parray": 0,
    "dodge": 0,
    "electronic": 2,
    "type": "medium",
    "move": null,
    "stance": "offensive",
    "description": "",
    "projectile": [
      "071"
    ]
  },
  {
    "id": "080",
    "name": "DTG-30R Hyena Radar Type",
    "score": 27,
    "structure": 2,
    "armor": 5,
    "parray": 0,
    "dodge": 0,
    "electronic": 2,
    "type": "medium",
    "move": null,
    "stance": "offensive",
    "description": "",
  },
  {
    "id": "522",
    "name": "MD-1 Dragonfly Micro Scout",
    "score": 0,
    "structure": 0,
    "armor": 2,
    "parray": 0,
    "dodge": 2,
    "electronic": 3,
    "type": "small",
    "move": null,
    "stance": "offensive",
    "description": ""
  }
];

export const unTorso: Part[] = [
  {
    "id": "091",
    "name": "TM31C Gray Wolf Battle Core",
    "score": 45,
    "structure": 4,
    "armor": 4,
    "parray": 0,
    "dodge": 1,
    "electronic": 3,
    "type": "torso",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "projectile": [
      "155"
    ]
  },
  {
    "id": "092",
    "name": "TM31R Caracal Battle Core",
    "score": 54,
    "structure": 4,
    "armor": 4,
    "parray": 0,
    "dodge": 1,
    "electronic": 4,
    "type": "torso",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "094",
    "name": "TM39 Viper Low Profile Core",
    "score": 63,
    "structure": 3,
    "armor": 3,
    "parray": 0,
    "dodge": 1,
    "electronic": 5,
    "type": "torso",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "096",
    "name": "TM641 Octopus Stealth Core",
    "score": 81,
    "structure": 3,
    "armor": 3,
    "parray": 0,
    "dodge": 1,
    "electronic": 5,
    "type": "torso",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "097",
    "name": "TM35N Alligator Electronic Warfare Core",
    "score": 72,
    "structure": 4,
    "armor": 5,
    "parray": 0,
    "dodge": 1,
    "electronic": 4,
    "type": "torso",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "098",
    "name": "TM35B Bison Assault Core",
    "score": 72,
    "structure": 4,
    "armor": 5,
    "parray": 0,
    "dodge": 1,
    "electronic": 4,
    "type": "torso",
    "description": "",
    "imgSrc": "",
    "tags": []
  }, {
    "id": "247",
    "name": "TM641 Octopus Stealth Core Trial Model",
    "score": 81,
    "structure": 3,
    "armor": 3,
    "parray": 0,
    "dodge": 1,
    "electronic": 5,
    "type": "torso",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  // {
  //   "id": "555",
  //   "name": "TM35BT Taurus Experimental Core",
  //   "score": 84,
  //   "armor": 5,
  //   "structure": 4,
  //   "parray": 0,
  //   "dodge": 1,
  //   "electronic": 4,
  //   "type": "torso",
  //   "imgSrc": "",
  //   "tags": []
  // }
];

export const unChasis: Part[] = [
  {
    "id": "099",
    "name": "LM231  Standard Chassis",
    "score": 27,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 4,
    "electronic": 0,
    "type": "chasis",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "100",
    "name": "LM210S  Stealth Chassis",
    "score": 39,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 4,
    "electronic": 0,
    "type": "chasis",
    "description": "",
    "imgSrc": "",
    "tags": []
  }, {
    "id": "250",
    "name": "LM210S  Stealth Chassis -Trial Mode",
    "score": 39,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 4,
    "electronic": 0,
    "type": "chasis",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "101",
    "name": "LM213B  Combat Chassis",
    "score": 57,
    "structure": 1,
    "armor": 4,
    "parray": 0,
    "dodge": 4,
    "electronic": 0,
    "type": "chasis",
    "description": "",
    "imgSrc": "",
    "tags": []
  }
];

export const unLeftHand: Part[] = [
  {
    "id": "103",
    "name": "S9 Meteor Shield + M5 Pile Bunker",
    "score": 57,
    "structure": 0,
    "armor": 4,
    "parray": 2,
    "dodge": 1,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "107",
    "name": "S100 Shield + Grenade Pod",
    "score": 66,
    "structure": 0,
    "armor": 5,
    "parray": 2,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "projectile": [
      "154"
    ],
    "throwIndex": "108"
  },
  {
    "id": "108",
    "name": "S100 Shield + Grenade Pod (D)",
    "score": 0,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "projectile": [
      "154"
    ]
  },
  {
    "id": "111",
    "name": "RH21 Pistol + M3 Vibroblade (L)",
    "score": 45,
    "structure": 0,
    "armor": 3,
    "parray": 1,
    "dodge": 1,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "throwIndex": "112"
  },
  {
    "id": "112",
    "name": "RH21 Pistol + M3 Vibroblade (L) (D)",
    "score": 0,
    "structure": 0,
    "armor": 3,
    "parray": 1,
    "dodge": 1,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "117",
    "name": "MDXS Fairy System + R6 SMG (L)",
    "score": 45,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 2,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "throwIndex": "118"
  },
  {
    "id": "118",
    "name": "MDXS Fairy System + R6 SMG (L) (D)",
    "score": 0,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 2,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "121",
    "name": "MSH1 Assistance Arm (L)",
    "score": 24,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "126",
    "name": "K9 Nail Gun + M14BO Wakizashi",
    "score": 42,
    "structure": 0,
    "armor": 3,
    "parray": 1,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  }, {
    "id": "256",
    "name": "K9 Nail Gun + M14BO Wakizashi Trial Model (L)",
    "score": 42,
    "structure": 0,
    "armor": 3,
    "parray": 1,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "129",
    "name": "RKG70  Missile Pod",
    "score": 42,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "projectile": [
      "157"
    ],
    "throwIndex": "130"
  },
  {
    "id": "130",
    "name": "RKG70  Missile Pod (D)",
    "score": 0,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "131",
    "name": "M3S Vibroblade(L)",
    "score": 42,
    "structure": 0,
    "armor": 3,
    "parray": 1,
    "dodge": 1,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "135",
    "name": "M4 Vibroblade + Grenade Pod (L)",
    "score": 54,
    "structure": 0,
    "armor": 3,
    "parray": 1,
    "dodge": 1,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "projectile": [
      "154"
    ]
  },
  {
    "id": "139",
    "name": "MX82 Multifunctional Whip",
    "score": 48,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 1,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "142",
    "name": "S100 Shield",
    "score": 48,
    "structure": 0,
    "armor": 5,
    "parray": 2,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "throwIndex": "143"
  },
  {
    "id": "143",
    "name": "S100 Shield (D)",
    "score": 0,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "144",
    "name": "K7 Nail Gun + S10 Shield",
    "score": 54,
    "structure": 0,
    "armor": 5,
    "parray": 2,
    "dodge": 0,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "146",
    "name": "G6 Shotgun + Grenade Pod",
    "score": 75,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 1,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "projectile": [
      "154"
    ],
    "throwIndex": "147"
  },
  {
    "id": "147",
    "name": "G6 Shotgun + Grenade Pod (D)",
    "score": 0,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 1,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "projectile": [
      "154"
    ]
  },
  {
    "id": "150",
    "name": "RHX23 Rainstorm Assault Pistol (L)",
    "score": 57,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 2,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "throwIndex": "151"
  },
  {
    "id": "151",
    "name": "RHX23 Rainstorm Assault Pistol (L) (D)",
    "score": 0,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 2,
    "electronic": 0,
    "type": "leftHand",
    "description": "",
    "imgSrc": "",
    "tags": []
  }
];

export const unRightHand: Part[] = [{
  "id": "257",
  "name": "K9 Nail Gun + M14BO Wakizashi Trial Model (L)",
  "score": 42,
  "structure": 0,
  "armor": 3,
  "parray": 1,
  "dodge": 0,
  "electronic": 0,
  "type": "rightHand",
  "description": "",
  "imgSrc": "",
  "tags": []
},
{
  "id": "104",
  "name": "R7 Automatic Rifle",
  "score": 42,
  "structure": 0,
  "armor": 3,
  "parray": 0,
  "dodge": 0,
  "electronic": 0,
  "type": "rightHand",
  "description": "",
  "imgSrc": "",
  "tags": [],
  "throwIndex": "105"
},
{
  "id": "105",
  "name": "R7 Automatic Rifle (D)",
  "score": 0,
  "structure": 0,
  "armor": 3,
  "parray": 0,
  "dodge": 0,
  "electronic": 0,
  "type": "rightHand",
  "description": "",
  "imgSrc": "",
  "tags": []
},
{
  "id": "106",
  "name": "R33 Sniper Rifle",
  "score": 39,
  "structure": 0,
  "armor": 3,
  "parray": 0,
  "dodge": 0,
  "electronic": 0,
  "type": "rightHand",
  "description": "",
  "imgSrc": "",
  "tags": []
},
{
  "id": "109",
  "name": "R6 SMG",
  "score": 54,
  "structure": 0,
  "armor": 3,
  "parray": 0,
  "dodge": 1,
  "electronic": 0,
  "type": "rightHand",
  "description": "",
  "imgSrc": "",
  "tags": []
},
{
  "id": "110",
  "name": "R6 SMG (D)",
  "score": 0,
  "structure": 0,
  "armor": 3,
  "parray": 0,
  "dodge": 1,
  "electronic": 0,
  "type": "rightHand",
  "description": "",
  "imgSrc": "",
  "tags": []
},
{
  "id": "113",
  "name": "RH21 Pistol + M3 Vibroblade (R)",
  "score": 45,
  "structure": 0,
  "armor": 3,
  "parray": 1,
  "dodge": 1,
  "electronic": 0,
  "type": "rightHand",
  "description": "",
  "imgSrc": "",
  "tags": [],
  "throwIndex": "114"
},
{
  "id": "114",
  "name": "RH21 Pistol + M3 Vibroblade (R) (D)",
  "score": 0,
  "structure": 0,
  "armor": 3,
  "parray": 1,
  "dodge": 1,
  "electronic": 0,
  "type": "rightHand",
  "description": "",
  "imgSrc": "",
  "tags": []
},
{
  "id": "115",
  "name": "S100 Shield + R6SS SMG",
  "score": 63,
  "structure": 0,
  "armor": 5,
  "parray": 2,
  "dodge": 0,
  "electronic": 0,
  "type": "rightHand",
  "description": "",
  "imgSrc": "",
  "tags": [],
  "throwIndex": "116"
},
{
  "id": "116",
  "name": "S100 Shield + R6SS SMG (D)",
  "score": 0,
  "structure": 0,
  "armor": 4,
  "parray": 0,
  "dodge": 0,
  "electronic": 0,
  "type": "rightHand",
  "description": "",
  "imgSrc": "",
  "tags": []
},
{
  "id": "119",
  "name": "MDXS Fairy System + R6 SMG (R)",
  "score": 45,
  "structure": 0,
  "armor": 3,
  "parray": 0,
  "dodge": 2,
  "electronic": 0,
  "type": "rightHand",
  "description": "",
  "imgSrc": "",
  "tags": [],
  "throwIndex": "120"
},
{
  "id": "120",
  "name": "MDXS Fairy System + R6 SMG (R) (D)",
  "score": 0,
  "structure": 0,
  "armor": 3,
  "parray": 0,
  "dodge": 2,
  "electronic": 0,
  "type": "rightHand",
  "description": "",
  "imgSrc": "",
  "tags": []
},
{
  "id": "122",
  "name": "IGX920 Heavy Ion Gun",
  "score": 60,
  "structure": 0,
  "armor": 4,
  "parray": 0,
  "dodge": -2,
  "electronic": 0,
  "type": "rightHand",
  "description": "",
  "imgSrc": "",
  "tags": [],
  "throwIndex": "123",
},
{
  "id": "123",
  "name": "IGX920 Heavy Ion Gun (D)",
  "score": 0,
  "structure": 0,
  "armor": 4,
  "parray": 0,
  "dodge": 0,
  "electronic": 0,
  "type": "rightHand",
  "description": "",
  "imgSrc": "",
  "tags": []
},
{
  "id": "124",
  "name": "R6SD SMG",
  "score": 60,
  "structure": 0,
  "armor": 3,
  "parray": 0,
  "dodge": 1,
  "electronic": 0,
  "type": "rightHand",
  "description": "",
  "imgSrc": "",
  "tags": [],
  "throwIndex": "125"
},
{
  "id": "125",
  "name": "R6SD SMG (D)",
  "score": 0,
  "structure": 0,
  "armor": 3,
  "parray": 0,
  "dodge": 1,
  "electronic": 0,
  "type": "rightHand",
  "description": "",
  "imgSrc": "",
  "tags": []
},
{
  "id": "127",
  "name": "R9B Tactical Rifle",
  "score": 48,
  "structure": 0,
  "armor": 3,
  "parray": 0,
  "dodge": 0,
  "electronic": 0,
  "type": "rightHand",
  "description": "",
  "imgSrc": "",
  "tags": [],
  "throwIndex": "128"
},
{
  "id": "128",
  "name": "R9B Tactical Rifle (D)",
  "score": 0,
  "structure": 0,
  "armor": 3,
  "parray": 0,
  "dodge": 0,
  "electronic": 0,
  "type": "rightHand",
  "description": "",
  "imgSrc": "",
  "tags": []
},
{
  "id": "133",
  "name": "M3S Vibroblade (R)",
  "score": 42,
  "structure": 0,
  "armor": 3,
  "parray": 1,
  "dodge": 1,
  "electronic": 0,
  "type": "rightHand",
  "description": "",
  "imgSrc": "",
  "tags": []
},
{
  "id": "137",
  "name": "M4 Vibroblade + Grenade Pod (R)",
  "score": 54,
  "structure": 0,
  "armor": 3,
  "parray": 1,
  "dodge": 1,
  "electronic": 0,
  "type": "rightHand",
  "description": "",
  "imgSrc": "",
  "tags": [],
  "projectile": [
    "154"
  ]
},
{
  "id": "140",
  "name": "IGX350 Ion Shotgun",
  "score": 45,
  "structure": 0,
  "armor": 4,
  "parray": 0,
  "dodge": 0,
  "electronic": 0,
  "type": "rightHand",
  "description": "",
  "imgSrc": "",
  "tags": [],
  "throwIndex": "141"
},
{
  "id": "141",
  "name": "IGX350 Ion Shotgun (D)",
  "score": 0,
  "structure": 0,
  "armor": 4,
  "parray": 0,
  "dodge": 0,
  "electronic": 0,
  "type": "rightHand",
  "description": "",
  "imgSrc": "",
  "tags": []
},
{
  "id": "145",
  "name": "M15BO Katana",
  "score": 81,
  "structure": 0,
  "armor": 4,
  "parray": 2,
  "dodge": 2,
  "electronic": 0,
  "type": "rightHand",
  "description": "",
  "imgSrc": "",
  "tags": []
},
{
  "id": "148",
  "name": "G6 Shotgun + M5 Pile Bunker",
  "score": 69,
  "structure": 0,
  "armor": 4,
  "parray": 0,
  "dodge": 1,
  "electronic": 0,
  "type": "rightHand",
  "description": "",
  "imgSrc": "",
  "tags": [],
  "throwIndex": "149"
},
{
  "id": "149",
  "name": "G6 Shotgun + M5 Pile Bunker (D)",
  "score": 0,
  "structure": 0,
  "armor": 4,
  "parray": 0,
  "dodge": 1,
  "electronic": 0,
  "type": "rightHand",
  "description": "",
  "imgSrc": "",
  "tags": []
},
{
  "id": "152",
  "name": "RHX23 Rainstorm Assault Pistol (R)",
  "score": 57,
  "structure": 0,
  "armor": 3,
  "parray": 0,
  "dodge": 2,
  "electronic": 0,
  "type": "rightHand",
  "description": "",
  "imgSrc": "",
  "tags": [],
  "throwIndex": "153"
},
{
  "id": "153",
  "name": "RHX23 Rainstorm Assault Pistol (R) (D)",
  "score": 0,
  "structure": 0,
  "armor": 3,
  "parray": 0,
  "dodge": 2,
  "electronic": 0,
  "type": "rightHand",
  "description": "",
  "imgSrc": "",
  "tags": []
},
// {
//     "id": "556",
//     "name": "R7MG LMG",
//     "score": 50,
//     "armor": 3,
//     "structure": 0,
//     "parray": 0,
//     "dodge": 0,
//     "electronic": 0,
//     "type": "rightHand",
//     "imgSrc": "",
//     "tags": []
//   },
//   {
//     "id": "557",
//     "name": "R7MG LMG (D)",
//     "score": 0,
//     "armor": 3,
//     "structure": 0,
//     "parray": 0,
//     "dodge": 0,
//     "electronic": 0,
//     "type": "rightHand",
//     "imgSrc": "",
//     "tags": []
//   }
];

export const unBackpack: Part[] = [
  {
    "id": "081",
    "name": "EBS/X40 Armor Energy Charger",
    "score": 39,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 2,
    "electronic": 0,
    "type": "backpack",
    "description": "",
    "imgSrc": "",
    "tags": []
  }, {
    "id": "265",
    "name": "EBS/X40 Armor Energy Charger Trial Model",
    "score": 39,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 2,
    "electronic": 0,
    "type": "backpack",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "082",
    "name": "GSD2A Pholcus Mine Rack",
    "score": 21,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "backpack",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "projectile": [
      "156"
    ]
  },
  {
    "id": "083",
    "name": "CSC60 Cooler",
    "score": 27,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 1,
    "electronic": 0,
    "type": "backpack",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "084",
    "name": "DBP Turtle Shell Barricade Rack",
    "score": 39,
    "structure": 0,
    "armor": 5,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "backpack",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "projectile": [
      "158"
    ]
  },
  {
    "id": "085",
    "name": "AMDS210 Delphinium Carrier",
    "score": 30,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "backpack",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "086",
    "name": "RKG70 Ammunition Pack",
    "score": 21,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "backpack",
    "description": "",
    "imgSrc": "",
    "tags": [],
    "projectile": [
      "157"
    ]
  },
  {
    "id": "087",
    "name": "MSH2 Stabilizer Arm",
    "score": 24,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "type": "backpack",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "088",
    "name": "JP1 Jetpack",
    "score": 57,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 2,
    "electronic": 0,
    "type": "backpack",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "089",
    "name": "EC50 Electronic Warfare Pod",
    "score": 42,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 1,
    "electronic": 1,
    "type": "backpack",
    "description": "",
    "imgSrc": "",
    "tags": []
  },
  {
    "id": "090",
    "name": "OCSP Overloading Pack",
    "score": 49,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 2,
    "electronic": 0,
    "type": "backpack",
    "description": "",
    "imgSrc": "",
    "tags": []
  }
];

export const unDrones: Drone[] = [
  {
    "id": "159",
    "name": "AMDS210 Delphinium Automatic Defense System",
    "score": 0,
    "structure": 0,
    "armor": 2,
    "parray": 0,
    "dodge": 0,
    "electronic": 2,
    "type": "small",
    "move": null,
    "stance": "offensive",
    "description": ""
  },
  {
    "id": "160",
    "name": "ADK15D Porcupine CIWS Type",
    "score": 48,
    "structure": 2,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 2,
    "type": "medium",
    "move": null,
    "stance": "offensive",
    "description": ""
  },
  {
    "id": "161",
    "name": "ADK15/MAS Porcupine Microwave Type",
    "score": 30,
    "structure": 2,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 2,
    "type": "medium",
    "move": null,
    "stance": "offensive",
    "description": ""
  },
  {
    "id": "162",
    "name": "ADK30C Tarantula Carrier Type",
    "score": 12,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 5,
    "electronic": 2,
    "type": "medium",
    "move": null,
    "stance": "offensive",
    "description": ""
  },
  {
    "id": "163",
    "name": "ADK30F Tarantula Firepower Type",
    "score": 33,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 5,
    "electronic": 2,
    "type": "small",
    "move": null,
    "stance": "offensive",
    "description": ""
  },
  {
    "id": "164",
    "name": "ADK60R Raven Scout Type",
    "score": 33,
    "structure": 0,
    "armor": 1,
    "parray": 0,
    "dodge": 7,
    "electronic": 3,
    "type": "medium",
    "move": null,
    "stance": "offensive",
    "description": ""
  },
  {
    "id": "165",
    "name": "ADK60EC Raven EC Type",
    "score": 33,
    "structure": 0,
    "armor": 1,
    "parray": 0,
    "dodge": 7,
    "electronic": 3,
    "type": "medium",
    "move": null,
    "stance": "offensive",
    "description": ""
  },
  {
    "id": "166",
    "name": "ADK60S Raven Interference Type",
    "score": 51,
    "structure": 0,
    "armor": 1,
    "parray": 0,
    "dodge": 7,
    "electronic": 3,
    "type": "medium",
    "move": null,
    "stance": "offensive",
    "description": ""
  },
  {
    "id": "167",
    "name": "SGM-2 Pholcus Automatic Mine (Unfolded)",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 2,
    "electronic": 2,
    "type": "small",
    "move": null,
    "stance": "offensive",
    "description": ""
  }
];

export const pdDrones: Drone[] = [
  {
    "id": "PRDR-101",
    "name": "MD-4A Reaper Type I",
    "type": "large",
    "score": 90,
    "structure": 4,
    "armor": 5,
    "parray": 0,
    "dodge": 0,
    "electronic": 3,
    "move": 6,
    "stance": "defensive",
    "description": "",
    "isPD": true, "projectile": [
      "PDAM-001"
    ]
  },
  {
    "id": "PRDR-102",
    "name": "MD-4C Reaper Type III",
    "type": "large",
    "score": 99,
    "structure": 4,
    "armor": 5,
    "parray": 0,
    "dodge": 0,
    "electronic": 3,
    "move": 6,
    "stance": "defensive",
    "description": "",
    "isPD": true, "projectile": [
      "PDAM-001"
    ]
  },
  {
    "id": "PRDR-103",
    "name": "MD-4D Reaper Type IV",
    "type": "large",
    "score": 105,
    "structure": 5,
    "armor": 6,
    "parray": 0,
    "dodge": 0,
    "electronic": 3,
    "move": 6,
    "stance": "defensive",
    "description": "",
    "isPD": true
  },
  {
    "id": "PRDR-104",
    "name": "MD-4B Reaper Type II",
    "type": "large",
    "score": 114,
    "structure": 5,
    "armor": 6,
    "parray": 0,
    "dodge": 0,
    "electronic": 3,
    "move": 6,
    "stance": "defensive",
    "description": "",
    "isPD": true
  },
  {
    "id": "PRDR-105",
    "name": "MD-4E Reaper  Engineer Type",
    "type": "large",
    "score": 90,
    "structure": 4,
    "armor": 5,
    "parray": 0,
    "dodge": 0,
    "electronic": 3,
    "move": 6,
    "stance": "defensive",
    "description": "",
    "isPD": true, "projectile": [
      "PDAM-003", "PDAM-004"
    ]
  },
  {
    "id": "PRDR-201",
    "name": "LD-5A Vigilant Autocannon Type",
    "type": "medium",
    "score": 48,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 4,
    "electronic": 2,
    "move": 6,
    "stance": "mobility",
    "description": "",
    "isPD": true
  },
  {
    "id": "PRDR-202",
    "name": "LD-5M Vigilant MG Type",
    "type": "medium",
    "score": 42,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 4,
    "electronic": 2,
    "move": 6,
    "stance": "mobility",
    "description": "",
    "isPD": true
  },
  {
    "id": "PRDR-203",
    "name": "LD-5B Vigilant Bombing Type",
    "type": "medium",
    "score": 45,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 4,
    "electronic": 2,
    "move": 6,
    "stance": "mobility",
    "description": "",
    "isPD": true, "projectile": [
      "PDAM-005"
    ]
  },
  {
    "id": "PRDR-204",
    "name": "LD-5S Vigilant Support Type",
    "type": "medium",
    "score": 48,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 4,
    "electronic": 2,
    "move": 6,
    "stance": "mobility",
    "description": "",
    "isPD": true, "projectile": [
      "PDAM-005", "PDAM-006"
    ]
  }
];

export const rdlPilots: Pilot[] = [
  {
    "id": "FPA-01",
    "name": " Misty",
    "score": 15,
    "LV": 4,
    "faction": "RDL",
    "swift": 7,
    "melee": 4,
    "projectile": 5,
    "firing": 3,
    "moving": 3,
    "tactic": 2,
    "trait": " Variation",
    "traitDescription": " · In Tactical Timing, may perform Starting Action from any timing."
  },
  {
    "id": "FPA-02",
    "name": " Spike",
    "score": 15,
    "LV": 4,
    "faction": "RDL",
    "swift": 3,
    "melee": 7,
    "projectile": 6,
    "firing": 2,
    "moving": 5,
    "tactic": 5,
    "trait": " Eagle-eye",
    "traitDescription": " · When performing Firing Action, gain Armor Piercing 1."
  },
  {
    "id": "FPA-03",
    "name": "Wu",
    "score": 12,
    "LV": 4,
    "faction": "RDL",
    "swift": 6,
    "melee": 2,
    "projectile": 3,
    "firing": 7,
    "moving": 4,
    "tactic": 4,
    "trait": "Fortitude",
    "traitDescription": "· Piloted Mech does not suffer reduced Link when a part is destroyed."
  },
  {
    "id": "FPA-04",
    "name": "Hammerhead",
    "score": 10,
    "LV": 4,
    "faction": "RDL",
    "swift": 4,
    "melee": 3,
    "projectile": 2,
    "firing": 5,
    "moving": 2,
    "tactic": 6,
    "trait": "Onslaught",
    "traitDescription": "· [Offensive Stance] Melee Action may exchange {Eye} for {Light Hit}."
  },
  {
    "id": "FPA-05",
    "name": "Anser",
    "score": 15,
    "LV": 4,
    "faction": "RDL",
    "swift": 5,
    "melee": 6,
    "projectile": 9,
    "firing": 3,
    "moving": 8,
    "tactic": 4,
    "trait": "Inexhaustible",
    "traitDescription": "· If the Chassis of the piloted mech has no Structure Value, consider as having 2 Structure Value."
  },
  {
    "id": "FPA-06",
    "name": "KeyHole",
    "score": 12,
    "LV": 4,
    "faction": "RDL",
    "swift": 2,
    "melee": 5,
    "projectile": 4,
    "firing": 6,
    "moving": 6,
    "tactic": 7,
    "trait": "Amplify",
    "traitDescription": "· Range of Aura, Electronic Attack and Electronic Support of the piloted mech +1 grid."
  },
  {
    "id": "FPA-09",
    "name": "Shock Troop-09",
    "score": 6,
    "LV": 4,
    "faction": "RDL",
    "swift": 6,
    "melee": 2,
    "projectile": 3,
    "firing": 7,
    "moving": 4,
    "tactic": 4,
    "trait": "",
    "traitDescription": "A new Shock Troop from Test and Evaluation Squadron 066"
  },
  {
    "id": "FPA-10",
    "name": "Shock Troop-10",
    "score": 6,
    "LV": 4,
    "faction": "RDL",
    "swift": 6,
    "melee": 2,
    "projectile": 3,
    "firing": 7,
    "moving": 4,
    "tactic": 4,
    "trait": "",
    "traitDescription": "A new Shock Troop from Test and Evaluation Squadron 066"
  },
  {
    "id": "FPA-11",
    "name": "Shock Troop-11",
    "score": 6,
    "LV": 4,
    "faction": "RDL",
    "swift": 6,
    "melee": 2,
    "projectile": 3,
    "firing": 7,
    "moving": 4,
    "tactic": 4,
    "trait": "",
    "traitDescription": "A new Shock Troop from Test and Evaluation Squadron 066"
  },
  {
    "id": "FPA-12",
    "name": "Shock Troop-12",
    "score": 6,
    "LV": 4,
    "faction": "RDL",
    "swift": 6,
    "melee": 2,
    "projectile": 3,
    "firing": 7,
    "moving": 4,
    "tactic": 4,
    "trait": "",
    "traitDescription": "A new Shock Troop from Test and Evaluation Squadron 066"
  },
  {
    "id": "FPA-13",
    "name": "Shock Troop-13",
    "score": 6,
    "LV": 4,
    "faction": "RDL",
    "swift": 6,
    "melee": 2,
    "projectile": 3,
    "firing": 7,
    "moving": 4,
    "tactic": 4,
    "trait": "",
    "traitDescription": "A new Shock Troop from Test and Evaluation Squadron 066"
  },
  {
    "id": "FPA-14",
    "name": "Scout-14",
    "score": 9,
    "LV": 4,
    "faction": "RDL",
    "swift": 5,
    "melee": 6,
    "projectile": 7,
    "firing": 4,
    "moving": 7,
    "tactic": 3,
    "trait": "",
    "traitDescription": "A new Scout from Test and Evaluation Squadron 066"
  },
  {
    "id": "FPA-15",
    "name": "Scout-15",
    "score": 9,
    "LV": 4,
    "faction": "RDL",
    "swift": 5,
    "melee": 6,
    "projectile": 7,
    "firing": 4,
    "moving": 7,
    "tactic": 3,
    "trait": "",
    "traitDescription": "A new Scout from Test and Evaluation Squadron 066"
  },
  {
    "id": "FPA-16",
    "name": "Scout-16",
    "score": 9,
    "LV": 4,
    "faction": "RDL",
    "swift": 5,
    "melee": 6,
    "projectile": 7,
    "firing": 4,
    "moving": 7,
    "tactic": 3,
    "trait": "",
    "traitDescription": "A new Scout from Test and Evaluation Squadron 066"
  },
  {
    "id": "FPA-17",
    "name": "Scout-17",
    "score": 9,
    "LV": 4,
    "faction": "RDL",
    "swift": 5,
    "melee": 6,
    "projectile": 7,
    "firing": 4,
    "moving": 7,
    "tactic": 3,
    "trait": "",
    "traitDescription": "A new Scout from Test and Evaluation Squadron 066"
  },
  {
    "id": "FPA-18",
    "name": "Scout-18",
    "score": 9,
    "LV": 4,
    "faction": "RDL",
    "swift": 5,
    "melee": 6,
    "projectile": 7,
    "firing": 4,
    "moving": 7,
    "tactic": 3,
    "trait": "",
    "traitDescription": "A new Scout from Test and Evaluation Squadron 066"
  },
  {
    "id": "FPA-06-2",
    "name": "KeyHole",
    "score": 12,
    "LV": 4,
    "faction": "RDL",
    "swift": 2,
    "melee": 5,
    "projectile": 4,
    "firing": 6,
    "moving": 6,
    "tactic": 7,
    "trait": "Hidden",
    "traitDescription": "·When piloted Mech is within range of allied Aura, gains Low Profile."
  }
];

export const unPilots: Pilot[] = [
  {
    "id": "LPA-19",
    "name": "Quartz",
    "score": 24,
    "LV": 4,
    "faction": "UN",
    "swift": 2,
    "melee": 5,
    "projectile": 4,
    "firing": 4,
    "moving": 6,
    "tactic": 6,
    "trait": " Calm",
    "traitDescription": "Recover 1 Link at the end of each round"
  },
  {
    "id": "LPA-20",
    "name": "Panzer",
    "score": 15,
    "LV": 4,
    "faction": "UN",
    "swift": 3,
    "melee": 3,
    "projectile": 2,
    "firing": 5,
    "moving": 2,
    "tactic": 6,
    "trait": "Block",
    "traitDescription": " · When Breaking Away from piloted mech, the Enemy Unit needs to consume 1 additional Move Range or 1 Link."
  },
  {
    "id": "LPA-21",
    "name": "Firefly",
    "score": 18,
    "LV": 4,
    "faction": "UN",
    "swift": 3,
    "melee": 7,
    "projectile": 6,
    "firing": 1,
    "moving": 5,
    "tactic": 5,
    "trait": " Stealth",
    "traitDescription": " · Piloted Mech's movement route may pass through other units when Optical Camouflage is on or in Low Profile."
  },
  {
    "id": "LPA-22",
    "name": "Yoyu",
    "score": 21,
    "LV": 4,
    "faction": "UN",
    "swift": 7,
    "melee": 4,
    "projectile": 5,
    "firing": 3,
    "moving": 4,
    "tactic": 1,
    "trait": " Provoke",
    "traitDescription": " · When Electronic Counter Roll is successful, may switch the Responder mech to Offensive Stance."
  },
  {
    "id": "LPA-23",
    "name": "Onyx",
    "score": 21,
    "LV": 4,
    "faction": "UN",
    "swift": 6,
    "melee": 2,
    "projectile": 3,
    "firing": 5,
    "moving": 4,
    "tactic": 4,
    "trait": " Chase",
    "traitDescription": " · When attacking a target with Fragile Token, may exchange {Eye} as {Heavy Hit}."
  },
  {
    "id": "LPA-24",
    "name": "Sealock",
    "score": 21,
    "LV": 4,
    "faction": "UN",
    "swift": 5,
    "melee": 4,
    "projectile": 8,
    "firing": 4,
    "moving": 7,
    "tactic": 3,
    "trait": " Chase",
    "traitDescription": " · When attacking a target with Fragile Token, may exchange {Eye} as {Heavy Hit}."
  },
  {
    "id": "LPA-27",
    "name": "Rifleman1",
    "score": 9,
    "LV": 4,
    "faction": "UN",
    "swift": 3,
    "melee": 7,
    "projectile": 6,
    "firing": 2,
    "moving": 5,
    "tactic": 5,
    "trait": "",
    "traitDescription": "Trainee Rifleman of 303 Squadron."
  },
  {
    "id": "LPA-28",
    "name": "Rifleman2",
    "score": 9,
    "LV": 4,
    "faction": "UN",
    "swift": 3,
    "melee": 7,
    "projectile": 6,
    "firing": 2,
    "moving": 5,
    "tactic": 5,
    "trait": "",
    "traitDescription": "Trainee Rifleman of 303 Squadron."
  },
  {
    "id": "LPA-29",
    "name": "Rifleman3",
    "score": 9,
    "LV": 4,
    "faction": "UN",
    "swift": 3,
    "melee": 7,
    "projectile": 6,
    "firing": 2,
    "moving": 5,
    "tactic": 5,
    "trait": "",
    "traitDescription": "Trainee Rifleman of 303 Squadron."
  },
  {
    "id": "LPA-30",
    "name": "Rifleman4",
    "score": 9,
    "LV": 4,
    "faction": "UN",
    "swift": 3,
    "melee": 7,
    "projectile": 6,
    "firing": 2,
    "moving": 5,
    "tactic": 5,
    "trait": "",
    "traitDescription": "Trainee Rifleman of 303 Squadron."
  },
  {
    "id": "LPA-31",
    "name": "Charger1",
    "score": 6,
    "LV": 4,
    "faction": "UN",
    "swift": 4,
    "melee": 3,
    "projectile": 2,
    "firing": 5,
    "moving": 2,
    "tactic": 6,
    "trait": "",
    "traitDescription": "Trainee Charger of 303 Squadron."
  },
  {
    "id": "LPA-32",
    "name": "Charger2",
    "score": 6,
    "LV": 4,
    "faction": "UN",
    "swift": 4,
    "melee": 3,
    "projectile": 2,
    "firing": 5,
    "moving": 2,
    "tactic": 6,
    "trait": "",
    "traitDescription": "Trainee Charger of 303 Squadron."
  },
  {
    "id": "LPA-33",
    "name": "Charger3",
    "score": 6,
    "LV": 4,
    "faction": "UN",
    "swift": 4,
    "melee": 3,
    "projectile": 2,
    "firing": 5,
    "moving": 2,
    "tactic": 6,
    "trait": "",
    "traitDescription": "Trainee Charger of 303 Squadron."
  },
  {
    "id": "LPA-34",
    "name": "Charger4",
    "score": 6,
    "LV": 4,
    "faction": "UN",
    "swift": 4,
    "melee": 3,
    "projectile": 2,
    "firing": 5,
    "moving": 2,
    "tactic": 6,
    "trait": "",
    "traitDescription": "Trainee Charger of 303 Squadron."
  },
  //  {
  //   "id": "LPA-66",
  //   "name": "Charger34",
  //   "score": 9,
  //   "LV": 4,
  //   "faction": "UN",
  //   "swift": 3,
  //   "melee": 7,
  //   "projectile": 6,
  //   "firing": 2,
  //   "moving": 5,
  //   "tactic": 5,
  //   "trait": "",
  //   "traitDescription": "Trainee Charger of 303 Squadron."
  // }
];

export const pdTorso: Part[] = [
  {
    "id": "287",
    "name": "ACE-001 White Dwarf Core Part",
    "type": "torso",
    "score": 72,
    "structure": 3,
    "armor": 5,
    "parray": 0,
    "dodge": 1,
    "electronic": 3,
    "description": "",
    "projectile": ["288"],
    "isPD": true
  }
];

export const pdChasis: Part[] = [
  {
    "id": "289",
    "name": "ACE-001 White Chassis Part",
    "type": "chasis",
    "score": 24,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 3,
    "electronic": 0,
    "description": "",
    "isPD": true
  }
];

export const pdLeftHand: Part[] = [{
  "id": "291",
  "name": "ACE-001 White Left Arm Part",
  "type": "leftHand",
  "score": 57,
  "structure": 0,
  "armor": 4,
  "parray": 0,
  "dodge": 0,
  "electronic": 0,
  "description": "",
  "isPD": true
}
];

export const pdRightHand: Part[] = [

  {
    "id": "290",
    "name": "ACE-001 White Right Arm Part",
    "type": "rightHand",
    "score": 72,
    "structure": 0,
    "armor": 4,
    "parray": 1,
    "dodge": 0,
    "electronic": 0,
    "description": "",
    "isPD": true
  }
];

export const pdBackpack: Part[] = [
  {
    "id": "292",
    "name": "ACE-001 White Left Bit Part",
    "type": "backpack",
    "score": 60,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 1,
    "electronic": 2,
    "description": "",
    "projectile": ["293", "294", "295"],
    "isPD": true
  }
];

export const pdPilots: Pilot[] = [
  {
    "id": "ACE-01",
    "name": "Karl·Fried",
    "score": 15,
    "LV": 4,
    "faction": "PD",
    "swift": 5,
    "melee": 7,
    "projectile": 6,
    "firing": 3,
    "moving": 8,
    "tactic": 6,
    "trait": "Synesthesia",
    "traitDescription": "· When a \"White Dwarf\" Bit performs a roll, it may consume Link from this Mech to re-roll."
  }
];

export const allTacticCards: TacticCard[] = [
  {
    "id": "274",
    "name": "Additional Command",
    "description": "",
    "score": 30
  },{
    "id": "275",
    "name": "Battlefield Recovery",
    "description": "",
    "score": 30
  },{
    "id": "276",
    "name": "Hit and Run",
    "description": "",
    "score": 30
  },{
    "id": "277",
    "name": "System Repair",
    "description": "",
    "score": 30
  },{
    "id": "278",
    "name": "Tactical Dispostion",
    "description": "",
    "score": 30
  },{
    "id": "279",
    "name": "Remote Restart",
    "description": "",
    "score": 30
  },
]