import { Part, Drone, Pilot } from './types';

export const pilots: Pilot[] = [
  {
    "id": "ZPA-35",
    "name": "大厨",
    "score": 15,
    "LV": 4,
    "faction": "GOF",
    "swift": 3,
    "melee": 4,
    "projectile": 4,
    "firing": 6,
    "moving": 6,
    "tactic": 7,
    "trait": "CQC",
    "traitDescription": "· 执行近战动作时，可以消耗1枚指令标记，将{眼睛}视为{重击}"
  },
  {
    "id": "ZPA-36",
    "name": "紫苑",
    "score": 12,
    "LV": 4,
    "faction": "GOF",
    "swift": 6,
    "melee": 4,
    "projectile": 5,
    "firing": 3,
    "moving": 3,
    "tactic": 4,
    "trait": "调整",
    "traitDescription": "· 每回合1次，指令阶段可以消耗1枚指令标记，为1台友军机甲恢复1点链接值。"
  },
  {
    "id": "ZPA-37",
    "name": "猎狐犬",
    "score": 15,
    "LV": 4,
    "faction": "GOF",
    "swift": 3,
    "melee": 7,
    "projectile": 6,
    "firing": 2,
    "moving": 5,
    "tactic": 5,
    "trait": "寻踪",
    "traitDescription": "· 如果有2台以上的己方无人机对目标有视线，本机在射击时无视低特征。"
  },
  {
    "id": "ZPA-38",
    "name": "护林员",
    "score": 15,
    "LV": 4,
    "faction": "GOF",
    "swift": 5,
    "melee": 6,
    "projectile": 7,
    "firing": 4,
    "moving": 7,
    "tactic": 3,
    "trait": "湿件优势",
    "traitDescription": "· 执行电子对抗投骰时，可消耗1点链接值，将{眼睛}视为{闪电}。"
  },
  {
    "id": "ZPA-39",
    "name": "丧尸",
    "score": 18,
    "LV": 4,
    "faction": "GOF",
    "swift": 4,
    "melee": 3,
    "projectile": 2,
    "firing": 5,
    "moving": 4,
    "tactic": 7,
    "trait": "求生意志",
    "traitDescription": "· 本机部件少于4时，本机的专注重投不消耗链接值。"
  },
  {
    "id": "ZPA-40",
    "name": "伯劳",
    "score": 12,
    "LV": 4,
    "faction": "GOF",
    "swift": 5,
    "melee": 2,
    "projectile": 3,
    "firing": 8,
    "moving": 4,
    "tactic": 4,
    "trait": "欢愉",
    "traitDescription": "· [攻击姿态]以近战动作摧毁敌军部件时，恢复1点链接值。"
  },
  {
    "id": "ZPA-43",
    "name": "游骑兵1",
    "score": 4,
    "LV": 4,
    "faction": "GOF",
    "swift": 2,
    "melee": 5,
    "projectile": 4,
    "firing": 6,
    "moving": 6,
    "tactic": 8,
    "trait": "nan",
    "traitDescription": "525中队的实习游骑兵。"
  },
  {
    "id": "ZPA-44",
    "name": "游骑兵2",
    "score": 4,
    "LV": 4,
    "faction": "GOF",
    "swift": 2,
    "melee": 5,
    "projectile": 4,
    "firing": 6,
    "moving": 6,
    "tactic": 8,
    "trait": "nan",
    "traitDescription": "525中队的实习游骑兵。"
  },
  {
    "id": "ZPA-45",
    "name": "游骑兵3",
    "score": 4,
    "LV": 4,
    "faction": "GOF",
    "swift": 2,
    "melee": 5,
    "projectile": 4,
    "firing": 6,
    "moving": 6,
    "tactic": 8,
    "trait": "nan",
    "traitDescription": "525中队的实习游骑兵。"
  },
  {
    "id": "ZPA-46",
    "name": "掷弹兵1",
    "score": 4,
    "LV": 4,
    "faction": "GOF",
    "swift": 8,
    "melee": 4,
    "projectile": 5,
    "firing": 3,
    "moving": 3,
    "tactic": 2,
    "trait": "nan",
    "traitDescription": "525中队的实习掷弹兵。"
  },
  {
    "id": "ZPA-47",
    "name": "掷弹兵2",
    "score": 4,
    "LV": 4,
    "faction": "GOF",
    "swift": 8,
    "melee": 4,
    "projectile": 5,
    "firing": 3,
    "moving": 3,
    "tactic": 2,
    "trait": "nan",
    "traitDescription": "525中队的实习掷弹兵。"
  },
  {
    "id": "ZPA-48",
    "name": "掷弹兵3",
    "score": 4,
    "LV": 4,
    "faction": "GOF",
    "swift": 8,
    "melee": 4,
    "projectile": 5,
    "firing": 3,
    "moving": 3,
    "tactic": 2,
    "trait": "nan",
    "traitDescription": "525中队的实习掷弹兵。"
  },
  {
    "id": "ZPA-49",
    "name": "掷弹兵4",
    "score": 4,
    "LV": 4,
    "faction": "GOF",
    "swift": 8,
    "melee": 4,
    "projectile": 5,
    "firing": 3,
    "moving": 3,
    "tactic": 2,
    "trait": "nan",
    "traitDescription": "525中队的实习掷弹兵。"
  },
  {
    "id": "nan",
    "name": "战斗员A-101",
    "score": 0,
    "LV": 5,
    "faction": "UN",
    "swift": 8,
    "melee": 4,
    "projectile": 5,
    "firing": 3,
    "moving": 3,
    "tactic": 2,
    "trait": "nan",
    "traitDescription": "为了使用LUKAS系统进行远程接入，战斗员的作战义体均装备了LK系列植入体。"
  },
  {
    "id": "nan",
    "name": "战斗员A-102",
    "score": 0,
    "LV": 5,
    "faction": "UN",
    "swift": 8,
    "melee": 4,
    "projectile": 5,
    "firing": 3,
    "moving": 3,
    "tactic": 2,
    "trait": "nan",
    "traitDescription": "搭载作战员和LUKAS的运输机通常作为空中支援，在战场上空盘旋，以获得最低的延迟。"
  },
  {
    "id": "nan",
    "name": "战斗员A-103",
    "score": 0,
    "LV": 5,
    "faction": "UN",
    "swift": 8,
    "melee": 4,
    "projectile": 5,
    "firing": 3,
    "moving": 3,
    "tactic": 2,
    "trait": "nan",
    "traitDescription": "虽然“工作就是工作”，但执行中队通常不会在短时间内切换合作方。"
  },
  {
    "id": "FPA-01",
    "name": "薄雾-01",
    "score": 0,
    "LV": 4,
    "faction": "UN",
    "swift": 7,
    "melee": 4,
    "projectile": 5,
    "firing": 3,
    "moving": 3,
    "tactic": 2,
    "trait": "变招",
    "traitDescription": "· 在战术时机，起手动作不限制时机类型。"
  },
  {
    "id": "FPA-02",
    "name": "长钉-02",
    "score": 0,
    "LV": 4,
    "faction": "UN",
    "swift": 3,
    "melee": 7,
    "projectile": 6,
    "firing": 2,
    "moving": 5,
    "tactic": 5,
    "trait": "鹰眼",
    "traitDescription": "· 执行射击动作时获得穿甲1。"
  },
  {
    "id": "FPA-03",
    "name": "无霜-03",
    "score": 0,
    "LV": 4,
    "faction": "UN",
    "swift": 6,
    "melee": 2,
    "projectile": 3,
    "firing": 7,
    "moving": 4,
    "tactic": 4,
    "trait": "坚毅",
    "traitDescription": "· 本机部件被摧毁时，不扣除链接值。"
  },
  {
    "id": "FPA-04",
    "name": "锤头鲨-04",
    "score": 0,
    "LV": 4,
    "faction": "UN",
    "swift": 4,
    "melee": 3,
    "projectile": 2,
    "firing": 5,
    "moving": 2,
    "tactic": 6,
    "trait": "猛攻",
    "traitDescription": "· 【攻击姿态】近战动作{眼睛}视为{轻击}。"
  },
  {
    "id": "FPA-05",
    "name": "灰雁-05",
    "score": 0,
    "LV": 4,
    "faction": "UN",
    "swift": 5,
    "melee": 6,
    "projectile": 9,
    "firing": 3,
    "moving": 8,
    "tactic": 4,
    "trait": "不竭",
    "traitDescription": "· 本机的下肢如果没有结构值，则视为拥有2点结构值。"
  },
  {
    "id": "FPA-06",
    "name": "锁眼-06",
    "score": 0,
    "LV": 4,
    "faction": "UN",
    "swift": 2,
    "melee": 5,
    "projectile": 4,
    "firing": 6,
    "moving": 6,
    "tactic": 7,
    "trait": "功率加大",
    "traitDescription": "· 本机的光环、电子攻击与电子支援，+1范围。"
  },
  {
    "id": "FPN-09",
    "name": "突击兵-09",
    "score": 0,
    "LV": 4,
    "faction": "UN",
    "swift": 6,
    "melee": 2,
    "projectile": 3,
    "firing": 7,
    "moving": 4,
    "tactic": 4,
    "trait": "nan",
    "traitDescription": "066测试中队的新晋突击兵。"
  },
  {
    "id": "FPN-10",
    "name": "突击兵-10",
    "score": 0,
    "LV": 4,
    "faction": "UN",
    "swift": 6,
    "melee": 2,
    "projectile": 3,
    "firing": 7,
    "moving": 4,
    "tactic": 4,
    "trait": "nan",
    "traitDescription": "066测试中队的新晋突击兵。"
  },
  {
    "id": "FPN-11",
    "name": "突击兵-11",
    "score": 0,
    "LV": 4,
    "faction": "UN",
    "swift": 6,
    "melee": 2,
    "projectile": 3,
    "firing": 7,
    "moving": 4,
    "tactic": 4,
    "trait": "nan",
    "traitDescription": "066测试中队的新晋突击兵。"
  },
  {
    "id": "FPN-12",
    "name": "突击兵-12",
    "score": 0,
    "LV": 4,
    "faction": "UN",
    "swift": 6,
    "melee": 2,
    "projectile": 3,
    "firing": 7,
    "moving": 4,
    "tactic": 4,
    "trait": "nan",
    "traitDescription": "066测试中队的新晋突击兵。"
  },
  {
    "id": "FPN-13",
    "name": "突击兵-13",
    "score": 0,
    "LV": 4,
    "faction": "UN",
    "swift": 6,
    "melee": 2,
    "projectile": 3,
    "firing": 7,
    "moving": 4,
    "tactic": 4,
    "trait": "nan",
    "traitDescription": "066测试中队的新晋突击兵。"
  },
  {
    "id": "FPN-14",
    "name": "侦察兵-14",
    "score": 0,
    "LV": 4,
    "faction": "UN",
    "swift": 5,
    "melee": 6,
    "projectile": 7,
    "firing": 4,
    "moving": 7,
    "tactic": 3,
    "trait": "nan",
    "traitDescription": "066测试中队的新晋侦察兵。"
  },
  {
    "id": "FPN-15",
    "name": "侦察兵-15",
    "score": 0,
    "LV": 4,
    "faction": "UN",
    "swift": 5,
    "melee": 6,
    "projectile": 7,
    "firing": 4,
    "moving": 7,
    "tactic": 3,
    "trait": "nan",
    "traitDescription": "066测试中队的新晋侦察兵。"
  },
  {
    "id": "FPN-16",
    "name": "侦察兵-16",
    "score": 0,
    "LV": 4,
    "faction": "UN",
    "swift": 5,
    "melee": 6,
    "projectile": 7,
    "firing": 4,
    "moving": 7,
    "tactic": 3,
    "trait": "nan",
    "traitDescription": "066测试中队的新晋侦察兵。"
  },
  {
    "id": "FPN-17",
    "name": "侦察兵-17",
    "score": 0,
    "LV": 4,
    "faction": "UN",
    "swift": 5,
    "melee": 6,
    "projectile": 7,
    "firing": 4,
    "moving": 7,
    "tactic": 3,
    "trait": "nan",
    "traitDescription": "066测试中队的新晋侦察兵。"
  },
  {
    "id": "FPN-18",
    "name": "侦察兵-18",
    "score": 0,
    "LV": 4,
    "faction": "UN",
    "swift": 5,
    "melee": 6,
    "projectile": 7,
    "firing": 4,
    "moving": 7,
    "tactic": 3,
    "trait": "nan",
    "traitDescription": "066测试中队的新晋侦察兵。"
  },
  {
    "id": "FPA-19",
    "name": "锁眼-06\n藏木于林",
    "score": 0,
    "LV": 4,
    "faction": "UN",
    "swift": 2,
    "melee": 5,
    "projectile": 4,
    "firing": 6,
    "moving": 6,
    "tactic": 7,
    "trait": "功率隐匿",
    "traitDescription": "· 本机处于友军光环范围内时获得低特征。"
  },
  {
    "id": "FPN-63",
    "name": "侦察兵-63",
    "score": 0,
    "LV": 4,
    "faction": "UN",
    "swift": 5,
    "melee": 6,
    "projectile": 7,
    "firing": 4,
    "moving": 7,
    "tactic": 3,
    "trait": "nan",
    "traitDescription": "066测试中队的新晋侦察兵。"
  },
  {
    "id": "FPA-04",
    "name": "锤头鲨-04\n内务能手",
    "score": 0,
    "LV": 4,
    "faction": "UN",
    "swift": 4,
    "melee": 3,
    "projectile": 2,
    "firing": 5,
    "moving": 2,
    "tactic": 6,
    "trait": "除虫",
    "traitDescription": "· 【攻击姿态】当本机获得行动机会时，可最多消耗1点链接值以获得1个动作时点。"
  },
  {
    "id": "LPA-19",
    "name": "石英",
    "score": 24,
    "LV": 4,
    "faction": "UN",
    "swift": 2,
    "melee": 5,
    "projectile": 4,
    "firing": 4,
    "moving": 6,
    "tactic": 6,
    "trait": "沉著",
    "traitDescription": "· 每回合结束时恢复1点链接值。"
  },
  {
    "id": "LPA-20",
    "name": "铠甲",
    "score": 15,
    "LV": 4,
    "faction": "UN",
    "swift": 3,
    "melee": 3,
    "projectile": 2,
    "firing": 5,
    "moving": 2,
    "tactic": 6,
    "trait": "阻拦",
    "traitDescription": "· 敌方单位脱离与本机的近战锁定时，需要额外消耗1格移动力，或者支付1点链接值。"
  },
  {
    "id": "LPA-21",
    "name": "鬼火",
    "score": 18,
    "LV": 4,
    "faction": "UN",
    "swift": 3,
    "melee": 7,
    "projectile": 6,
    "firing": 1,
    "moving": 5,
    "tactic": 5,
    "trait": "匿踪",
    "traitDescription": "· 当本机开启光学迷彩或处于低特征中时，本机的移动路径可穿越其他单位。"
  },
  {
    "id": "LPA-22",
    "name": "余裕",
    "score": 21,
    "LV": 4,
    "faction": "UN",
    "swift": 7,
    "melee": 4,
    "projectile": 5,
    "firing": 3,
    "moving": 4,
    "tactic": 1,
    "trait": "挑衅",
    "traitDescription": "· 当本机电子对抗投骰成功时，可使对方机甲切换为攻击姿态。"
  },
  {
    "id": "LPA-23",
    "name": "玉髓",
    "score": 21,
    "LV": 4,
    "faction": "UN",
    "swift": 6,
    "melee": 2,
    "projectile": 3,
    "firing": 5,
    "moving": 4,
    "tactic": 4,
    "trait": "不屈",
    "traitDescription": "· 本机可以碾压大体型单位。"
  },
  {
    "id": "LPA-24",
    "name": "峡湾",
    "score": 21,
    "LV": 4,
    "faction": "UN",
    "swift": 5,
    "melee": 4,
    "projectile": 8,
    "firing": 4,
    "moving": 7,
    "tactic": 3,
    "trait": "追击",
    "traitDescription": "· 攻击有脆弱标记的目标时，{眼睛}视为{重击}。"
  },
  {
    "id": "LPN-27",
    "name": "步枪手1",
    "score": 9,
    "LV": 4,
    "faction": "UN",
    "swift": 3,
    "melee": 7,
    "projectile": 6,
    "firing": 2,
    "moving": 5,
    "tactic": 5,
    "trait": "nan",
    "traitDescription": "303中队的实习步枪手。"
  },
  {
    "id": "LPN-28",
    "name": "步枪手2",
    "score": 9,
    "LV": 4,
    "faction": "UN",
    "swift": 3,
    "melee": 7,
    "projectile": 6,
    "firing": 2,
    "moving": 5,
    "tactic": 5,
    "trait": "nan",
    "traitDescription": "303中队的实习步枪手。"
  },
  {
    "id": "LPN-29",
    "name": "步枪手3",
    "score": 9,
    "LV": 4,
    "faction": "UN",
    "swift": 3,
    "melee": 7,
    "projectile": 6,
    "firing": 2,
    "moving": 5,
    "tactic": 5,
    "trait": "nan",
    "traitDescription": "303中队的实习步枪手。"
  },
  {
    "id": "LPN-30",
    "name": "步枪手4",
    "score": 9,
    "LV": 4,
    "faction": "UN",
    "swift": 3,
    "melee": 7,
    "projectile": 6,
    "firing": 2,
    "moving": 5,
    "tactic": 5,
    "trait": "nan",
    "traitDescription": "303中队的实习步枪手。"
  },
  {
    "id": "LPN-31",
    "name": "冲锋手1",
    "score": 6,
    "LV": 4,
    "faction": "UN",
    "swift": 4,
    "melee": 3,
    "projectile": 2,
    "firing": 5,
    "moving": 2,
    "tactic": 6,
    "trait": "nan",
    "traitDescription": "303中队的实习冲锋手。"
  },
  {
    "id": "LPN-32",
    "name": "冲锋手2",
    "score": 6,
    "LV": 4,
    "faction": "UN",
    "swift": 4,
    "melee": 3,
    "projectile": 2,
    "firing": 5,
    "moving": 2,
    "tactic": 6,
    "trait": "nan",
    "traitDescription": "303中队的实习冲锋手。"
  },
  {
    "id": "LPN-33",
    "name": "冲锋手3",
    "score": 6,
    "LV": 4,
    "faction": "UN",
    "swift": 4,
    "melee": 3,
    "projectile": 2,
    "firing": 5,
    "moving": 2,
    "tactic": 6,
    "trait": "nan",
    "traitDescription": "303中队的实习冲锋手。"
  },
  {
    "id": "LPN-34",
    "name": "冲锋手4",
    "score": 6,
    "LV": 4,
    "faction": "UN",
    "swift": 4,
    "melee": 3,
    "projectile": 2,
    "firing": 5,
    "moving": 2,
    "tactic": 6,
    "trait": "nan",
    "traitDescription": "303中队的实习冲锋手。"
  },
  {
    "id": "LPA-23",
    "name": "玉髓\n温柔和弦",
    "score": 24,
    "LV": 4,
    "faction": "UN",
    "swift": 6,
    "melee": 2,
    "projectile": 3,
    "firing": 5,
    "moving": 4,
    "tactic": 4,
    "trait": "装饰音",
    "traitDescription": "· 当本机执行射击动作时，如果目标处于3格内范围，本次射击动作+1Y。"
  }
];

export const drones: Drone[] = [
  {
    "id": "ZHDR-201",
    "name": "N31 猎犬I “猎兔犬”",
    "type": "medium",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "move": 5,
    "stance": "offensive",
    "description": "·曲射：本动作不需要对落点或目标有视线。\n·齐射X：发射或布撒最多X枚抛射物，并消耗同等数量的弹药标记。"
  },
  {
    "id": "ZHDR-202",
    "name": "N31 猎犬II “看门狗”",
    "type": "medium",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "move": 5,
    "stance": "offensive",
    "description": "nan"
  },
  {
    "id": "ZHDR-203",
    "name": "N31 猎犬III “斗牛犬”",
    "type": "medium",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "move": 5,
    "stance": "offensive",
    "description": "nan"
  },
  {
    "id": "ZHDR-303",
    "name": "N503 “女武神”",
    "type": "medium",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "move": 5,
    "stance": "offensive",
    "description": "·全向射击：本动作没有射界限制。\n·近战射击：在近战锁定中仍可执行本动作。"
  },
  {
    "id": "ZHDR-304",
    "name": "N504 “鹰身女妖”",
    "type": "medium",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "move": 5,
    "stance": "offensive",
    "description": "·全向射击：本动作没有射界限制。\n·近战射击：在近战锁定中仍可执行本动作。"
  },
  {
    "id": "ZHDR-101",
    "name": "N11 先锋I “塔盾”",
    "type": "medium",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "move": 5,
    "stance": "defensive",
    "description": "·自动盾牌：相邻的己方单位在遭受射击时，如果攻击者与目标的连线穿过本单位，则攻击变为以本机为目标。"
  },
  {
    "id": "ZHDR-102",
    "name": "N12 先锋II “十字弓”",
    "type": "medium",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "move": 5,
    "stance": "defensive",
    "description": "·全向射击：本动作没有射界限制。\n·近战射击：在近战锁定中仍可执行本动作。"
  },
  {
    "id": "ZHDR-103",
    "name": "N13 先锋III “阔剑”",
    "type": "medium",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "move": 5,
    "stance": "defensive",
    "description": "·全向射击：本动作没有射界限制。\n·近战射击：在近战锁定中仍可执行本动作。"
  },
  {
    "id": "ZHDR-104",
    "name": "N14 先锋IV “标枪”",
    "type": "medium",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "move": 5,
    "stance": "defensive",
    "description": "·曲射：本动作不需要对落点或目标有视线。"
  },
  {
    "id": "ZHDR-106",
    "name": "N113 神盾II “弩炮”",
    "type": "medium",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "move": 4,
    "stance": "offensive",
    "description": "·穿甲X：遭受本攻击时受击方减少X枚白骰。\n·近战射击：在近战锁定中仍可执行本动作。"
  },
  {
    "id": "ZHDR-107",
    "name": "N113 神盾III “冲角”",
    "type": "medium",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "move": 4,
    "stance": "offensive",
    "description": "·压制：被本动作宣布为目标的机甲会立刻切换为防御姿态（重启中单位不受此影响）。"
  },
  {
    "id": "ZHDR-301",
    "name": "N51 “护教者”",
    "type": "medium",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "move": 5,
    "stance": "defensive",
    "description": "·霰射：如果目标为机甲，溢出伤害结算至目标另1个随机部件。\n·击退X：本动作结束后，将目标沿攻击方向，强制移动X格。"
  },
  {
    "id": "ZHDR-302",
    "name": "N52 “狂热者”",
    "type": "medium",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "move": 5,
    "stance": "defensive",
    "description": "nan"
  },
  {
    "id": "ZHDR-204",
    "name": "N305 猎鹰I “迷雾鹰”",
    "type": "medium",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "move": 6,
    "stance": "mobility",
    "description": "nan"
  },
  {
    "id": "ZHDR-205",
    "name": "N306 猎鹰II “咆哮鹰”",
    "type": "medium",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "move": 6,
    "stance": "mobility",
    "description": "nan"
  },
  {
    "id": "ZHDR-206",
    "name": "N307 猎鹰III “巡逻鹰”",
    "type": "medium",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "move": 6,
    "stance": "mobility",
    "description": "· 静默：执行本动作时不会解除光学迷彩。"
  },
  {
    "id": "ZYDR-108",
    "name": "SU1 “护巢蜂”",
    "type": "medium",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "move": 0,
    "stance": "mobility",
    "description": "nan"
  },
  {
    "id": "PRDR-101",
    "name": "MD-4A \"收割者\"I型",
    "type": "medium",
    "score": 90,
    "structure": 0,
    "armor": 5,
    "parray": 0,
    "dodge": 0,
    "electronic": 3,
    "move": 6,
    "stance": "defensive",
    "description": "·曲射：本动作不需要对落点或目标有视线。\n·齐射X：发射或布撒最多X枚抛射物，并消耗同等数量的弹药标记。"
  },
  {
    "id": "PRDR-102",
    "name": "MD-4C \"收割者\"III型",
    "type": "medium",
    "score": 99,
    "structure": 0,
    "armor": 5,
    "parray": 0,
    "dodge": 0,
    "electronic": 3,
    "move": 6,
    "stance": "defensive",
    "description": "·曲射：本动作不需要对落点或目标有视线。\n·齐射X：发射或布撒最多X枚抛射物，并消耗同等数量的弹药标记。"
  },
  {
    "id": "PRDR-103",
    "name": "MD-4D \"收割者\"IV型",
    "type": "medium",
    "score": 105,
    "structure": 0,
    "armor": 6,
    "parray": 0,
    "dodge": 0,
    "electronic": 3,
    "move": 6,
    "stance": "defensive",
    "description": "nan"
  },
  {
    "id": "PRDR-104",
    "name": "MD-4B \"收割者\"II型",
    "type": "medium",
    "score": 114,
    "structure": 0,
    "armor": 6,
    "parray": 0,
    "dodge": 0,
    "electronic": 3,
    "move": 6,
    "stance": "defensive",
    "description": "nan"
  },
  {
    "id": "PRDR-105",
    "name": "MD-4E \"收割者\"工兵型",
    "type": "medium",
    "score": 90,
    "structure": 0,
    "armor": 5,
    "parray": 0,
    "dodge": 0,
    "electronic": 3,
    "move": 6,
    "stance": "defensive",
    "description": "·直射：本动作需要对落点或目标有视线。"
  },
  {
    "id": "PRDR-201",
    "name": "LD-5A \"警惕\"机炮型",
    "type": "medium",
    "score": 48,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 2,
    "move": 6,
    "stance": "mobility",
    "description": "·全向射击：本动作没有射界限制。\n·近战射击：在近战锁定中仍可执行本动作。\n·空中移动：本动作视为飞行。"
  },
  {
    "id": "PRDR-202",
    "name": "LD-5M \"警惕\"机枪型",
    "type": "medium",
    "score": 42,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 2,
    "move": 6,
    "stance": "mobility",
    "description": "·全向射击：本动作没有射界限制。\n·近战射击：在近战锁定中仍可执行本动作。\n·空中移动：本动作视为飞行。"
  },
  {
    "id": "PRDR-203",
    "name": "LD-5B \"警惕\"轰炸型",
    "type": "medium",
    "score": 45,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 2,
    "move": 6,
    "stance": "mobility",
    "description": "·曲射：本动作不需要对落点或目标有视线。\n·齐射X：发射或布撒最多X枚抛射物，并消耗同等数量的弹药标记。\n·空中移动：本动作视为飞行。"
  },
  {
    "id": "PRDR-204",
    "name": "LD-5S \"警惕\"支援型",
    "type": "medium",
    "score": 48,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 2,
    "move": 6,
    "stance": "mobility",
    "description": "·曲射：本动作不需要对落点或目标有视线。\n·齐射X：发射或布撒最多X枚抛射物，并消耗同等数量的弹药标记。\n·空中移动：本动作视为飞行。\n·直射：本动作需要对落点或目标有视线。"
  },
  {
    "id": "FXDR-101",
    "name": "DTG-30M “鬣狗”机枪型",
    "type": "medium",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "move": 5,
    "stance": "defensive",
    "description": "·全向射击：本动作没有射界限制。\n·近战射击：在近战锁定中仍可执行本动作。"
  },
  {
    "id": "FXDR-102",
    "name": "DTG-30S “鬣狗”导弹型",
    "type": "medium",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "move": 5,
    "stance": "defensive",
    "description": "·曲射：本动作不需要对落点或目标有视线。\n·齐射X：发射或布撒最多X枚抛射物，并消耗同等数量的弹药标记。"
  },
  {
    "id": "FXDR-103",
    "name": "DTG-30R “鬣狗”雷达型",
    "type": "medium",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "move": 5,
    "stance": "defensive",
    "description": "nan"
  },
  {
    "id": "nan",
    "name": "DTG-30Art  “鬣狗”涂装型",
    "type": "medium",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "move": 5,
    "stance": "defensive",
    "description": "nan"
  },
  {
    "id": "nan",
    "name": "MD-1 “蜻蜓”微型侦察机",
    "type": "medium",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "move": 0,
    "stance": "mobility",
    "description": "nan"
  },
  {
    "id": "LHDR-501",
    "name": "AMDS210“翠雀”自动防御系统",
    "type": "medium",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "move": 0,
    "stance": "offensive",
    "description": "nan"
  },
  {
    "id": "LHDR-301",
    "name": "ADK15D近防型豪猪",
    "type": "medium",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "move": 5,
    "stance": "defensive",
    "description": "·激光武器：命中使目标获得脆弱标记。\n·全向射击：本动作没有射界限制。\n·近战射击：在近战锁定中仍可执行本动作。"
  },
  {
    "id": "LHDR-302",
    "name": "ADK15/MAS 微波型豪猪",
    "type": "medium",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "move": 5,
    "stance": "defensive",
    "description": "nan"
  },
  {
    "id": "nan",
    "name": "ADK15P离子型豪猪",
    "type": "medium",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "move": 5,
    "stance": "defensive",
    "description": "·毁伤：溢出伤害可结算至结构值。\n·离子武器：命中拥有脆弱标记的目标时，{闪电}可视为{重击}。"
  },
  {
    "id": "nan",
    "name": "ADK15Art 涂装型豪猪",
    "type": "medium",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "move": 5,
    "stance": "defensive",
    "description": "nan"
  },
  {
    "id": "LHDR-102",
    "name": "ADK30C 运载型狼蛛",
    "type": "medium",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "move": 6,
    "stance": "mobility",
    "description": "nan"
  },
  {
    "id": "LHDR-101",
    "name": "ADK30F 火力型狼蛛",
    "type": "medium",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "move": 6,
    "stance": "mobility",
    "description": "·激光武器：命中使目标获得脆弱标记。\n·全向射击：本动作没有射界限制。\n·近战射击：在近战锁定中仍可执行本动作。"
  },
  {
    "id": "LHDR-201",
    "name": "ADK60R 侦查型渡鸦",
    "type": "medium",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "move": 0,
    "stance": "mobility",
    "description": "nan"
  },
  {
    "id": "LHDR-202",
    "name": "ADK60EC 电战型渡鸦",
    "type": "medium",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "move": 0,
    "stance": "mobility",
    "description": "· 中继器：范围内友军单位在进行电子攻击或电子支援时，可以本机作为出发点。"
  },
  {
    "id": "LHDR-203",
    "name": "ADK60S 干扰型渡鸦",
    "type": "medium",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "move": 0,
    "stance": "mobility",
    "description": "nan"
  },
  {
    "id": "LHDR-401",
    "name": "SGM2“幽灵蛛”自行地雷(展开）",
    "type": "medium",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "move": 1,
    "stance": "mobility",
    "description": "nan"
  }
];

export const parts: Part[] = [
  {
    "id": "ZYTR-101",
    "name": "P7\n“勇士”\n主战核心",
    "type": "torso",
    "score": 76,
    "structure": 3,
    "armor": 5,
    "parray": 0,
    "dodge": 0,
    "electronic": 3,
    "description": "·指令生成X：指令阶段开始时，本机自动生成X枚指令标记。\n· 指令协调X：本动作执行结束后，可以立即向X台己方无人机发送1枚指令标记。 "
  },
  {
    "id": "ZYTR-102",
    "name": "P7-A3\n“百夫长”\n节点核心",
    "type": "torso",
    "score": 79,
    "structure": 3,
    "armor": 5,
    "parray": 0,
    "dodge": 0,
    "electronic": 3,
    "description": "·指令生成X：指令阶段开始时，本机自动生成X枚指令标记。"
  },
  {
    "id": "ZYTR-201",
    "name": "P22\n“猎人”\n电战核心",
    "type": "torso",
    "score": 91,
    "structure": 4,
    "armor": 5,
    "parray": 0,
    "dodge": 0,
    "electronic": 4,
    "description": "·指令生成X：指令阶段开始时，本机自动生成X枚指令标记。"
  },
  {
    "id": "ZYTR-301",
    "name": "P28\n“龙骑兵”\n重甲核心",
    "type": "torso",
    "score": 97,
    "structure": 4,
    "armor": 5,
    "parray": 0,
    "dodge": 0,
    "electronic": 2,
    "description": "·指令生成X：指令阶段开始时，本机自动生成X枚指令标记。"
  },
  {
    "id": "ZYTR-302",
    "name": "P24\n“战车”\n重甲核心",
    "type": "torso",
    "score": 94,
    "structure": 4,
    "armor": 5,
    "parray": 0,
    "dodge": 0,
    "electronic": 2,
    "description": "·指令生成X：指令阶段开始时，本机自动生成X枚指令标记。"
  },
  {
    "id": "ZHLT-101",
    "name": "PL1\n标准下肢",
    "type": "chasis",
    "score": 37,
    "structure": 5,
    "armor": 1,
    "parray": 0,
    "dodge": 3,
    "electronic": 0,
    "description": "nan"
  },
  {
    "id": "ZHLT-201",
    "name": "PL29\n隐秘下肢",
    "type": "chasis",
    "score": 61,
    "structure": 5,
    "armor": 1,
    "parray": 0,
    "dodge": 4,
    "electronic": 0,
    "description": "·静默：不会解除光学迷彩。"
  },
  {
    "id": "ZHLT-301",
    "name": "PLK400\n“半人马”\n高速下肢",
    "type": "chasis",
    "score": 90,
    "structure": 3,
    "armor": 5,
    "parray": 0,
    "dodge": 3,
    "electronic": 0,
    "description": "`不可阻挡：本动作在禁足状态下也可以移动\n·异形X：执行本动作时，需要消耗X点链接值。\n·推动X：将目标沿本单位面朝方向，强制直线移动X格，然后本单位执行同样的移动。"
  },
  {
    "id": "ZHLT-302",
    "name": "PL35\n重甲下肢",
    "type": "chasis",
    "score": 64,
    "structure": 2,
    "armor": 6,
    "parray": 0,
    "dodge": 3,
    "electronic": 0,
    "description": "·推动X：将目标沿本单位面朝方向，强制直线移动X格，然后本单位执行同样的移动。"
  },
  {
    "id": "ZHLA-101",
    "name": "SS12圆盾",
    "type": "leftHand",
    "score": 0,
    "structure": 5,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "ZHRA-101",
    "name": "MR14磁轨步枪",
    "type": "rightHand",
    "score": 0,
    "structure": 4,
    "armor": 1,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "ZHRA-101",
    "name": "MR14磁轨步枪（抛弃卡）",
    "type": "rightHand",
    "score": 0,
    "structure": 4,
    "armor": 1,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "ZHLA-102",
    "name": "双联“雨燕”发射器",
    "type": "leftHand",
    "score": 0,
    "structure": 4,
    "armor": 1,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "ZHLA-102",
    "name": "双联“雨燕”发射器（抛弃卡）",
    "type": "leftHand",
    "score": 0,
    "structure": 4,
    "armor": 1,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "ZHRA-102",
    "name": "MR16磁轨步枪",
    "type": "rightHand",
    "score": 0,
    "structure": 4,
    "armor": 1,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "ZHRA-102",
    "name": "MR16磁轨步枪（抛弃卡）",
    "type": "rightHand",
    "score": 0,
    "structure": 4,
    "armor": 1,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "ZHRA-103",
    "name": "M115长矛",
    "type": "rightHand",
    "score": 0,
    "structure": 4,
    "armor": 1,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "ZHRA-103",
    "name": "M115长矛（抛弃卡）",
    "type": "rightHand",
    "score": 0,
    "structure": 4,
    "armor": 1,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "ZHLA-201",
    "name": "GSD7迫击炮",
    "type": "leftHand",
    "score": 0,
    "structure": 4,
    "armor": 1,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "ZHLA-201",
    "name": "GSD7迫击炮（抛弃卡）",
    "type": "leftHand",
    "score": 0,
    "structure": 4,
    "armor": 1,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "ZHRA-201",
    "name": "MR21磁轨步枪",
    "type": "rightHand",
    "score": 0,
    "structure": 4,
    "armor": 1,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "ZHRA-201",
    "name": "MR21磁轨步枪（抛弃卡）",
    "type": "rightHand",
    "score": 0,
    "structure": 4,
    "armor": 1,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "ZHLA-202",
    "name": "M4格斗爪",
    "type": "leftHand",
    "score": 0,
    "structure": 5,
    "armor": 1,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "ZHRA-202",
    "name": "MR24磁轨步枪",
    "type": "rightHand",
    "score": 0,
    "structure": 4,
    "armor": 1,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "ZHRA-202",
    "name": "MR24磁轨步枪（抛弃卡）",
    "type": "rightHand",
    "score": 0,
    "structure": 4,
    "armor": 1,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "ZHLA-301",
    "name": "SS30重盾",
    "type": "leftHand",
    "score": 0,
    "structure": 5,
    "armor": 6,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "ZHLA-301",
    "name": "SS30重盾（抛弃卡）",
    "type": "leftHand",
    "score": 0,
    "structure": 5,
    "armor": 1,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "ZHRA-301",
    "name": "M100长枪",
    "type": "rightHand",
    "score": 0,
    "structure": 5,
    "armor": 1,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "ZHRA-301",
    "name": "M100长枪（抛弃卡）",
    "type": "rightHand",
    "score": 0,
    "structure": 5,
    "armor": 1,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "ZHLA-302",
    "name": "MR870霰弹枪",
    "type": "leftHand",
    "score": 0,
    "structure": 5,
    "armor": 1,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "ZHLA-302",
    "name": "MR870霰弹枪（抛弃卡）",
    "type": "leftHand",
    "score": 0,
    "structure": 5,
    "armor": 1,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "ZHLA-303",
    "name": "辅助左臂",
    "type": "leftHand",
    "score": 0,
    "structure": 5,
    "armor": 1,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "ZHRA-303",
    "name": "M105长戟",
    "type": "rightHand",
    "score": 0,
    "structure": 4,
    "armor": 1,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "ZHRA-303",
    "name": "M105长戟（抛弃卡）",
    "type": "rightHand",
    "score": 0,
    "structure": 4,
    "armor": 1,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "ZHLA-304",
    "name": "MH-K1热能重剑（左）",
    "type": "leftHand",
    "score": 0,
    "structure": 5,
    "armor": 1,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "ZHLA-304",
    "name": "MH-K1热能重剑（左）（抛弃卡）",
    "type": "leftHand",
    "score": 0,
    "structure": 5,
    "armor": 1,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "ZHRA-304",
    "name": "MH-K1热能重剑（右）",
    "type": "rightHand",
    "score": 0,
    "structure": 5,
    "armor": 1,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "ZHRA-304",
    "name": "MH-K1热能重剑（右）（抛弃卡）",
    "type": "rightHand",
    "score": 0,
    "structure": 5,
    "armor": 1,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "ZYBP-101",
    "name": "DLSP蜂群控制包",
    "type": "backpack",
    "score": 0,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 1,
    "electronic": 0,
    "description": "nan"
  },
  {
    "id": "ZYBP-102",
    "name": "集成数据链吊舱",
    "type": "backpack",
    "score": 0,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 1,
    "electronic": 0,
    "description": "· 指令协调X：在本机此次行动结束后，可以立即为X台己方无人机各提供1枚指令标记。"
  },
  {
    "id": "ZYBP-201",
    "name": "CSS20“披风”光学迷彩系统",
    "type": "backpack",
    "score": 0,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 1,
    "electronic": 0,
    "description": "·光学迷彩：将本机替换为光学迷彩模型，并移除所有高亮目标/低特征标记。\n· 隐秘X：光学迷彩解除时，本机在X格范围内现身。"
  },
  {
    "id": "ZYBP-202",
    "name": "ECP9“鹰哨”无人机指挥系统",
    "type": "backpack",
    "score": 0,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 1,
    "electronic": 0,
    "description": "nan"
  },
  {
    "id": "ZYBP-301",
    "name": "MCP7“回旋镖”携带包",
    "type": "backpack",
    "score": 0,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 1,
    "electronic": 0,
    "description": "·曲射：本动作不需要对落点或目标有视线。"
  },
  {
    "id": "ZYBP-302",
    "name": "“光环”近战协作系统",
    "type": "backpack",
    "score": 0,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 1,
    "electronic": 0,
    "description": "nan"
  },
  {
    "id": "PDTR-101",
    "name": "H2-A“危机”I型",
    "type": "torso",
    "score": 69,
    "structure": 3,
    "armor": 5,
    "parray": 0,
    "dodge": 0,
    "electronic": 2,
    "description": "nan"
  },
  {
    "id": "PDTR-102",
    "name": "H2-B“危机”II型",
    "type": "torso",
    "score": 72,
    "structure": 3,
    "armor": 5,
    "parray": 0,
    "dodge": 0,
    "electronic": 2,
    "description": "nan"
  },
  {
    "id": "PDLT-101",
    "name": "HL2\n“危机”下肢",
    "type": "chasis",
    "score": 0,
    "structure": 0,
    "armor": 5,
    "parray": 0,
    "dodge": 3,
    "electronic": 0,
    "description": "nan"
  },
  {
    "id": "PDLT-102",
    "name": "HL2-M\n“危机”下肢M",
    "type": "chasis",
    "score": 0,
    "structure": 0,
    "armor": 5,
    "parray": 0,
    "dodge": 3,
    "electronic": 0,
    "description": "nan"
  },
  {
    "id": "PDLA-101",
    "name": "Ls197R机炮（左）",
    "type": "leftHand",
    "score": 0,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "PDRA-101",
    "name": "Ls197R机炮（右）",
    "type": "rightHand",
    "score": 0,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "PDLA-102",
    "name": "Ot41激光压制系统+Sd3盾牌",
    "type": "leftHand",
    "score": 0,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "PDRA-102",
    "name": "Ot50-ADS+Sd3盾牌",
    "type": "rightHand",
    "score": 0,
    "structure": 0,
    "armor": 4,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "PDBP-101",
    "name": "四联装“飞鱼”发射器",
    "type": "backpack",
    "score": 0,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": "·曲射：本动作不需要对落点或目标有视线。\n·齐射X：发射或布撒最多X枚抛射物，并消耗同等数量的弹药标记。"
  },
  {
    "id": "PDBP-102",
    "name": "Ls297双联机炮",
    "type": "backpack",
    "score": 0,
    "structure": 0,
    "armor": 3,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": "·压制：被本动作宣布为目标的机甲会立刻切换为防御姿态（处于宕机姿态的单位不受此影响）。"
  },
  {
    "id": "FXTR-101",
    "name": "RT-06\n “泥沼”\n 主战核心",
    "type": "torso",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": "nan"
  },
  {
    "id": "FXTR-102-B",
    "name": "RT-07T\n “沙丘”\n 战术核心",
    "type": "torso",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": "·灵活时机：本动作可在相邻时机作为起手动作，如一个拥有本关键词的移动动作，可以在射击/移动/战术时机作为起手动作。"
  },
  {
    "id": "FXTR-201",
    "name": "RT-08\n “雷暴”\n 炮战核心",
    "type": "torso",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": "·额外射击时点：此时点只能在一次行动机会的最后使用，只能用于射击，但可以执行本行动机会中已使用过的动作。\n·击退X：本动作结束后，将目标沿攻击方向，强制移动X格。"
  },
  {
    "id": "FXTR-202",
    "name": "RT-09A\n “火山”\n 重甲核心",
    "type": "torso",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": "·指定X：在任何削减骰子数量的宣布之后，可以设定X枚骰子的结果。\n被指定的骰子不参与投骰，也无法被任何一方重投。\n·直射：本动作需要对落点或目标有视线。"
  },
  {
    "id": "FXTR-301",
    "name": "RT-15B\n “熔岩”\n 突击核心",
    "type": "torso",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": "·直射：本动作需要对落点或目标有视线。"
  },
  {
    "id": "FXTR-303U",
    "name": "RT-15C\n “冰川”\n 突击核心",
    "type": "torso",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": "·额外射击时点：此时点只能在一次行动机会的最后使用，只能用于射击，但可以执行本行动机会中已使用过的动作。\n·直射：本动作需要对落点或目标有视线。"
  },
  {
    "id": "FXTR-302",
    "name": "RT-15/EC\n “极光”\n 电战核心",
    "type": "torso",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": "·电战节点X：范围内友军在进行电子对抗投骰时，可以使用本机的电子值+X。"
  },
  {
    "id": "FMTR-401L",
    "name": "RT-09M\n “火山M”\n 重甲核心",
    "type": "torso",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": "·指定X：在任何削减骰子数量的宣布之后，可以设定X枚骰子的结果。\n被指定的骰子不参与投骰，也无法被任何一方重投。\n·直射：本动作需要对落点或目标有视线。"
  },
  {
    "id": "FMTR-402L",
    "name": "RT-09M II\n “火山M II”\n 重甲核心",
    "type": "torso",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": "·指定X：在任何削减骰子数量的宣布之后，可以设定X枚骰子的结果。\n被指定的骰子不参与投骰，也无法被任何一方重投。\n·直射：本动作需要对落点或目标有视线。"
  },
  {
    "id": "FMTR-304",
    "name": "RT-16B\n “雪崩”\n 突击核心",
    "type": "torso",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": "·直射：本动作需要对落点或目标有视线。"
  },
  {
    "id": "FMTR-305",
    "name": "RT-15/S\n “光轮”\n 支援核心",
    "type": "torso",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": "nan"
  },
  {
    "id": "FMTR-103",
    "name": "RT-06E\n “泥沼E”\n 主战核心",
    "type": "torso",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": "nan"
  },
  {
    "id": "nan",
    "name": "RTX-06SR\n“泥沼SR”主战核心",
    "type": "torso",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": "nan"
  },
  {
    "id": "FXLT-101",
    "name": "RL-06\n 标准下肢",
    "type": "chasis",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": "nan"
  },
  {
    "id": "FXLT-201-A",
    "name": "RL-08\n 重甲下肢",
    "type": "chasis",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": "nan"
  },
  {
    "id": "FXLT-301",
    "name": "RL-03D\n “快马”高速下肢",
    "type": "chasis",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": "nan"
  },
  {
    "id": "FXLT-201-A",
    "name": "RL-08M\n 重甲下肢",
    "type": "chasis",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": "nan"
  },
  {
    "id": "FXLT-401",
    "name": "RL-08M II 重甲下肢",
    "type": "chasis",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": "nan"
  },
  {
    "id": "nan",
    "name": "RL-06M\n 标准下肢",
    "type": "chasis",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": "nan"
  },
  {
    "id": "nan",
    "name": "RL-06MS\n 辅助下肢",
    "type": "chasis",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": "nan"
  },
  {
    "id": "nan",
    "name": "RL-08C\n 重甲下肢",
    "type": "chasis",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": "nan"
  },
  {
    "id": "FXLA-101",
    "name": "55型轻盾 + CC-6格斗刀",
    "type": "leftHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "FXLA-101",
    "name": "55型轻盾 + CC-6格斗刀（弃置）",
    "type": "leftHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "FXRA-101",
    "name": "AC-32自动步枪",
    "type": "rightHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "FXRA-101",
    "name": "AC-32自动步枪（弃置）",
    "type": "rightHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "FXRA-106U",
    "name": "AC-32M射手步枪",
    "type": "rightHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "FXRA-106U",
    "name": "AC-32M射手步枪（弃置）",
    "type": "rightHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "FXLA-102",
    "name": "ML-32双联发射器 + CC-3格斗刀",
    "type": "leftHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "FXRA-102",
    "name": "AC-150重型机枪",
    "type": "rightHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "FXRA-102",
    "name": "AC-150重型机枪（弃置）",
    "type": "rightHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "FXLA-103",
    "name": "R-20肩置磁轨炮（左）",
    "type": "leftHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "FXRA-103",
    "name": "R-20肩置磁轨炮（右）",
    "type": "rightHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "FXLA-104",
    "name": "77型重型盾牌",
    "type": "leftHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "FXLA-104",
    "name": "77型重型盾牌（弃置）",
    "type": "leftHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "FXRA-104",
    "name": "CC-4战斗刀（右）",
    "type": "rightHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "FXLA-105K",
    "name": "CC-4战斗刀（左）",
    "type": "leftHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "FXRA-106SE",
    "name": "ACX-350“积雨云”原型重机枪",
    "type": "rightHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "FXRA-106SE",
    "name": "ACX-350“积雨云”原型重机枪（弃置）",
    "type": "rightHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "FXLA-106SE",
    "name": "SPHX-3重武器支持手",
    "type": "leftHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "FXLA-201",
    "name": "L-320肩部机枪 + CC-6格斗刀",
    "type": "leftHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "FXLA-201",
    "name": "L-320肩部机枪 + CC-6格斗刀（弃置）",
    "type": "leftHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "FXRA-201",
    "name": "R-35重型磁轨炮",
    "type": "rightHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "FXRA-201",
    "name": "R-35重型磁轨炮（弃置）",
    "type": "rightHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "FXLA-202",
    "name": "79型战斗盾牌",
    "type": "leftHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "FXRA-202",
    "name": "55型轻盾 + PC-9霰弹枪（右）",
    "type": "rightHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "FXRA-202",
    "name": "55型轻盾 + PC-9霰弹枪（右）（弃置）",
    "type": "rightHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "FXRA-206G",
    "name": "55型轻盾 + PC-9霰弹枪 + 烟幕弹（右）",
    "type": "rightHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "FXRA-206G",
    "name": "55型轻盾 + PC-9霰弹枪 + 烟幕弹（右）（弃置）",
    "type": "rightHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "FXLA-203",
    "name": "FCC-12 “大手” 格斗系统",
    "type": "leftHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "FXRA-203",
    "name": "L-320肩部机枪 + CC-90重格斗刀",
    "type": "rightHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "FXRA-203",
    "name": "L-320肩部机枪 + CC-90重格斗刀 （弃置）",
    "type": "rightHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "FXLA-204",
    "name": "55型轻盾 + PC-9霰弹枪（左）",
    "type": "leftHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "FXLA-204",
    "name": "55型轻盾 + PC-9霰弹枪（左）（弃置）",
    "type": "leftHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "FXRA-204",
    "name": "CC-100“力士”链锤",
    "type": "rightHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "FXLA-301",
    "name": "G/AC-6火箭筒",
    "type": "leftHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "FXLA-301",
    "name": "G/AC-6火箭筒（弃置）",
    "type": "leftHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "FXRA-301",
    "name": "AC-39战术步枪",
    "type": "rightHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "FXRA-301",
    "name": "AC-39战术步枪（弃置）",
    "type": "rightHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "FXLA-302",
    "name": "62型臂盾 + CC-20单手剑（左）",
    "type": "leftHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "FXRA-302",
    "name": "63型臂炮 + CC-20单手剑（右）",
    "type": "rightHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "FXLA-303",
    "name": "55型轻盾 + MES信标发射器",
    "type": "leftHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "FXLA-303",
    "name": "55型轻盾+\n MES信标发射器\n （弃置）",
    "type": "leftHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "FXRA-303",
    "name": "AC-161冲锋枪",
    "type": "rightHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "FXRA-303",
    "name": "AC-161冲锋枪（弃置）",
    "type": "rightHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "FMLA-401L",
    "name": "77型重盾（早期型）",
    "type": "leftHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "FMLA-401LA",
    "name": "77型重盾早期型（弃置）",
    "type": "leftHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "FMRA-401L",
    "name": "L-320肩部机枪 + CC-90重型格斗刀早期型",
    "type": "rightHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "FMRA-401LA",
    "name": "L-320肩部机枪 + CC-90重型格斗刀早期型（弃置）",
    "type": "rightHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "nan",
    "name": "L-330肩部机枪 + 77B型重盾",
    "type": "leftHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "nan",
    "name": "L-330肩部机枪 + 77B型重盾（弃置）",
    "type": "leftHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "nan",
    "name": "L-330肩部机枪 + CC-85岩锯",
    "type": "rightHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "nan",
    "name": "L-330肩部机枪 + CC-85岩锯（弃置）",
    "type": "rightHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "nan",
    "name": "55型轻盾 + PC-9K霰弹枪（右）",
    "type": "rightHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "nan",
    "name": "55型轻盾 + PC-9K霰弹枪（右）（弃置）",
    "type": "rightHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "nan",
    "name": "55型轻盾 + PC-9K霰弹枪（左）",
    "type": "leftHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "nan",
    "name": "55型轻盾 + PC-9K霰弹枪（左）（弃置）",
    "type": "leftHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "nan",
    "name": "AH-21手枪 + CC-50打桩机 （右）",
    "type": "rightHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "nan",
    "name": "AH-21手枪 + CC-50打桩机 （右）（弃置）",
    "type": "rightHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "nan",
    "name": "AH-21手枪 + CC-50打桩机 （左）",
    "type": "leftHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "nan",
    "name": "AH-21手枪 + CC-50打桩机 （左）（弃置）",
    "type": "leftHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "nan",
    "name": "AC-35狙击步枪",
    "type": "rightHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "nan",
    "name": "AC-35狙击步枪（弃置）",
    "type": "rightHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "nan",
    "name": "AC-32C自动步枪",
    "type": "rightHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "nan",
    "name": "AC-32C自动步枪（弃置）",
    "type": "rightHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "nan",
    "name": "55型轻盾",
    "type": "leftHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "nan",
    "name": "CC-7战斗刀（左）",
    "type": "leftHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "nan",
    "name": "PC-6霰弹枪",
    "type": "rightHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "nan",
    "name": "PC-6霰弹枪（弃置）",
    "type": "rightHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "nan",
    "name": "[金汤力]小奖赛奖杯",
    "type": "rightHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "nan",
    "name": "ML-32B双联发射器 + CC-3格斗刀",
    "type": "leftHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "FXBP-101",
    "name": "SH-15战场修复系统",
    "type": "backpack",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": "nan"
  },
  {
    "id": "FXBP-102",
    "name": "ECS-2外置冷却器",
    "type": "backpack",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": "nan"
  },
  {
    "id": "FXBP-103",
    "name": "AMS-190主动防御系统",
    "type": "backpack",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": "nan"
  },
  {
    "id": "FXBP-104",
    "name": "ML-34四联导弹包",
    "type": "backpack",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": "·曲射：本动作不需要对落点或目标有视线。\n·齐射X：发射或布撒最多X枚抛射物，并消耗同等数量的弹药标记。"
  },
  {
    "id": "FXBP-105SE",
    "name": "LGP-80长程火炮",
    "type": "backpack",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": "·毁伤：溢出伤害可结算至结构值。"
  },
  {
    "id": "FXBP-201",
    "name": "GLP-15布雷包",
    "type": "backpack",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": "·直射：本动作需要对落点或目标有视线。"
  },
  {
    "id": "FXBP-202",
    "name": "MUD-1“泥浆”电子战背包",
    "type": "backpack",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": "nan"
  },
  {
    "id": "FXBP-203",
    "name": "CP-3信标携带包",
    "type": "backpack",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": "·直射：本动作需要对落点或目标有视线。\n·投掷：执行本动作时必须指定一个空手。"
  },
  {
    "id": "FXBP-301",
    "name": "MUE/N-20“回响”支援背包",
    "type": "backpack",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": "nan"
  },
  {
    "id": "FXBP-302",
    "name": "TB-600跳跃背包",
    "type": "backpack",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": "· 空中移动：本动作视为飞行。"
  },
  {
    "id": "FXBP-303",
    "name": "ML-92双联导弹包",
    "type": "backpack",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": "·曲射：本动作不需要对落点或目标有视线。\n·齐射X：发射或布撒最多X枚抛射物，并消耗同等数量的弹药标记。"
  },
  {
    "id": "FMBP-401L",
    "name": "AMS-192主动防御系统",
    "type": "backpack",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": "nan"
  },
  {
    "id": "FMBP-402L",
    "name": "AMS-193主动防御系统",
    "type": "backpack",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": "nan"
  },
  {
    "id": "nan",
    "name": "HD-2数据携带包",
    "type": "backpack",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": "nan"
  },
  {
    "id": "nan",
    "name": "ML-94四联导弹包",
    "type": "backpack",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": "·曲射：本动作不需要对落点或目标有视线。\n·齐射X：发射或布撒最多X枚抛射物，并消耗同等数量的弹药标记。"
  },
  {
    "id": "nan",
    "name": "CP-4无人机携带包",
    "type": "backpack",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": "·直射：本动作需要对落点或目标有视线。\n·投掷：执行本动作时必须指定一个空手。"
  },
  {
    "id": "nan",
    "name": "ECS-3外置冷却器",
    "type": "backpack",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": "nan"
  },
  {
    "id": "LHTR-101",
    "name": "TM31C\n“灰狼”\n主战核心",
    "type": "torso",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": "·曲射：本动作不需要对落点或目标有视线。"
  },
  {
    "id": "LHTR-102",
    "name": "TM31R\n“薮猫”\n主战核心",
    "type": "torso",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": "nan"
  },
  {
    "id": "LHTR-201",
    "name": "TM39\n“蝮蛇”\n低征核心",
    "type": "torso",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": "·低特征：拥有低特征单位遭受射击时，受击骰结果中的{眼睛}可视为{闪避}。\n· 静默：执行本动作时不会解除光学迷彩与低特征。"
  },
  {
    "id": "LHTR-202",
    "name": "TM641\n“章鱼”\n隐秘核心",
    "type": "torso",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": "· 隐秘X：光学迷彩解除时，本机在X格范围内现身。\n· 静默：执行本动作时不会解除光学迷彩与低特征。"
  },
  {
    "id": "LHTR-301",
    "name": "TM35N\n“短吻鳄”\n电战核心",
    "type": "torso",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": "· 静默：执行本动作时不会解除光学迷彩与低特征。\n· KC装甲：当本机受击时，可消耗本部件的充能标记，将受击骰结果中的{闪电}视为{防御}。"
  },
  {
    "id": "LHTR-302",
    "name": "TM35B\n“野牛”\n突击核心",
    "type": "torso",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": "· KC装甲：当本机受击时，可消耗本部件的充能标记，将受击骰结果中的{闪电}视为{防御}。"
  },
  {
    "id": "nan",
    "name": "TM641O\n“章鱼”\n隐秘核心试作型",
    "type": "torso",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": "· 隐秘X：光学迷彩解除时，本机在X格范围内现身。\n· 静默：执行本动作时不会解除光学迷彩与低特征。"
  },
  {
    "id": "nan",
    "name": "TM39D\n“眼镜蛇”\n战术核心",
    "type": "torso",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": "· 静默：执行本动作时不会解除光学迷彩与低特征。\n· 监视射击标记：在延迟阶段的最后，移除本标记，本单位可执行1个射击动作。"
  },
  {
    "id": "nan",
    "name": "TM35BT\n“金牛”\n实验核心",
    "type": "torso",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": "· KC装甲：当本机受击时，可消耗本部件的充能标记，将受击骰结果中的{闪电}视为{防御}。"
  },
  {
    "id": "nan",
    "name": "TM31RS\n“黑猫”\n辅助核心",
    "type": "torso",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": "· 静默：执行本动作时不会解除光学迷彩与低特征。"
  },
  {
    "id": "nan",
    "name": "TM35NA\n“尼罗鳄”\n电战核心",
    "type": "torso",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": "· KC装甲：当本机受击时，可消耗本部件的充能标记，将受击骰结果中的{闪电}视为{防御}。\n· 静默：执行本动作时不会解除光学迷彩与低特征。"
  },
  {
    "id": "nan",
    "name": "TM31Q\n“野猫”\n主战核心",
    "type": "torso",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": "·指令生成X：指令阶段开始时，本机自动生成X枚指令标记。"
  },
  {
    "id": "nan",
    "name": "TM31KC\n“灰狼”KC型实验核心",
    "type": "torso",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": "·曲射：本动作不需要对落点或目标有视线。"
  },
  {
    "id": "nan",
    "name": "TM39B\n“蝮蛇II”\n低征核心",
    "type": "torso",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": "· 静默：执行本动作时不会解除光学迷彩与低特征。"
  },
  {
    "id": "LHLT-101",
    "name": "LM231\n标准下肢",
    "type": "chasis",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": "nan"
  },
  {
    "id": "LHLT-201",
    "name": "LM210S\n隐秘下肢",
    "type": "chasis",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": "· 静默：执行本动作时不会解除光学迷彩与低特征。"
  },
  {
    "id": "LHLT-301",
    "name": "LM213B\n格斗下肢",
    "type": "chasis",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": "nan"
  },
  {
    "id": "nan",
    "name": "LM210SO\n隐秘下肢试作型",
    "type": "chasis",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": "· 静默：执行本动作时不会解除光学迷彩与低特征。"
  },
  {
    "id": "LHLA-101",
    "name": "S9“流星”盾 + M5刺桩",
    "type": "leftHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "LHRA-101",
    "name": "R7自动步枪",
    "type": "rightHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "LHRA-101",
    "name": "R7自动步枪（抛弃卡）",
    "type": "rightHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "LHRA-102",
    "name": "R33狙击步枪",
    "type": "rightHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "LHLA-103",
    "name": "S100大盾 + 手雷荚舱",
    "type": "leftHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "LHLA-103",
    "name": "S100大盾 + 手雷荚舱（抛弃卡）",
    "type": "leftHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "LHRA-103",
    "name": "R6冲锋枪",
    "type": "rightHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "LHRA-103",
    "name": "R6冲锋枪（抛弃卡）",
    "type": "rightHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "LHLA-104",
    "name": "RH21手枪 + M3振剑（左）",
    "type": "leftHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "LHLA-104",
    "name": "RH21手枪·M3振剑（左）（抛弃卡）",
    "type": "leftHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "LHRA-104",
    "name": "RH21手枪 + M3振剑（右）",
    "type": "rightHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "LHRA-104",
    "name": "RH21手枪·M3振剑（右）（抛弃卡）",
    "type": "rightHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "LHRA-105O",
    "name": "S100大盾 + R6SS肩炮",
    "type": "rightHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "LHRA-105O",
    "name": "S100大盾 + R6SS肩炮（抛弃卡）",
    "type": "rightHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "LHLA-106GK",
    "name": "MDXS\"精灵\"系统 + R6冲锋枪（左）",
    "type": "leftHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "LHLA-106GK",
    "name": "MDXS\"精灵\"系统 + R6冲锋枪（左）（抛弃卡）",
    "type": "leftHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "LHRA-106GK",
    "name": "MDXS\"精灵\"系统 + R6冲锋枪（右）",
    "type": "rightHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "LHRA-106GK",
    "name": "MDXS\"精灵\"系统 + R6冲锋枪（右）（抛弃卡）",
    "type": "rightHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "LHLA-201",
    "name": "MSH1稳定辅助臂（左）",
    "type": "leftHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "LHRA-201",
    "name": "IGX920重型离子炮",
    "type": "rightHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "LHRA-201",
    "name": "IGX920重型离子炮（抛弃卡）",
    "type": "rightHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "LHRA-202",
    "name": "R6SD冲锋枪",
    "type": "rightHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "LHRA-202",
    "name": "R6SD冲锋枪（抛弃卡）",
    "type": "rightHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "LHLA-203",
    "name": "K9钉刺枪 + M14BO“胁差”",
    "type": "leftHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "LHRA-203",
    "name": "R9B战术步枪",
    "type": "rightHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "LHRA-203",
    "name": "R9B战术步枪（抛弃卡）",
    "type": "rightHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "LHLA-204",
    "name": "RKG70导弹巢",
    "type": "leftHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "LHLA-204",
    "name": "RKG70导弹巢（抛弃卡）",
    "type": "leftHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "LHLA-205",
    "name": "M3S振剑（左）",
    "type": "leftHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "LHRA-205",
    "name": "M3S振剑（右） ",
    "type": "rightHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "LHLA-206",
    "name": "M4振剑 + 手雷荚舱（左）",
    "type": "leftHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "LHRA-206",
    "name": "M4振剑 + 手雷荚舱（右）",
    "type": "rightHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "LHLA-301",
    "name": "MX82多功能鞭索",
    "type": "leftHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "LHRA-301",
    "name": "IGX350离子霰弹枪",
    "type": "rightHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "LHRA-301",
    "name": "IGX350离子霰弹枪（抛弃卡）",
    "type": "rightHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "LHLA-302",
    "name": "S100大盾",
    "type": "leftHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "LHLA-302",
    "name": "S100大盾（抛弃卡）",
    "type": "leftHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "LHLA-303",
    "name": "K7钉刺枪 + S10中盾",
    "type": "leftHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "LHRA-303",
    "name": "M15BO\"打刀\"",
    "type": "rightHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "LHLA-304",
    "name": "G6霰射炮 + 手雷荚舱",
    "type": "leftHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "LHLA-304",
    "name": "G6霰射炮 + 手雷荚舱（抛弃卡）",
    "type": "leftHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "LHRA-304",
    "name": "G6霰射炮 + M5刺桩",
    "type": "rightHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "LHRA-304",
    "name": "G6霰射炮 + M5刺桩（抛弃卡）",
    "type": "rightHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "LHLA-305SEO",
    "name": "RHX23“暴雨”突击手枪（左）",
    "type": "leftHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "LHLA-305SEO",
    "name": "RHX23“暴雨”突击手枪（左）（抛弃卡）",
    "type": "leftHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "LHRA-305SEO",
    "name": "RHX23“暴雨”突击手枪（右）",
    "type": "leftHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "LHRA-305SEO",
    "name": "RHX23“暴雨”突击手枪（右）（抛弃卡）",
    "type": "leftHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "nan",
    "name": "K9钉刺枪 + M14BO“胁差”试作型（左）",
    "type": "leftHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "nan",
    "name": "K9钉刺枪 + M14BO“胁差”试作型（右）",
    "type": "rightHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "nan",
    "name": "[金汤力]小奖赛奖杯",
    "type": "rightHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "nan",
    "name": "K21重型钉刺枪",
    "type": "rightHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "nan",
    "name": "K21重型钉刺枪（抛弃卡）",
    "type": "rightHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "nan",
    "name": "XTC右臂",
    "type": "rightHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "nan",
    "name": "R33S静默狙击枪",
    "type": "rightHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "nan",
    "name": "S100大盾 + R6SS肩炮（左）",
    "type": "leftHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "nan",
    "name": "S100大盾 + R6SS肩炮（抛弃卡）",
    "type": "leftHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "nan",
    "name": "R7MG轻机枪",
    "type": "rightHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "nan",
    "name": "R7MG轻机枪（抛弃卡）",
    "type": "rightHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "nan",
    "name": "S9“流星”盾 + IGX106离子炮",
    "type": "leftHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "nan",
    "name": "R7K战术步枪",
    "type": "rightHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "nan",
    "name": "R7K战术步枪（抛弃卡）",
    "type": "rightHand",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": ""
  },
  {
    "id": "LHBP-101",
    "name": "EBS/X40护甲充能器",
    "type": "backpack",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": "\n· KC装甲：当本机受击时，可消耗本部件的充能标记，将受击骰结果中的{闪电}视为{防御}。"
  },
  {
    "id": "LHBP-102",
    "name": "GSD2A“幽灵蛛”挂架",
    "type": "backpack",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": "·曲射：本动作不需要对落点或目标有视线。\n·投掷：执行本动作时必须指定一个空手。"
  },
  {
    "id": "LHBP-103",
    "name": "CSC60冷却剂背包",
    "type": "backpack",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": "·激光武器：命中使目标获得脆弱标记。"
  },
  {
    "id": "LHBP-201",
    "name": "DBP“龟壳”掩体挂架",
    "type": "backpack",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": "nan"
  },
  {
    "id": "LHBP-202",
    "name": "AMDS210“翠雀”携带包",
    "type": "backpack",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": "nan"
  },
  {
    "id": "LHBP-203",
    "name": "RKG70弹药补充包",
    "type": "backpack",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": "nan"
  },
  {
    "id": "LHBP-204",
    "name": "MSH2稳定臂",
    "type": "backpack",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": "· 全向射击：本动作没有射界限制。"
  },
  {
    "id": "LHBP-301",
    "name": "JP1喷射包",
    "type": "backpack",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": "· 空中移动：本动作视为飞行。"
  },
  {
    "id": "LHBP-302",
    "name": "EC50电战荚舱",
    "type": "backpack",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": "nan"
  },
  {
    "id": "LHBP-303",
    "name": "OCSP超载包",
    "type": "backpack",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": "nan"
  },
  {
    "id": "LHBP-101",
    "name": "EBS/X40护甲充能器试作型",
    "type": "backpack",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": "\n· KC装甲：当本机受击时，可消耗本部件的充能标记，将受击骰结果中的{闪电}视为{防御}。"
  },
  {
    "id": "nan",
    "name": "JP5机动提升包",
    "type": "backpack",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": "nan"
  },
  {
    "id": "nan",
    "name": "OCS85 黑箱携带挂架",
    "type": "backpack",
    "score": 0,
    "structure": 0,
    "armor": 0,
    "parray": 0,
    "dodge": 0,
    "electronic": 0,
    "description": "nan"
  }
];
